import {
  BookProductionSettings,
  NamedStyleId,
  PageGeometry,
  PrintGuidesConfig,
  TRIM_PRESET_MAP,
  TrimPreset,
  TypographyStyle,
} from '../types/bookLayoutTypes';

export const MM_TO_PT = 2.83465; // 1 mm = 2.83465 points
export const PT_TO_MM = 0.352778;

export const DEFAULT_TYPOGRAPHY_STYLES: Record<NamedStyleId, TypographyStyle> = {
  book_title: {
    id: 'book_title',
    label: 'Book Title',
    fontFamily: 'serif',
    fontSizePt: 26,
    fontWeight: '700',
    italic: false,
    lineHeight: 1.2,
    letterSpacingEm: -0.01,
    spaceBeforePt: 0,
    spaceAfterPt: 16,
    alignment: 'center',
    color: '#5A1832', // Burgundy
  },
  unit_title: {
    id: 'unit_title',
    label: 'Unit Title',
    fontFamily: 'serif',
    fontSizePt: 20,
    fontWeight: '700',
    italic: false,
    lineHeight: 1.25,
    letterSpacingEm: 0,
    spaceBeforePt: 24,
    spaceAfterPt: 12,
    alignment: 'left',
    color: '#9A7438', // Antique Gold Dark
  },
  chapter_title: {
    id: 'chapter_title',
    label: 'Chapter Title',
    fontFamily: 'serif',
    fontSizePt: 18,
    fontWeight: '700',
    italic: false,
    lineHeight: 1.3,
    letterSpacingEm: -0.005,
    spaceBeforePt: 18,
    spaceAfterPt: 10,
    alignment: 'left',
    color: '#292521',
  },
  chapter_subtitle: {
    id: 'chapter_subtitle',
    label: 'Chapter Subtitle / Learning Goals',
    fontFamily: 'serif',
    fontSizePt: 11,
    fontWeight: '500',
    italic: true,
    lineHeight: 1.45,
    letterSpacingEm: 0,
    spaceBeforePt: 4,
    spaceAfterPt: 14,
    alignment: 'left',
    color: '#71685E',
  },
  heading_1: {
    id: 'heading_1',
    label: 'Heading 1 (Major Section)',
    fontFamily: 'serif',
    fontSizePt: 14,
    fontWeight: '700',
    italic: false,
    lineHeight: 1.35,
    letterSpacingEm: 0,
    spaceBeforePt: 14,
    spaceAfterPt: 6,
    alignment: 'left',
    color: '#5A1832',
  },
  heading_2: {
    id: 'heading_2',
    label: 'Heading 2 (Sub-section)',
    fontFamily: 'serif',
    fontSizePt: 12,
    fontWeight: '600',
    italic: false,
    lineHeight: 1.4,
    letterSpacingEm: 0,
    spaceBeforePt: 10,
    spaceAfterPt: 4,
    alignment: 'left',
    color: '#292521',
  },
  heading_3: {
    id: 'heading_3',
    label: 'Heading 3 (Rule / Element)',
    fontFamily: 'sans-serif',
    fontSizePt: 10.5,
    fontWeight: '700',
    italic: false,
    lineHeight: 1.4,
    letterSpacingEm: 0.01,
    spaceBeforePt: 8,
    spaceAfterPt: 4,
    alignment: 'left',
    color: '#4B3F35',
  },
  body: {
    id: 'body',
    label: 'Body Text',
    fontFamily: 'serif',
    fontSizePt: 10.5,
    fontWeight: '400',
    italic: false,
    lineHeight: 1.5,
    letterSpacingEm: 0,
    spaceBeforePt: 0,
    spaceAfterPt: 6,
    alignment: 'justify',
    color: '#292521',
  },
  example: {
    id: 'example',
    label: 'Example & Model Prose',
    fontFamily: 'serif',
    fontSizePt: 10,
    fontWeight: '400',
    italic: true,
    lineHeight: 1.45,
    letterSpacingEm: 0,
    spaceBeforePt: 4,
    spaceAfterPt: 6,
    alignment: 'left',
    color: '#382D25',
  },
  grammar_rule: {
    id: 'grammar_rule',
    label: 'Grammar Rule Enunciation',
    fontFamily: 'serif',
    fontSizePt: 10.5,
    fontWeight: '600',
    italic: false,
    lineHeight: 1.45,
    letterSpacingEm: 0,
    spaceBeforePt: 6,
    spaceAfterPt: 6,
    alignment: 'left',
    color: '#5A1832',
  },
  exercise_heading: {
    id: 'exercise_heading',
    label: 'Exercise Heading',
    fontFamily: 'serif',
    fontSizePt: 12.5,
    fontWeight: '700',
    italic: false,
    lineHeight: 1.35,
    letterSpacingEm: 0,
    spaceBeforePt: 14,
    spaceAfterPt: 6,
    alignment: 'left',
    color: '#5A1832',
  },
  exercise_instruction: {
    id: 'exercise_instruction',
    label: 'Exercise Instruction',
    fontFamily: 'serif',
    fontSizePt: 10,
    fontWeight: '500',
    italic: true,
    lineHeight: 1.4,
    letterSpacingEm: 0,
    spaceBeforePt: 2,
    spaceAfterPt: 8,
    alignment: 'left',
    color: '#524338',
  },
  question: {
    id: 'question',
    label: 'Exercise Question Item',
    fontFamily: 'serif',
    fontSizePt: 10,
    fontWeight: '400',
    italic: false,
    lineHeight: 1.45,
    letterSpacingEm: 0,
    spaceBeforePt: 4,
    spaceAfterPt: 6,
    alignment: 'left',
    color: '#292521',
  },
  caption: {
    id: 'caption',
    label: 'Figure / Table Caption',
    fontFamily: 'sans-serif',
    fontSizePt: 8.5,
    fontWeight: '500',
    italic: true,
    lineHeight: 1.35,
    letterSpacingEm: 0,
    spaceBeforePt: 4,
    spaceAfterPt: 8,
    alignment: 'center',
    color: '#71685E',
  },
  footnote: {
    id: 'footnote',
    label: 'Footnote / Citation',
    fontFamily: 'serif',
    fontSizePt: 8,
    fontWeight: '400',
    italic: false,
    lineHeight: 1.3,
    letterSpacingEm: 0,
    spaceBeforePt: 2,
    spaceAfterPt: 2,
    alignment: 'left',
    color: '#71685E',
  },
  teacher_note: {
    id: 'teacher_note',
    label: 'Teacher Annotation / Margin Note',
    fontFamily: 'sans-serif',
    fontSizePt: 9,
    fontWeight: '600',
    italic: false,
    lineHeight: 1.35,
    letterSpacingEm: 0.01,
    spaceBeforePt: 4,
    spaceAfterPt: 6,
    alignment: 'left',
    color: '#5A1832',
  },
  running_header: {
    id: 'running_header',
    label: 'Running Header',
    fontFamily: 'serif',
    fontSizePt: 8.5,
    fontWeight: '600',
    italic: false,
    lineHeight: 1.2,
    letterSpacingEm: 0.08,
    spaceBeforePt: 0,
    spaceAfterPt: 0,
    alignment: 'left',
    color: '#9A7438',
  },
  page_number: {
    id: 'page_number',
    label: 'Page Folio Number',
    fontFamily: 'serif',
    fontSizePt: 9,
    fontWeight: '700',
    italic: false,
    lineHeight: 1.2,
    letterSpacingEm: 0.02,
    spaceBeforePt: 0,
    spaceAfterPt: 0,
    alignment: 'center',
    color: '#5A1832',
  },
};

export const DEFAULT_PAGE_GEOMETRY: PageGeometry = {
  topMarginMm: 18,
  bottomMarginMm: 20,
  insideMarginMm: 22, // Gutter side
  outsideMarginMm: 16,
  gutterMm: 3, // Binding shift
  headerDistanceMm: 10,
  footerDistanceMm: 11,
  facingPages: true,
};

export const DEFAULT_PRINT_GUIDES: PrintGuidesConfig = {
  showMargins: true,
  showBleed: false,
  showTrim: true,
  showSafeArea: true,
  showBaselineGrid: false,
  showColumnGuides: false,
};

export const DEFAULT_PRODUCTION_SETTINGS: BookProductionSettings = {
  id: 'preset-crown-quarto-school',
  presetName: 'Crown Quarto (School Standard)',
  trimPreset: 'crown_quarto',
  geometry: { ...DEFAULT_PAGE_GEOMETRY },
  bleed: {
    bleedMm: 3,
    slugTopMm: 0,
    slugBottomMm: 0,
    slugInsideMm: 0,
    slugOutsideMm: 0,
  },
  guides: { ...DEFAULT_PRINT_GUIDES },
  typography: { ...DEFAULT_TYPOGRAPHY_STYLES },
  runningHeaders: {
    leftHeaderContent: 'series_title',
    rightHeaderContent: 'chapter_title',
    suppressOnChapterOpener: true,
    suppressOnFrontMatter: true,
    separator: 'rule',
  },
  pageNumbers: {
    position: 'bottom_outside',
    frontMatterFormat: 'roman',
    mainMatterFormat: 'arabic',
    suppressOnChapterOpener: false,
    suppressOnTitlePages: true,
  },
  defaultAnswerSpace: 'lines',
  startChapterOnRightPage: true,
  keepHeadingsWithNext: true,
  avoidBreakInsideExercise: true,
  twoColumnGlossary: true,
  colorMode: 'full_colour',
  edition: 'student',
  paperStock: '80gsm',
  paperTint: 'cream',
  zoomPercent: 100,
  canvasMode: 'spread',
};

// Preset Profiles
export const DESIGN_PRESET_PROFILES: Record<string, Partial<BookProductionSettings>> = {
  'Crown Quarto (School Standard)': {
    presetName: 'Crown Quarto (School Standard)',
    trimPreset: 'crown_quarto',
    geometry: {
      topMarginMm: 18,
      bottomMarginMm: 20,
      insideMarginMm: 22,
      outsideMarginMm: 16,
      gutterMm: 3,
      headerDistanceMm: 10,
      footerDistanceMm: 11,
      facingPages: true,
    },
    bleed: { bleedMm: 3, slugTopMm: 0, slugBottomMm: 0, slugInsideMm: 0, slugOutsideMm: 0 },
    defaultAnswerSpace: 'lines',
    twoColumnGlossary: true,
  },
  'Royal Octavo (Academic Prose)': {
    presetName: 'Royal Octavo (Academic Prose)',
    trimPreset: 'royal_octavo',
    geometry: {
      topMarginMm: 16,
      bottomMarginMm: 18,
      insideMarginMm: 20,
      outsideMarginMm: 14,
      gutterMm: 2.5,
      headerDistanceMm: 9,
      footerDistanceMm: 10,
      facingPages: true,
    },
    bleed: { bleedMm: 3, slugTopMm: 0, slugBottomMm: 0, slugInsideMm: 0, slugOutsideMm: 0 },
    defaultAnswerSpace: 'box',
    twoColumnGlossary: false,
  },
  'Standard A4 (Classroom Workbook)': {
    presetName: 'Standard A4 (Classroom Workbook)',
    trimPreset: 'a4',
    geometry: {
      topMarginMm: 20,
      bottomMarginMm: 22,
      insideMarginMm: 24,
      outsideMarginMm: 18,
      gutterMm: 4,
      headerDistanceMm: 12,
      footerDistanceMm: 12,
      facingPages: true,
    },
    bleed: { bleedMm: 0, slugTopMm: 0, slugBottomMm: 0, slugInsideMm: 0, slugOutsideMm: 0 },
    defaultAnswerSpace: 'writing_area',
    twoColumnGlossary: true,
  },
  'US Trade (Classic 6"×9")': {
    presetName: 'US Trade (Classic 6"×9")',
    trimPreset: 'us_trade',
    geometry: {
      topMarginMm: 16,
      bottomMarginMm: 18,
      insideMarginMm: 19,
      outsideMarginMm: 13,
      gutterMm: 2,
      headerDistanceMm: 8,
      footerDistanceMm: 9,
      facingPages: true,
    },
    bleed: { bleedMm: 3.175, slugTopMm: 0, slugBottomMm: 0, slugInsideMm: 0, slugOutsideMm: 0 },
    defaultAnswerSpace: 'blank',
    twoColumnGlossary: false,
  },
};

const STORAGE_KEY = 'novelcraft_book_layout_settings_v1';

export function loadBookProductionSettings(): BookProductionSettings {
  try {
    const saved = localStorage.getItem(STORAGE_KEY);
    if (saved) {
      const parsed = JSON.parse(saved);
      return {
        ...DEFAULT_PRODUCTION_SETTINGS,
        ...parsed,
        geometry: { ...DEFAULT_PRODUCTION_SETTINGS.geometry, ...parsed.geometry },
        guides: { ...DEFAULT_PRODUCTION_SETTINGS.guides, ...parsed.guides },
        typography: { ...DEFAULT_PRODUCTION_SETTINGS.typography, ...parsed.typography },
        runningHeaders: { ...DEFAULT_PRODUCTION_SETTINGS.runningHeaders, ...parsed.runningHeaders },
        pageNumbers: { ...DEFAULT_PRODUCTION_SETTINGS.pageNumbers, ...parsed.pageNumbers },
      };
    }
  } catch (e) {
    console.error('Failed to load layout settings from localStorage:', e);
  }
  return { ...DEFAULT_PRODUCTION_SETTINGS };
}

export function saveBookProductionSettings(settings: BookProductionSettings): void {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(settings));
  } catch (e) {
    console.error('Failed to save layout settings to localStorage:', e);
  }
}
