import { ChapterStructuralTemplate, ContentBlockType } from '../types';

export const CHAPTER_STRUCTURAL_TEMPLATES: ChapterStructuralTemplate[] = [
  {
    id: 'tpl-grammar-concept',
    type: 'grammar_concept',
    name: 'Grammar Concept Chapter',
    description: 'Ideal for theoretical foundation topics (e.g. Parts of Speech, Tenses, Concord). Structured with progressive definitions, rules, contrastive pairs, and tiered drills.',
    recommendedStages: ['Concept Exploration', 'Formal Rule Deduction', 'Contrastive Pairs', 'Guided Practice', 'Independent Mastery'],
    recommendedBlocks: [
      { type: 'heading', title: 'Chapter Heading', brief: 'Title and syllabus strand reference' },
      { type: 'definition', title: 'Formal Definition', brief: 'Core grammatical definition with age-appropriate terminology' },
      { type: 'grammar_rule', title: 'Golden Rule', brief: 'Primary prescriptive or descriptive rule formula' },
      { type: 'example_pair', title: 'Correct vs Incorrect Pair', brief: 'Side-by-side demonstration of error trap' },
      { type: 'worked_example', title: 'Step-by-Step Application', brief: 'Walkthrough of syntactic analysis' },
      { type: 'tip', title: 'Memory Aid / Exam Tip', brief: 'Mnemonic or critical board examination reminder' },
      { type: 'summary', title: 'Chapter Summary Box', brief: 'Recap of core formulas and rules' },
    ],
    exerciseStructure: [
      'Exercise A: Identification & Classification (Objective / MCQ)',
      'Exercise B: Fill in Blanks with Correct Form (Semi-structured)',
      'Exercise C: Error Identification & Correction (Analytical)',
    ],
    assessmentRequirements: '10–15 mark Chapter Test covering Knowledge, Application, and Analytical correction.',
    summaryStructure: ['Key definition recap', 'Syntax formula matrix', 'Top 3 common student traps'],
    teacherNoteStructure: ['Anticipated learner misconceptions', 'Recommended tactile / oral classroom opener', 'Differentiation for struggling learners'],
  },
  {
    id: 'tpl-usage-application',
    type: 'usage_application',
    name: 'Usage & Application Chapter',
    description: 'Designed for functional grammar in authentic writing and conversational contexts (e.g. Determiners, Modals, Prepositions).',
    recommendedStages: ['Contextual Discovery', 'Nuance & Register', 'Collocation & Patterning', 'Real-World Tasks'],
    recommendedBlocks: [
      { type: 'heading', title: 'Contextual Usage Header', brief: 'Situational context overview' },
      { type: 'worked_example', title: 'Contextual Dialogue / Excerpt', brief: 'Authentic passage demonstrating target forms' },
      { type: 'comparison_table', title: 'Subtle Distinctions Matrix', brief: 'Comparing similar items (e.g. May vs Might, In vs At)' },
      { type: 'watch_out', title: 'Register & Politeness Warning', brief: 'Formal vs informal register guidelines' },
      { type: 'exercise', title: 'Contextual Fillers Drill', brief: 'Passage-level gap fill' },
    ],
    exerciseStructure: [
      'Exercise A: Register Selection (Formal vs Informal)',
      'Exercise B: Passage Editing & Cohesion',
      'Exercise C: Situational Sentence Generation',
    ],
    assessmentRequirements: 'Application in continuous prose and dialogue completion.',
    summaryStructure: ['Usage quick reference table', 'Politeness and tone checklist'],
    teacherNoteStructure: ['Communicative pair work activities', 'Real-life authentic text suggestions'],
  },
  {
    id: 'tpl-sentence-transformation',
    type: 'sentence_transformation',
    name: 'Sentence Transformation Chapter',
    description: 'Focuses on structural syntax manipulation (Active-Passive, Direct-Indirect Speech, Degree of Comparison, Simple-Compound-Complex).',
    recommendedStages: ['Structural Blueprint', 'Stepwise Conversion Algorithm', 'Marker & Tense Shift', 'Bi-directional Transformation'],
    recommendedBlocks: [
      { type: 'heading', title: 'Transformation Rule Set', brief: 'Conversion overview and syntactic goals' },
      { type: 'diagram', title: 'Syntactic Shift Diagram', brief: 'Visual mapping of subject-object transposition' },
      { type: 'table', title: 'Tense & Pronoun Shift Table', brief: 'Direct reference lookup chart' },
      { type: 'worked_example', title: 'Step-by-Step Conversion', brief: 'Three-step procedure breakdown' },
      { type: 'warning_trap', title: 'Common Structural Pitfall', brief: 'Unchanged tenses in universal truths or passive agent drops' },
    ],
    exerciseStructure: [
      'Exercise A: Guided Transformation (Given starter phrase)',
      'Exercise B: Free Transformation without starter',
      'Exercise C: Synthesis of Two Clauses into One',
    ],
    assessmentRequirements: 'Board-pattern sentence rewrite questions with strict marking criteria.',
    summaryStructure: ['Transformation formula cheat sheet', 'Tense concordance table'],
    teacherNoteStructure: ['Visual sentence mapping techniques', 'Choral drill patterns'],
  },
  {
    id: 'tpl-composition',
    type: 'composition',
    name: 'Composition & Writing Chapter',
    description: 'Structured rhetoric and writing formats (Notice Writing, Formal Letters, Descriptive Essays, Diary Entries).',
    recommendedStages: ['Format & Layout', 'Content & Organization', 'Stylistic Expressions', 'Model Sample Analysis', 'Scaffolded Writing Task'],
    recommendedBlocks: [
      { type: 'heading', title: 'Format Specification', brief: 'Official board marks distribution breakdown' },
      { type: 'worked_example', title: 'Annotated Model Composition', brief: 'Full exemplar with margin annotations' },
      { type: 'vocabulary', title: 'High-Impact Vocabulary Bank', brief: 'Transition phrases, evocative adjectives, formal signposts' },
      { type: 'tip', title: 'Marking Scheme Rubric', brief: 'Format (1m), Content (2m), Expression (2m)' },
      { type: 'try_this', title: 'Drafting Prompts', brief: 'Three graduated writing topics with prompt hints' },
    ],
    exerciseStructure: [
      'Exercise A: Error Correction in Format',
      'Exercise B: Paragraph Development from Bullet Outlines',
      'Exercise C: Complete Composition Task under exam constraints',
    ],
    assessmentRequirements: 'Full rubric-based writing evaluation with peer-review checklist.',
    summaryStructure: ['Format skeleton diagram', 'Self-editing 5-point checklist'],
    teacherNoteStructure: ['Time-management suggestions for exam writing', 'Differentiated sentence starters'],
  },
  {
    id: 'tpl-vocabulary',
    type: 'vocabulary',
    name: 'Vocabulary & Word Study Chapter',
    description: 'Etymology, Affixes, Idioms, Phrasal Verbs, and Academic Collocations.',
    recommendedStages: ['Root/Affix Analysis', 'Meaning in Context', 'Collocational Clustered Sets', 'Creative Integration'],
    recommendedBlocks: [
      { type: 'heading', title: 'Etymology & Morphological Roots', brief: 'Prefix, stem, and suffix derivation' },
      { type: 'table', title: 'Root Family Table', brief: 'Family of words derived from target root' },
      { type: 'example_set', title: 'Idiomatic Collocations in Sentences', brief: 'Illustrative sentences showcasing correct nuance' },
      { type: 'common_error', title: 'False Friends & Easily Confused Words', brief: 'e.g. Accept vs Except, Principal vs Principle' },
    ],
    exerciseStructure: [
      'Exercise A: Context Clues & Synonyms/Antonyms',
      'Exercise B: Word Formation using Affixes',
      'Exercise C: Phrasal Verb Replacement in Paragraphs',
    ],
    assessmentRequirements: 'Spelling, morphological inflection, and cloze passage testing.',
    summaryStructure: ['Master root reference chart', 'Top 20 phrasal verbs with definitions'],
    teacherNoteStructure: ['Etymological storytelling suggestions', 'Weekly vocabulary expansion routine'],
  },
  {
    id: 'tpl-revision',
    type: 'revision',
    name: 'Comprehensive Revision Chapter',
    description: 'Term-end or unit-end synthesis reviewing multiple grammatical strands with diagnostic feedback.',
    recommendedStages: ['Comprehensive Concept Review', 'Cross-Topic Synthesis', 'Diagnostic Self-Assessment'],
    recommendedBlocks: [
      { type: 'heading', title: 'Unit Diagnostic Overview', brief: 'List of interconnected concepts covered' },
      { type: 'table', title: 'Master Syntax & Rules Matrix', brief: 'Consolidated formulas from previous chapters' },
      { type: 'tip', title: 'Exam Strategy & Time Management', brief: 'How to tackle mixed grammar sections efficiently' },
    ],
    exerciseStructure: [
      'Section 1: Quick Fire Concept Check (20 questions)',
      'Section 2: Integrated Grammar Cloze & Editing (Board Pattern)',
      'Section 3: Structural Sentence Rewriting',
    ],
    assessmentRequirements: 'Full 25–40 mark term paper simulating board examination conditions.',
    summaryStructure: ['Remedial flowchart: "If you scored under 70%, review Chapter X"'],
    teacherNoteStructure: ['Error frequency matrix', 'Remedial intervention groupings'],
  },
  {
    id: 'tpl-assessment-practice',
    type: 'assessment_practice',
    name: 'Assessment & Practice Chapter',
    description: 'Exam-mode mock papers and sample test batteries with comprehensive marking keys.',
    recommendedStages: ['Timed Paper 1 (Standard)', 'Timed Paper 2 (Challenging)', 'Detailed Marking Scheme'],
    recommendedBlocks: [
      { type: 'heading', title: 'Board Exam Mock Test Specifications', brief: 'Duration, Marks, General Instructions' },
      { type: 'important_note', title: 'Marking Scheme Guidelines', brief: 'Step marking and zero penalty instructions' },
    ],
    exerciseStructure: [
      'Test Paper A: Foundation Level (25 Marks, 40 Mins)',
      'Test Paper B: Advanced Olympiad / Board Standard (35 Marks, 60 Mins)',
    ],
    assessmentRequirements: 'Complete marking key with rationale for every distractor.',
    summaryStructure: ['Performance score bands and recommendations'],
    teacherNoteStructure: ['Moderation notes and border-line mark guidance'],
  },
  {
    id: 'tpl-custom',
    type: 'custom',
    name: 'Custom Structural Template',
    description: 'Empty chapter shell with standard header, introductory section, practice container, and teacher reflection.',
    recommendedStages: ['Introduction', 'Core Content', 'Practice', 'Review'],
    recommendedBlocks: [
      { type: 'heading', title: 'Chapter Introduction', brief: 'Overview and learning outcomes' },
      { type: 'text', title: 'Theoretical Exposition', brief: 'Author body text' },
      { type: 'exercise', title: 'Practice Exercises', brief: 'Question set shell' },
    ],
    exerciseStructure: ['Exercise 1: Standard Practice'],
    assessmentRequirements: 'Author defined assessment requirements.',
    summaryStructure: ['Author defined summary points.'],
    teacherNoteStructure: ['Author defined teacher notes.'],
  },
];
