import {
  CurriculumSystemId,
  ProgressionStage,
  MasterGrammarConcept,
  CrossSystemLearningBand,
  FrameworkPolicyStatus,
  CurriculumEvidenceMetadata,
  EvidenceVerificationStatus,
  ConceptBookImplementation,
  SystemProgressionRecord,
  CurriculumDivergenceInsight,
  EarlyYearsPedagogicalModel,
  CurriculumClaimType,
  ClaimEvidenceRecord,
} from '../types';

// ============================================================================
// 1. CROSS-SYSTEM LEARNING BANDS (REPLACING UNILATERAL EQUIVALENCES)
// ============================================================================
export const CROSS_SYSTEM_LEARNING_BANDS: CrossSystemLearningBand[] = [
  {
    bandId: 'band-3',
    bandLabel: 'Learning Band 3',
    ageBracket: 'Ages 7–8 (Primary Phase)',
    cbseLevel: 'Class 3',
    cisceLevel: 'Class 3',
    cambridgeLevel: 'Cambridge Primary Stage 3',
    editorialDisclaimer: 'Editorial comparison only — not an official equivalence.',
  },
  {
    bandId: 'band-4',
    bandLabel: 'Learning Band 4',
    ageBracket: 'Ages 8–9 (Primary Phase)',
    cbseLevel: 'Class 4',
    cisceLevel: 'Class 4',
    cambridgeLevel: 'Cambridge Primary Stage 4',
    editorialDisclaimer: 'Editorial comparison only — not an official equivalence.',
  },
  {
    bandId: 'band-5',
    bandLabel: 'Learning Band 5',
    ageBracket: 'Ages 9–10 (Upper Primary)',
    cbseLevel: 'Class 5',
    cisceLevel: 'Class 5',
    cambridgeLevel: 'Cambridge Primary Stage 5',
    editorialDisclaimer: 'Editorial comparison only — not an official equivalence.',
  },
  {
    bandId: 'band-6',
    bandLabel: 'Learning Band 6',
    ageBracket: 'Ages 11–12 (Middle / Lower Secondary)',
    cbseLevel: 'Class 6',
    cisceLevel: 'Class 6',
    cambridgeLevel: 'Cambridge Lower Secondary Stage 7',
    editorialDisclaimer: 'Editorial comparison only — not an official equivalence.',
  },
  {
    bandId: 'band-7',
    bandLabel: 'Learning Band 7',
    ageBracket: 'Ages 12–13 (Middle / Lower Secondary)',
    cbseLevel: 'Class 7',
    cisceLevel: 'Class 7',
    cambridgeLevel: 'Cambridge Lower Secondary Stage 8',
    editorialDisclaimer: 'Editorial comparison only — not an official equivalence.',
  },
  {
    bandId: 'band-8',
    bandLabel: 'Learning Band 8',
    ageBracket: 'Ages 13–14 (Secondary Transition)',
    cbseLevel: 'Class 8',
    cisceLevel: 'Class 8',
    cambridgeLevel: 'Cambridge Lower Secondary Stage 9 (Checkpoint)',
    editorialDisclaimer: 'Editorial comparison only — not an official equivalence.',
  },
  {
    bandId: 'band-9',
    bandLabel: 'Learning Band 9',
    ageBracket: 'Ages 14–15 (Secondary / Upper Secondary)',
    cbseLevel: 'Class 9',
    cisceLevel: 'Class 9 (ICSE Prep)',
    cambridgeLevel: 'Cambridge IGCSE Year 10',
    editorialDisclaimer: 'Editorial comparison only — not an official equivalence.',
  },
  {
    bandId: 'band-10',
    bandLabel: 'Learning Band 10',
    ageBracket: 'Ages 15–16 (National / International Examinations)',
    cbseLevel: 'Class 10 (CBSE Board)',
    cisceLevel: 'Class 10 (ICSE Examination)',
    cambridgeLevel: 'Cambridge IGCSE Year 11 (Final Exams)',
    editorialDisclaimer: 'Editorial comparison only — not an official equivalence.',
  },
  {
    bandId: 'band-11',
    bandLabel: 'Learning Band 11',
    ageBracket: 'Ages 16–17 (Higher Secondary / Pre-U)',
    cbseLevel: 'Class 11',
    cisceLevel: 'Class 11 (ISC Prep)',
    cambridgeLevel: 'Cambridge International AS Level',
    editorialDisclaimer: 'Editorial comparison only — not an official equivalence.',
  },
  {
    bandId: 'band-12',
    bandLabel: 'Learning Band 12',
    ageBracket: 'Ages 17–18 (Graduating School Leaving)',
    cbseLevel: 'Class 12 (CBSE Board)',
    cisceLevel: 'Class 12 (ISC Board Examination)',
    cambridgeLevel: 'Cambridge International A Level',
    editorialDisclaimer: 'Editorial comparison only — not an official equivalence.',
  },
];

// ============================================================================
// 2. FRAMEWORK & POLICY PROFILES (DECOUPLED FROM UNIVERSAL ASSUMPTIONS)
// ============================================================================
export interface PolicyFrameworkProfile {
  id: string;
  frameworkName: string;
  educationSystem: CurriculumSystemId;
  programme: string;
  applicableClassRange: string;
  applicableEdition: string;
  publicationEffectiveYear: string;
  sourceReference: string;
  status: FrameworkPolicyStatus;
  notes: string;
  lastReviewed: string;
  reviewedBy: string;
}

export const FRAMEWORK_POLICY_PROFILES: PolicyFrameworkProfile[] = [
  {
    id: 'fp-cbse-ncf-2023',
    frameworkName: 'NCF-SE 2023 & NEP 2020 Pedagogical Guidelines',
    educationSystem: 'CBSE',
    programme: 'CBSE English Language & Literature (Classes 6–10)',
    applicableClassRange: 'Classes 6–10',
    applicableEdition: 'VERITAS CBSE Standard Series (Ed. 2024)',
    publicationEffectiveYear: '2023–24 (Effective 2024–2026)',
    sourceReference: 'CBSE Curriculum Secondary (Code 184) & NCF-SE Sec. 4.2',
    status: 'VERIFIED',
    notes: 'Prescribes integrated communicative grammar, error editing, and dialogic completion. Explicitly excludes rote isolated definitions.',
    lastReviewed: '2024-05-12',
    reviewedBy: 'Dr. Ananya Sen (CBSE Senior Curriculum Consultant)',
  },
  {
    id: 'fp-cisce-icse-2025',
    frameworkName: 'CISCE Regulations & Syllabuses for ICSE Examination',
    educationSystem: 'CISCE',
    programme: 'ICSE English Language Paper 1 (Question 5)',
    applicableClassRange: 'Classes 9–10 (with preparatory Class 6–8 grounding)',
    applicableEdition: 'VERITAS CISCE Classical Grammar Series (Ed. 2024)',
    publicationEffectiveYear: '2024–2026',
    sourceReference: 'CISCE Official Syllabuses 2025/2026, Section V English Language',
    status: 'VERIFIED',
    notes: 'Enforces Question 5 compulsory grammar: Q5(a) passage verb tenses (4m), Q5(b) prepositions (4m), Q5(c) join without "and/but/so" (4m), Q5(d) transformation (8m). Note: NEP 2020 does not supersede CISCE Council regulations without explicit CISCE notification.',
    lastReviewed: '2024-04-18',
    reviewedBy: 'Prof. Margaret Davies (CISCE Chief Examiner Ret.)',
  },
  {
    id: 'fp-cisce-primary-middle',
    frameworkName: 'CISCE Curriculum for Preschool to Class VIII',
    educationSystem: 'CISCE',
    programme: 'Junior & Middle School English Curriculum',
    applicableClassRange: 'Classes 3–8',
    applicableEdition: 'VERITAS CISCE Classical Grammar Series (Ed. 2024)',
    publicationEffectiveYear: '2016 (Reaffirmed 2022)',
    sourceReference: 'CISCE Preschool–VIII Curriculum Document, English Language',
    status: 'MAPPED',
    notes: 'Prescribes progressive parts of speech, active/passive voice introduction in Class 6, and conditional clauses in Class 7. Distinct from ICSE Class 10 exam rubric.',
    lastReviewed: '2024-04-20',
    reviewedBy: 'Prof. Margaret Davies',
  },
  {
    id: 'fp-cambridge-lower-sec',
    frameworkName: 'Cambridge Lower Secondary English Curriculum Framework (0861)',
    educationSystem: 'Cambridge',
    programme: 'Cambridge Lower Secondary (Stages 7–9)',
    applicableClassRange: 'Stages 7–9 (Checkpoint)',
    applicableEdition: 'VERITAS Cambridge International Edition (Ed. 2024)',
    publicationEffectiveYear: '2020 (Updated 2023 for 2024–2027)',
    sourceReference: 'Cambridge Assessment International Education Framework 0861',
    status: 'VERIFIED',
    notes: 'Enquiry-led linguistic analysis: passive voice for depersonalisation, complex sentence rhythms, modal hedging for diplomatic stance. Completely autonomous from Indian national policy frameworks.',
    lastReviewed: '2024-06-02',
    reviewedBy: 'Alistair Vance, MA Cantab (Cambridge CAIE Consultant)',
  },
  {
    id: 'fp-cambridge-igcse-0500',
    frameworkName: 'Cambridge IGCSE First Language English (0500 / 0990)',
    educationSystem: 'Cambridge',
    programme: 'Upper Secondary / IGCSE',
    applicableClassRange: 'Years 10–11',
    applicableEdition: 'VERITAS Cambridge International Edition (Ed. 2024)',
    publicationEffectiveYear: '2024–2026',
    sourceReference: 'Cambridge IGCSE First Language English Syllabus 2024–2026',
    status: 'VERIFIED',
    notes: 'Grammar assessed through extended writing criteria and summary precision. Does not test isolated grammar blank drills.',
    lastReviewed: '2024-06-05',
    reviewedBy: 'Alistair Vance, MA Cantab',
  },
];

// ============================================================================
// 3. INDEPENDENT BOARD CURRICULUM PROFILES
// ============================================================================
export interface IndependentBoardProfile {
  systemId: CurriculumSystemId;
  systemName: string;
  governingBody: string;
  primaryFrameworkDoc: string;
  syllabusYear: string;
  terminologyConventions: string[];
  pedagogicalCore: string;
  assessmentStructure: string;
  verificationStatus: EvidenceVerificationStatus;
  verificationEvidenceCount: number;
  unverifiedModelWarning?: string;
}

export const INDEPENDENT_BOARD_PROFILES: Record<CurriculumSystemId, IndependentBoardProfile> = {
  CBSE: {
    systemId: 'CBSE',
    systemName: 'Central Board of Secondary Education',
    governingBody: 'Ministry of Education, Government of India',
    primaryFrameworkDoc: 'CBSE Curriculum Secondary (Code 184) & NCF-SE 2023',
    syllabusYear: '2024–25 (Exam Cycle 2025)',
    terminologyConventions: ['Subject-Verb Concord', 'Determiners', 'Modals', 'Reported Speech', 'Tenses in Context'],
    pedagogicalCore: 'Communicative grammar: gap-filling, dialogic reporting, and error editing paragraphs within Section B (10 marks).',
    assessmentStructure: 'Section B Grammar: 10 marks total (12 questions with choice of 10, 1 mark each).',
    verificationStatus: 'NEEDS_ACADEMIC_REVIEW',
    verificationEvidenceCount: 7,
    unverifiedModelWarning: 'Note: Class 9–10 syllabus code 184 is verified, but Class 6–8 middle school grammar scopes remain an unverified editorial model pending formal CBSE circulars.',
  },
  CISCE: {
    systemId: 'CISCE',
    systemName: 'Council for the Indian School Certificate Examinations',
    governingBody: 'Council for the Indian School Certificate Examinations, New Delhi',
    primaryFrameworkDoc: 'CISCE Regulations & Syllabuses 2025/2026 (Paper 1)',
    syllabusYear: '2024–25 (ICSE Exam 2025)',
    terminologyConventions: ['Subject-Verb Agreement', 'Prepositions & Phrasal Verbs', 'Transformation of Sentences', 'Synthesis of Sentences'],
    pedagogicalCore: 'Classical grammatical precision: rigorous sentence transformation without altering meaning, prepositional nuance, and exact verb inflection.',
    assessmentStructure: 'English Language Paper 1 Question 5 (20 marks): Q5(a) verb forms (4m), Q5(b) prepositions (4m), Q5(c) joining (4m), Q5(d) transformation (8m). Junior classes use preparatory continuum.',
    verificationStatus: 'NEEDS_ACADEMIC_REVIEW',
    verificationEvidenceCount: 8,
    unverifiedModelWarning: 'Note: ICSE Class 10 Paper 1 Question 5 is verified from 2025 regulations; Junior Class 3–8 specific mark breakdowns are unverified editorial models.',
  },
  Cambridge: {
    systemId: 'Cambridge',
    systemName: 'Cambridge Assessment International Education (CAIE)',
    governingBody: 'Cambridge University Press & Assessment, University of Cambridge',
    primaryFrameworkDoc: 'Cambridge Lower Secondary (0861) & IGCSE (0500)',
    syllabusYear: '2024–2026 Continuous Framework',
    terminologyConventions: ['Stage (not Class)', 'Expanded Noun Phrases', 'Passive for Objectivity', 'Modal Hedging', 'Cohesive Devices'],
    pedagogicalCore: 'Enquiry-led linguistic analysis: exploring grammatical choices for stylistic effect, audience modulation, and rhetorical stance.',
    assessmentStructure: 'Embedded in Reading Analysis and Directed/Continuous Writing Assessment Criteria (e.g. Band 1: Wide range of sophisticated sentence structures).',
    verificationStatus: 'NEEDS_ACADEMIC_REVIEW',
    verificationEvidenceCount: 6,
    unverifiedModelWarning: 'Note: Cambridge frameworks assess grammar holistically through writing rubrics; isolated mark allocations are unverified editorial interpretations.',
  },
};

// ============================================================================
// 4. DEMONSTRATION RECORD: SUBJECT-VERB CONCORD (GOLD STANDARD THREE-LAYER)
// ============================================================================

// Claim-level evidence records demonstrating mixed verification statuses
export const DEMO_CONCORD_CLAIM_EVIDENCE: Record<
  CurriculumSystemId,
  Record<CurriculumClaimType, ClaimEvidenceRecord>
> = {
  CBSE: {
    canonicalTerminology: {
      claimType: 'canonicalTerminology',
      claimLabel: 'Canonical Board Terminology',
      claimValue: 'Subject–Verb Concord',
      status: 'VERIFIED',
      sourceOrganisation: 'Central Board of Secondary Education, Delhi',
      sourceTitle: 'CBSE Secondary School Curriculum 2024–25: English Language and Literature (Code No. 184)',
      sourceType: 'official_syllabus',
      publicationOrSyllabusYear: '2024–2025',
      applicableProgramme: 'Secondary English Language & Literature (Code 184)',
      applicableClassOrStage: 'Class 9 & Class 10',
      pageSectionOrObjective: 'Section B (Grammar), Page 7, Item 4',
      sourceReferenceOrLocation: 'https://cbseacademic.nic.in/curriculum_2025.html',
      dateChecked: '2024-05-10',
      checkedByOrReviewer: 'Dr. Ananya Sen, CBSE Curriculum Advisor',
      notes: 'CBSE Code 184 explicitly terms this topic "Subject-Verb Concord" (not Agreement). Verified against official PDF syllabus.',
      history: [
        {
          timestamp: '2024-05-10T14:30:00Z',
          action: 'VERIFIED',
          performedBy: 'Dr. Ananya Sen',
          previousStatus: 'SOURCE_ADDED_NOT_VERIFIED',
          newStatus: 'VERIFIED',
          notes: 'Matched verbatim heading in CBSE 2024-25 Curriculum document page 7.',
        },
      ],
    },
    pedagogicalEmphasis: {
      claimType: 'pedagogicalEmphasis',
      claimLabel: 'Pedagogical Emphasis',
      claimValue: 'Functional accuracy in communicative sentences and contextual discourse. Formal rules taught through usage rather than parsing.',
      status: 'EDITORIAL_INTERPRETATION',
      sourceOrganisation: 'National Council of Educational Research and Training (NCERT)',
      sourceTitle: 'Learning Outcomes at the Secondary Stage (English)',
      sourceType: 'curriculum_framework',
      publicationOrSyllabusYear: '2023–2024',
      applicableProgramme: 'CBSE Middle & Secondary Phase',
      applicableClassOrStage: 'Classes 6–10',
      pageSectionOrObjective: 'Learning Outcome E6.3 & E8.5',
      sourceReferenceOrLocation: 'NCERT Guidelines for English Language Instruction',
      dateChecked: '2024-06-12',
      checkedByOrReviewer: 'Editorial Working Group',
      notes: 'Classified as EDITORIAL INTERPRETATION. While NCERT emphasises communicative usage, this exact pedagogical synthesis is formulated by VERITAS editors and is not a verbatim board regulation.',
      history: [
        {
          timestamp: '2024-06-12T10:00:00Z',
          action: 'MARKED_EDITORIAL',
          performedBy: 'Editorial Lead',
          previousStatus: 'UNVERIFIED_EDITORIAL_MODEL',
          newStatus: 'EDITORIAL_INTERPRETATION',
          notes: 'Derived from NCERT communicative learning outcomes; marked as editorial synthesis.',
        },
      ],
    },
    expectedDepth: {
      claimType: 'expectedDepth',
      claimLabel: 'Expected Depth & Scope',
      claimValue: 'Focus on collective nouns, correlative conjunctions (neither...nor, either...or), indefinite pronouns, and intervening prepositional phrases.',
      status: 'SOURCE_ADDED_NOT_VERIFIED',
      sourceOrganisation: 'Central Board of Secondary Education, Delhi',
      sourceTitle: 'CBSE Curriculum Framework & NCERT Honeycomb/Honeysuckle Teacher Handbooks',
      sourceType: 'textbook_guideline',
      publicationOrSyllabusYear: '2024',
      applicableProgramme: 'Middle School English (Classes 6–8)',
      applicableClassOrStage: 'Class 6 Core',
      pageSectionOrObjective: 'Grammar Syllabus Annexure 3',
      sourceReferenceOrLocation: 'CBSE Middle School English Handbooks',
      dateChecked: '2024-07-02',
      checkedByOrReviewer: 'Pending Senior Subject Specialist Sign-off',
      notes: 'Source cited but specific list of sub-rules has not been formally verified against official CBSE Class 6 circulars (which are largely school-based).',
      history: [
        {
          timestamp: '2024-07-02T16:00:00Z',
          action: 'SOURCE_ADDED',
          performedBy: 'Editorial Assistant',
          previousStatus: 'UNVERIFIED_EDITORIAL_MODEL',
          newStatus: 'SOURCE_ADDED_NOT_VERIFIED',
          notes: 'Handbook reference identified; awaiting subject specialist review.',
        },
      ],
    },
    boardExamWeightage: {
      claimType: 'boardExamWeightage',
      claimLabel: 'Board Exam Weightage & Slot',
      claimValue: '2–3 marks (Mandatory slot in Class 10 Section B Grammar: 10 marks total)',
      status: 'NEEDS_ACADEMIC_REVIEW',
      sourceOrganisation: 'CBSE Examination Department',
      sourceTitle: 'CBSE Class X English Language and Literature Sample Question Paper 2024–25',
      sourceType: 'sample_question_paper',
      publicationOrSyllabusYear: '2024–2025',
      applicableProgramme: 'Class 10 Board Exam (Code 184)',
      applicableClassOrStage: 'Class 10',
      pageSectionOrObjective: 'Section B (Grammar), Questions 3(i)–3(xii)',
      sourceReferenceOrLocation: 'CBSE Sample Question Paper 2024-25 Q3',
      dateChecked: '2024-05-15',
      checkedByOrReviewer: 'Audit Team Flag',
      notes: 'CRITICAL INTEGRITY FLAG: While Concord frequently appears for 1–2 items in Q3, the CBSE syllabus does NOT fix an isolated "mandatory 2-3 marks slot" by regulation. Questions test a mix of 10 items out of 12 across 5 grammar topics. Requires academic review to avoid misleading textbook claims.',
      history: [
        {
          timestamp: '2024-05-15T11:20:00Z',
          action: 'REVIEW_REQUESTED',
          performedBy: 'Compliance Auditor',
          previousStatus: 'VERIFIED',
          newStatus: 'NEEDS_ACADEMIC_REVIEW',
          notes: 'Downgraded from VERIFIED: CBSE syllabus does not mandate fixed mark allocation per topic.',
        },
      ],
    },
    testingPattern: {
      claimType: 'testingPattern',
      claimLabel: 'Assessment Paradigm',
      claimValue: 'Integrated cloze gap-filling dialogues and error-correction within short paragraphs. No isolated definition or parsing questions.',
      status: 'UNVERIFIED_EDITORIAL_MODEL',
      sourceOrganisation: 'CBSE & NCERT',
      sourceTitle: 'Classroom Assessment Matrix Guidelines',
      sourceType: 'editorial_analysis',
      publicationOrSyllabusYear: '2024',
      applicableProgramme: 'General Secondary Grammar',
      applicableClassOrStage: 'Classes 6–8',
      pageSectionOrObjective: 'Continuous Assessment Protocol',
      sourceReferenceOrLocation: 'School Assessment Circular 2023',
      dateChecked: '2024-03-20',
      checkedByOrReviewer: 'Editorial Team',
      notes: 'UNVERIFIED EDITORIAL MODEL: Reflects common publishing practice for Class 6 internal assessments. Not a mandated CBSE board testing template for middle schools.',
      history: [
        {
          timestamp: '2024-03-20T09:15:00Z',
          action: 'MARKED_EDITORIAL',
          performedBy: 'Publishing Editor',
          previousStatus: 'UNVERIFIED_EDITORIAL_MODEL',
          newStatus: 'UNVERIFIED_EDITORIAL_MODEL',
          notes: 'Standardized classroom exercise format; not an official board prescription.',
        },
      ],
    },
    introductoryLevel: {
      claimType: 'introductoryLevel',
      claimLabel: 'Introduced Grade Level',
      claimValue: 'Introduced formally in Class 5/6',
      status: 'EDITORIAL_INTERPRETATION',
      sourceOrganisation: 'NCERT',
      sourceTitle: 'Primary English Learning Continuum',
      sourceType: 'curriculum_framework',
      publicationOrSyllabusYear: '2023',
      applicableProgramme: 'Middle Stage',
      applicableClassOrStage: 'Class 6',
      dateChecked: '2024-06-01',
      checkedByOrReviewer: 'Editorial Working Group',
      notes: 'Subject-verb agreement is informally used in Class 3-4 oral tasks; formal syntactic rules are traditionally introduced in Class 6.',
    },
    frameworkApplicability: {
      claimType: 'frameworkApplicability',
      claimLabel: 'National Framework Alignment',
      claimValue: 'NCF-SE 2023 Middle Stage Grammar Competencies C-2.1',
      status: 'SOURCE_ADDED_NOT_VERIFIED',
      sourceOrganisation: 'Ministry of Education / NCERT',
      sourceTitle: 'National Curriculum Framework for School Education 2023',
      sourceType: 'curriculum_framework',
      publicationOrSyllabusYear: '2023',
      applicableProgramme: 'National Curriculum Framework',
      applicableClassOrStage: 'Middle Stage (Classes 6–8)',
      pageSectionOrObjective: 'Section 4.2 Language Education, Competency C-2.1',
      dateChecked: '2024-07-01',
      checkedByOrReviewer: 'Curriculum Team',
      notes: 'Cited from NCF-SE document; awaiting formal textbook alignment certification from CBSE.',
    },
  },
  CISCE: {
    canonicalTerminology: {
      claimType: 'canonicalTerminology',
      claimLabel: 'Canonical Board Terminology',
      claimValue: 'Subject–Verb Agreement',
      status: 'VERIFIED',
      sourceOrganisation: 'Council for the Indian School Certificate Examinations, New Delhi',
      sourceTitle: 'ICSE Regulations and Syllabuses for 2025 Examination: English (Paper 1)',
      sourceType: 'official_syllabus',
      publicationOrSyllabusYear: '2024–2025',
      applicableProgramme: 'ICSE Examination (Class 10)',
      applicableClassOrStage: 'Class 9 & 10',
      pageSectionOrObjective: 'Paper 1 (Language), Section 5',
      sourceReferenceOrLocation: 'https://cisce.org/regulations-and-syllabuses-2025/',
      dateChecked: '2024-04-15',
      checkedByOrReviewer: 'Prof. Margaret Davies, CISCE Senior Consultant',
      notes: 'CISCE uses the classical terminology "Subject-Verb Agreement" in its syllabus guides and past examination papers.',
      history: [
        {
          timestamp: '2024-04-15T12:00:00Z',
          action: 'VERIFIED',
          performedBy: 'Prof. Margaret Davies',
          previousStatus: 'SOURCE_ADDED_NOT_VERIFIED',
          newStatus: 'VERIFIED',
          notes: 'Checked against ICSE 2025 Regulations PDF.',
        },
      ],
    },
    pedagogicalEmphasis: {
      claimType: 'pedagogicalEmphasis',
      claimLabel: 'Pedagogical Emphasis',
      claimValue: 'Classical structural syntax, rule exceptions (plural nouns with singular verbs, collective nouns), and syntactic precision.',
      status: 'EDITORIAL_INTERPRETATION',
      sourceOrganisation: 'CISCE Publications',
      sourceTitle: 'Analysis of Pupil Performance: ICSE English Language',
      sourceType: 'editorial_analysis',
      publicationOrSyllabusYear: '2023',
      applicableProgramme: 'ICSE English Language',
      applicableClassOrStage: 'Class 10',
      pageSectionOrObjective: 'Chief Examiner Comments on Question 5',
      sourceReferenceOrLocation: 'CISCE Pupil Performance Analysis 2023, pp. 24–28',
      dateChecked: '2024-05-18',
      checkedByOrReviewer: 'Senior Language Editor',
      notes: 'EDITORIAL INTERPRETATION: Synthesized from Chief Examiner reports on recurring learner errors in Q5. Not an official syllabus mandate.',
      history: [
        {
          timestamp: '2024-05-18T15:30:00Z',
          action: 'MARKED_EDITORIAL',
          performedBy: 'Senior Language Editor',
          previousStatus: 'SOURCE_ADDED_NOT_VERIFIED',
          newStatus: 'EDITORIAL_INTERPRETATION',
          notes: 'Chief Examiner comments digested into pedagogical focus statement.',
        },
      ],
    },
    expectedDepth: {
      claimType: 'expectedDepth',
      claimLabel: 'Expected Depth & Scope',
      claimValue: 'Mastery of tricky subjects: "neither...nor", "as well as", "together with", mathematical quantities, and titles of works.',
      status: 'SOURCE_ADDED_NOT_VERIFIED',
      sourceOrganisation: 'CISCE',
      sourceTitle: 'Curriculum for Preschool to Class VIII: English Language',
      sourceType: 'curriculum_framework',
      publicationOrSyllabusYear: '2022',
      applicableProgramme: 'Middle School (Classes 6–8)',
      applicableClassOrStage: 'Class 6 & 7',
      pageSectionOrObjective: 'Theme: Grammar & Usage, Class 6 Matrix',
      sourceReferenceOrLocation: 'CISCE Preschool to Class VIII Document',
      dateChecked: '2024-06-25',
      checkedByOrReviewer: 'Editorial Assistant',
      notes: 'SOURCE ADDED — NOT VERIFIED: Document contains general agreement goals, but specific breakdown for Class 6 requires verification against actual ICSE affiliated school syllabi.',
      history: [
        {
          timestamp: '2024-06-25T11:00:00Z',
          action: 'SOURCE_ADDED',
          performedBy: 'Editorial Assistant',
          previousStatus: 'UNVERIFIED_EDITORIAL_MODEL',
          newStatus: 'SOURCE_ADDED_NOT_VERIFIED',
          notes: 'Preschool–VIII document located; needs academic reviewer check.',
        },
      ],
    },
    boardExamWeightage: {
      claimType: 'boardExamWeightage',
      claimLabel: 'Board Exam Weightage & Slot',
      claimValue: 'Part of Question 5(a) verb forms (4 marks) and 5(d) transformation (8 marks)',
      status: 'NEEDS_ACADEMIC_REVIEW',
      sourceOrganisation: 'CISCE',
      sourceTitle: 'ICSE Specimen Question Paper 2025: English Language (Paper 1)',
      sourceType: 'sample_question_paper',
      publicationOrSyllabusYear: '2024–2025',
      applicableProgramme: 'ICSE Class 10 Examination',
      applicableClassOrStage: 'Class 10',
      pageSectionOrObjective: 'Question 5(a) & 5(d)',
      sourceReferenceOrLocation: 'ICSE Specimen Paper 2025',
      dateChecked: '2024-05-12',
      checkedByOrReviewer: 'Audit Team Flag',
      notes: 'NEEDS ACADEMIC REVIEW: While Q5 tests verb forms and transformation, Concord is not guaranteed a specific mark quota on every year paper. Stating it as a guaranteed 4 or 8 mark slot requires revision to prevent misinforming textbook buyers.',
      history: [
        {
          timestamp: '2024-05-12T14:00:00Z',
          action: 'REVIEW_REQUESTED',
          performedBy: 'Compliance Auditor',
          previousStatus: 'VERIFIED',
          newStatus: 'NEEDS_ACADEMIC_REVIEW',
          notes: 'Flagged: Exam pattern does not allocate dedicated standalone marks solely to Concord.',
        },
      ],
    },
    testingPattern: {
      claimType: 'testingPattern',
      claimLabel: 'Assessment Paradigm',
      claimValue: 'Passage verb-form inflection without options, followed by structural sentence rewrites requiring subject re-matching.',
      status: 'SOURCE_ADDED_NOT_VERIFIED',
      sourceOrganisation: 'CISCE',
      sourceTitle: 'ICSE Regulations & Specimen Papers 2024-25',
      sourceType: 'sample_question_paper',
      publicationOrSyllabusYear: '2024',
      applicableProgramme: 'ICSE Paper 1',
      applicableClassOrStage: 'Class 10 (and Class 6–8 prep)',
      pageSectionOrObjective: 'Paper 1 Question 5 Format',
      sourceReferenceOrLocation: 'Specimen Paper 2024',
      dateChecked: '2024-06-10',
      checkedByOrReviewer: 'Editorial Working Group',
      notes: 'Source identified in specimen papers; requires confirmation of whether Class 6 textbooks should mimic this formal testing format.',
      history: [
        {
          timestamp: '2024-06-10T17:00:00Z',
          action: 'SOURCE_ADDED',
          performedBy: 'Editorial Assistant',
          previousStatus: 'UNVERIFIED_EDITORIAL_MODEL',
          newStatus: 'SOURCE_ADDED_NOT_VERIFIED',
          notes: 'Format verified in specimen paper; textbook translation pending review.',
        },
      ],
    },
    introductoryLevel: {
      claimType: 'introductoryLevel',
      claimLabel: 'Introduced Grade Level',
      claimValue: 'Introduced systematically in Class 5',
      status: 'EDITORIAL_INTERPRETATION',
      sourceOrganisation: 'CISCE',
      sourceTitle: 'Preschool–VIII Curriculum Document',
      sourceType: 'curriculum_framework',
      publicationOrSyllabusYear: '2022',
      applicableProgramme: 'Elementary Phase',
      applicableClassOrStage: 'Class 5',
      dateChecked: '2024-05-01',
      checkedByOrReviewer: 'CISCE Language Editor',
      notes: 'CISCE curriculum introduces basic subject-predicate agreement in Class 5, with formal exceptions in Class 6.',
    },
    frameworkApplicability: {
      claimType: 'frameworkApplicability',
      claimLabel: 'Framework Policy Discipline',
      claimValue: 'CISCE Independent Examination Byelaws (NEP not universally applicable)',
      status: 'EDITORIAL_INTERPRETATION',
      sourceOrganisation: 'CISCE',
      sourceTitle: 'CISCE Guidelines & Curriculum Policy Statements',
      sourceType: 'curriculum_circular',
      publicationOrSyllabusYear: '2023',
      applicableProgramme: 'CISCE Board Policy',
      applicableClassOrStage: 'All Classes',
      dateChecked: '2024-05-15',
      checkedByOrReviewer: 'Publishing Counsel',
      notes: 'DISCIPLINE NOTICE: CISCE operates under its own autonomous council. NEP 2020 recommendations are adopted selectively by CISCE; they are NOT universally binding on CISCE textbooks.',
    },
  },
  Cambridge: {
    canonicalTerminology: {
      claimType: 'canonicalTerminology',
      claimLabel: 'Canonical Board Terminology',
      claimValue: 'Subject-verb agreement in complex noun phrases',
      status: 'SOURCE_ADDED_NOT_VERIFIED',
      sourceOrganisation: 'Cambridge Assessment International Education',
      sourceTitle: 'Cambridge Lower Secondary English Curriculum Framework (0861)',
      sourceType: 'curriculum_framework',
      publicationOrSyllabusYear: '2023',
      applicableProgramme: 'Cambridge Lower Secondary (0861)',
      applicableClassOrStage: 'Stages 7–9',
      pageSectionOrObjective: 'Stage 7 Learning Objectives 7Rg.02 & 7Wg.04',
      sourceReferenceOrLocation: 'CAIE Lower Secondary Framework Guide',
      dateChecked: '2024-06-01',
      checkedByOrReviewer: 'Alistair Vance, MA Cantab',
      notes: 'SOURCE ADDED — NOT VERIFIED: Cambridge does not maintain an isolated "Subject-Verb Concord" syllabus chapter. Agreement is addressed under grammar and sentence structure objectives (7Rg.02 & 7Wg.04).',
      history: [
        {
          timestamp: '2024-06-01T10:00:00Z',
          action: 'SOURCE_ADDED',
          performedBy: 'Alistair Vance',
          previousStatus: 'UNVERIFIED_EDITORIAL_MODEL',
          newStatus: 'SOURCE_ADDED_NOT_VERIFIED',
          notes: 'Framework objective cited; awaiting second reader sign-off.',
        },
      ],
    },
    pedagogicalEmphasis: {
      claimType: 'pedagogicalEmphasis',
      claimLabel: 'Pedagogical Emphasis',
      claimValue: 'Stylistic clarity and syntactic control across multi-clause sentences; understanding impact on reader comprehension.',
      status: 'EDITORIAL_INTERPRETATION',
      sourceOrganisation: 'Cambridge Assessment International Education',
      sourceTitle: 'Teacher Guide: Cambridge Lower Secondary English (0861)',
      sourceType: 'curriculum_framework',
      publicationOrSyllabusYear: '2023',
      applicableProgramme: 'Cambridge Lower Secondary',
      applicableClassOrStage: 'Stage 7',
      pageSectionOrObjective: 'Section 3: Planning and Pedagogy',
      sourceReferenceOrLocation: 'Cambridge Teacher Guide 0861',
      dateChecked: '2024-06-05',
      checkedByOrReviewer: 'Editorial Working Group',
      notes: 'EDITORIAL INTERPRETATION: Extracted from Cambridge holistic teaching advice. Not a statutory examination rule.',
      history: [
        {
          timestamp: '2024-06-05T12:00:00Z',
          action: 'MARKED_EDITORIAL',
          performedBy: 'Lead Editor',
          previousStatus: 'UNVERIFIED_EDITORIAL_MODEL',
          newStatus: 'EDITORIAL_INTERPRETATION',
          notes: 'Teacher guide principles synthesized into pedagogical profile.',
        },
      ],
    },
    expectedDepth: {
      claimType: 'expectedDepth',
      claimLabel: 'Expected Depth & Scope',
      claimValue: 'Agreement sustained across parenthetical clauses, relative clauses, and compound subjects in formal transactional texts.',
      status: 'EDITORIAL_INTERPRETATION',
      sourceOrganisation: 'Cambridge International',
      sourceTitle: 'Scheme of Work: English Stage 7',
      sourceType: 'textbook_guideline',
      publicationOrSyllabusYear: '2023',
      applicableProgramme: 'Cambridge Lower Secondary',
      applicableClassOrStage: 'Stage 7',
      pageSectionOrObjective: 'Unit 7.2: Grammar for Effect',
      sourceReferenceOrLocation: 'Cambridge Scheme of Work 0861',
      dateChecked: '2024-06-08',
      checkedByOrReviewer: 'Editorial Working Group',
      notes: 'EDITORIAL INTERPRETATION: Suggested scope based on Cambridge Scheme of Work Unit 7.2 recommendations.',
      history: [
        {
          timestamp: '2024-06-08T15:00:00Z',
          action: 'MARKED_EDITORIAL',
          performedBy: 'Editorial Working Group',
          previousStatus: 'UNVERIFIED_EDITORIAL_MODEL',
          newStatus: 'EDITORIAL_INTERPRETATION',
          notes: 'Mapped from Scheme of Work suggestions.',
        },
      ],
    },
    boardExamWeightage: {
      claimType: 'boardExamWeightage',
      claimLabel: 'Board Exam Weightage & Slot',
      claimValue: 'Holistic criterion in writing rubrics (No isolated grammar marks in Cambridge Checkpoint / IGCSE)',
      status: 'UNVERIFIED_EDITORIAL_MODEL',
      sourceOrganisation: 'Cambridge Assessment International Education',
      sourceTitle: 'Cambridge Checkpoint English Specimen Mark Scheme 2024',
      sourceType: 'sample_question_paper',
      publicationOrSyllabusYear: '2024',
      applicableProgramme: 'Cambridge Lower Secondary Checkpoint (0861)',
      applicableClassOrStage: 'Stage 9 / Checkpoint',
      pageSectionOrObjective: 'Paper 2 (Writing) Section B Assessment Grid',
      sourceReferenceOrLocation: 'Mark Scheme 0861/02',
      dateChecked: '2024-06-15',
      checkedByOrReviewer: 'Audit Team',
      notes: 'UNVERIFIED EDITORIAL MODEL: While Cambridge Checkpoint does not test discrete grammar marks, the exact weightage of grammar in writing band descriptors varies across Paper 1 and Paper 2.',
      history: [
        {
          timestamp: '2024-06-15T11:00:00Z',
          action: 'REVIEW_REQUESTED',
          performedBy: 'Compliance Auditor',
          previousStatus: 'UNVERIFIED_EDITORIAL_MODEL',
          newStatus: 'UNVERIFIED_EDITORIAL_MODEL',
          notes: 'Marked as unverified editorial model; rubric weightage needs exact breakdown.',
        },
      ],
    },
    testingPattern: {
      claimType: 'testingPattern',
      claimLabel: 'Assessment Paradigm',
      claimValue: 'Integrated analytical composition, summary writing, and rhetorical evaluation. Assessment through extended writing rubrics.',
      status: 'EDITORIAL_INTERPRETATION',
      sourceOrganisation: 'Cambridge Assessment',
      sourceTitle: 'Cambridge IGCSE First Language English (0500) Syllabus 2024–2026',
      sourceType: 'official_syllabus',
      publicationOrSyllabusYear: '2024',
      applicableProgramme: 'Cambridge Secondary',
      applicableClassOrStage: 'Stages 7–IGCSE',
      pageSectionOrObjective: 'Assessment Overview & Syllabus Objectives',
      sourceReferenceOrLocation: 'CAIE Syllabus 0500',
      dateChecked: '2024-06-20',
      checkedByOrReviewer: 'Senior Academic Editor',
      notes: 'EDITORIAL INTERPRETATION: Synthesis of Cambridge communicative and continuous writing assessment philosophy.',
      history: [
        {
          timestamp: '2024-06-20T16:00:00Z',
          action: 'MARKED_EDITORIAL',
          performedBy: 'Senior Academic Editor',
          previousStatus: 'SOURCE_ADDED_NOT_VERIFIED',
          newStatus: 'EDITORIAL_INTERPRETATION',
          notes: 'Recorded as editorial synthesis.',
        },
      ],
    },
    introductoryLevel: {
      claimType: 'introductoryLevel',
      claimLabel: 'Introduced Stage Level',
      claimValue: 'Stage 4 Primary developing through Stage 7',
      status: 'SOURCE_ADDED_NOT_VERIFIED',
      sourceOrganisation: 'Cambridge Assessment',
      sourceTitle: 'Primary & Lower Secondary Progression Framework',
      sourceType: 'curriculum_framework',
      publicationOrSyllabusYear: '2023',
      applicableProgramme: 'Cambridge Primary/Lower Secondary',
      applicableClassOrStage: 'Stages 4–7',
      dateChecked: '2024-06-01',
      checkedByOrReviewer: 'Alistair Vance',
      notes: 'Introduced in Cambridge Primary Stage 4 under simple sentences, expanded in Stage 7 with clauses.',
    },
    frameworkApplicability: {
      claimType: 'frameworkApplicability',
      claimLabel: 'Framework Policy Discipline',
      claimValue: 'CAIE International Qualifications Framework (NEP not applicable)',
      status: 'VERIFIED',
      sourceOrganisation: 'Cambridge University Press & Assessment',
      sourceTitle: 'Cambridge Global Standards & Recognition Policy',
      sourceType: 'official_syllabus',
      publicationOrSyllabusYear: '2024',
      applicableProgramme: 'International Education Suite',
      applicableClassOrStage: 'Global Stages 1–13',
      pageSectionOrObjective: 'Accreditation Manual 2024',
      dateChecked: '2024-05-10',
      checkedByOrReviewer: 'Cambridge International Advisor',
      notes: 'Cambridge qualifications follow UK/International criteria and are not governed by Indian National Education Policy.',
    },
  },
};

export const DEMO_CONCORD_CBSE_EVIDENCE: CurriculumEvidenceMetadata = {
  sourceTitle: 'CBSE Secondary School Curriculum 2024–25: English Language and Literature (Code No. 184)',
  sourceOrganisation: 'Central Board of Secondary Education, Delhi',
  sourceType: 'official_syllabus',
  sourceYear: '2024',
  referenceUrl: 'https://cbseacademic.nic.in/curriculum_2025.html',
  pageSection: 'Section B (Grammar), Page 7, Item 4',
  applicableProgramme: 'Secondary English Language & Literature (Code 184)',
  applicableLevel: 'Class 10 (and Class 9 preparatory)',
  applicableSyllabusYear: '2024–2025',
  dateChecked: '2024-05-10',
  verificationStatus: 'NEEDS_ACADEMIC_REVIEW',
  academicReviewer: 'Dr. Ananya Sen, CBSE Curriculum Advisor',
  notes: 'Class 9–10 Secondary code 184 terminology is verified. However, Middle School (Class 6–8) mark weightages require academic review because CBSE middle school grammar is school-assessed.',
};

export const DEMO_CONCORD_CISCE_EVIDENCE: CurriculumEvidenceMetadata = {
  sourceTitle: 'ICSE Regulations and Syllabuses for 2025 Examination: English (Paper 1)',
  sourceOrganisation: 'Council for the Indian School Certificate Examinations, New Delhi',
  sourceType: 'official_syllabus',
  sourceYear: '2024',
  referenceUrl: 'https://cisce.org/regulations-and-syllabuses-2025/',
  pageSection: 'Paper 1 (Language), Section 5: Functional Grammar',
  applicableProgramme: 'ICSE Class 10 (compulsory)',
  applicableLevel: 'Class 10',
  applicableSyllabusYear: '2024–2025',
  dateChecked: '2024-04-15',
  verificationStatus: 'NEEDS_ACADEMIC_REVIEW',
  academicReviewer: 'Prof. Margaret Davies, CISCE Senior Consultant',
  notes: 'Class 10 Paper 1 Question 5 structure is verified. Middle school Class 6 breakdown is an unverified editorial model derived from CISCE Preschool–VIII guidelines.',
};

export const DEMO_CONCORD_CAMBRIDGE_EVIDENCE: CurriculumEvidenceMetadata = {
  sourceTitle: 'Cambridge Lower Secondary English Curriculum Framework (0861) Stages 7–9',
  sourceOrganisation: 'Cambridge Assessment International Education, Cambridge, UK',
  sourceType: 'curriculum_framework',
  sourceYear: '2023',
  referenceUrl: 'https://www.cambridgeinternational.org/programmes-and-qualifications/cambridge-lower-secondary/',
  pageSection: 'Stage 7 Learning Objective 7Rg.02 & 7Wg.04',
  applicableProgramme: 'Cambridge Lower Secondary',
  applicableLevel: 'Stage 7 (approx. Age 11–12)',
  applicableSyllabusYear: '2023–2026',
  dateChecked: '2024-06-01',
  verificationStatus: 'NEEDS_ACADEMIC_REVIEW',
  academicReviewer: 'Alistair Vance, MA Cantab',
  notes: 'Stage 7 learning objectives cited. Cambridge does not test isolated grammar marks; assessment weightage is an editorial interpretation of holistic writing band descriptors.',
};

// Layer C: Book / Edition Implementations in VERITAS Books
export const DEMO_CONCORD_BOOK_IMPLEMENTATIONS: ConceptBookImplementation[] = [
  {
    bookProjectId: 'proj-cbse-c6',
    bookTitle: 'Grammar in Action: CBSE Class 6 Edition',
    board: 'CBSE',
    programme: 'CBSE Middle School Core',
    classOrStage: 'Class 6',
    edition: '2024 Academic Edition',
    chapterId: 'cbse-c6-ch07',
    chapterTitle: 'Subject–Verb Concord in Communicative Situations',
    chapterNumber: 7,
    teachingDepth: 'Mastered',
    editionTerminology: 'Subject-Verb Concord',
    sampleExercises: [
      'Ex 7A: Dialogue Gap-Fill with Collective Nouns (jury, committee, team)',
      'Ex 7B: Intervening Prepositional Phrases identification',
      'Ex 7C: Error Correction in News Paragraphs',
    ],
    assessmentTreatment: 'Summative Unit Assessment: 10 contextual MCQs + 5 sentence correction items',
    coverageStatus: 'Covered',
  },
  {
    bookProjectId: 'proj-icse-c6',
    bookTitle: 'Grammar in Action: CISCE Class 6 Edition',
    board: 'CISCE',
    programme: 'CISCE Middle School Classical Suite',
    classOrStage: 'Class 6',
    edition: '2024 Academic Edition',
    chapterId: 'icse-c6-ch08',
    chapterTitle: 'Subject–Verb Agreement & Syntactic Rules',
    chapterNumber: 8,
    teachingDepth: 'Mastered',
    editionTerminology: 'Subject-Verb Agreement',
    sampleExercises: [
      'Ex 8A: Correlative Conjunctions (Either... or / Neither... nor) Proximity Rule',
      'Ex 8B: Classical Rule Drills: Nouns plural in form but singular in sense',
      'Ex 8C: Sentence Rewriting without changing meaning',
    ],
    assessmentTreatment: 'Preparatory ICSE Q5 drill: 8 passage blank completions + 4 sentence rewrites',
    coverageStatus: 'Covered',
  },
  {
    bookProjectId: 'proj-camb-s7',
    bookTitle: 'Grammar in Action: Cambridge Lower Secondary Stage 7',
    board: 'Cambridge',
    programme: 'Cambridge Lower Secondary (0861)',
    classOrStage: 'Stage 7',
    edition: '2024 International Edition',
    chapterId: 'camb-s7-ch06',
    chapterTitle: 'Concord, Complex Noun Phrases & Syntactic Control',
    chapterNumber: 6,
    teachingDepth: 'Developing',
    editionTerminology: 'Subject-verb agreement in complex noun phrases',
    sampleExercises: [
      'Ex 6A: Deconstructing Expanded Subject Noun Phrases in Travel Prose',
      'Ex 6B: Agreement across Relative and Non-finite Subordinate Clauses',
      'Ex 6C: Evaluating stylistic clarity in science journalism articles',
    ],
    assessmentTreatment: 'Writing Rubric Criterion: Accurate grammatical agreement in an 250-word editorial',
    coverageStatus: 'Covered',
  },
];

// System-Specific Spiral Progression Records for Concord
export const DEMO_CONCORD_SYSTEM_PROGRESSIONS = {
  CBSE: {
    'Class 3': {
      stageKey: 'Class 3',
      stageName: 'CBSE Class 3',
      progressionStage: 'I' as ProgressionStage,
      outcome: 'Identify singular/plural naming words with simple matching verbs (is/are, has/have).',
      depthNote: 'Concrete picture-supported drills, oral discovery.',
      curriculumRef: 'CBSE Foundational Learning Outcomes',
    },
    'Class 4': {
      stageKey: 'Class 4',
      stageName: 'CBSE Class 4',
      progressionStage: 'D' as ProgressionStage,
      outcome: 'Subject agreement with compound subjects joined by "and"; simple past was/were.',
      depthNote: 'Regular pronouns and common nouns in sentence pairs.',
      curriculumRef: 'NCERT Grade 4 English',
    },
    'Class 5': {
      stageKey: 'Class 5',
      stageName: 'CBSE Class 5',
      progressionStage: 'R' as ProgressionStage,
      outcome: 'Identify true head noun across basic intervening phrases ("The boy with the balloons is...").',
      depthNote: 'Filtering distracting prepositional modifiers.',
      curriculumRef: 'NCERT Grade 5 English',
    },
    'Class 6': {
      stageKey: 'Class 6',
      stageName: 'CBSE Class 6',
      progressionStage: 'M' as ProgressionStage,
      outcome: 'Full formal concord suite: collective nouns, indefinite quantifiers (each, everyone, either).',
      depthNote: 'Comprehensive chapter instruction; cloze and dialogue blanks.',
      curriculumRef: 'CBSE Class 6 Curriculum Framework',
    },
    'Class 7': {
      stageKey: 'Class 7',
      stageName: 'CBSE Class 7',
      progressionStage: 'M' as ProgressionStage,
      outcome: 'Indefinite quantifiers in complex sentences; agreement with titles, sums of money, time.',
      depthNote: 'Application in error editing passages.',
      curriculumRef: 'CBSE Class 7 English Syllabus',
    },
    'Class 8': {
      stageKey: 'Class 8',
      stageName: 'CBSE Class 8',
      progressionStage: 'R' as ProgressionStage,
      outcome: 'Concord in relative clauses; correlative conjunctions (neither... nor).',
      depthNote: 'Syntax integration and paragraph editing.',
      curriculumRef: 'CBSE Class 8 English Syllabus',
    },
    'Class 9': {
      stageKey: 'Class 9',
      stageName: 'CBSE Class 9',
      progressionStage: 'R' as ProgressionStage,
      outcome: 'Board error editing with concord traps in dense non-fiction articles.',
      depthNote: 'Timed exam drills reflecting CBSE Class 9 Question Paper format.',
      curriculumRef: 'CBSE Class 9 Curriculum Code 184',
    },
    'Class 10': {
      stageKey: 'Class 10',
      stageName: 'CBSE Class 10',
      progressionStage: 'M' as ProgressionStage,
      outcome: 'Zero-tolerance accuracy in board gap-filling and reported dialogues (Section B: 10 marks).',
      depthNote: 'Board exam mandatory slot (2–3 marks).',
      curriculumRef: 'CBSE Class 10 Curriculum Code 184 (Sec B)',
    },
    'Class 11': {
      stageKey: 'Class 11',
      stageName: 'CBSE Class 11',
      progressionStage: 'E' as ProgressionStage,
      outcome: 'Concord in inverted sentences, existential "there", and pseudo-cleft clauses.',
      depthNote: 'Academic and discursive prose registers.',
      curriculumRef: 'CBSE Class 11 English Core Code 301',
    },
    'Class 12': {
      stageKey: 'Class 12',
      stageName: 'CBSE Class 12',
      progressionStage: 'E' as ProgressionStage,
      outcome: 'Syntactic parallelism and notional concord in formal arguments and debates.',
      depthNote: 'Advanced rhetoric and journalistic analysis.',
      curriculumRef: 'CBSE Class 12 English Core Code 301',
    },
  },
  CISCE: {
    'Class 3': {
      stageKey: 'Class 3',
      stageName: 'CISCE Class 3',
      progressionStage: 'I' as ProgressionStage,
      outcome: 'Matching singular and plural subjects with basic present verbs.',
      depthNote: 'Preschool–VIII Curriculum guidelines.',
      curriculumRef: 'CISCE Guidelines Preschool–VIII',
    },
    'Class 4': {
      stageKey: 'Class 4',
      stageName: 'CISCE Class 4',
      progressionStage: 'D' as ProgressionStage,
      outcome: 'Rule of singular/plural subject with auxiliary verbs and irregular plurals.',
      depthNote: 'Classical sentence drills.',
      curriculumRef: 'CISCE Guidelines Preschool–VIII',
    },
    'Class 5': {
      stageKey: 'Class 5',
      stageName: 'CISCE Class 5',
      progressionStage: 'R' as ProgressionStage,
      outcome: 'Agreement with collective nouns acting as single units vs individuals.',
      depthNote: 'Introductory nuances.',
      curriculumRef: 'CISCE Guidelines Preschool–VIII',
    },
    'Class 6': {
      stageKey: 'Class 6',
      stageName: 'CISCE Class 6',
      progressionStage: 'M' as ProgressionStage,
      outcome: 'Mastery of parenthetical remarks ("along with", "as well as"), correlative pairs, indefinite pronouns.',
      depthNote: 'Rigorous sentence construction without multiple choice prompts.',
      curriculumRef: 'CISCE Middle School English Framework',
    },
    'Class 7': {
      stageKey: 'Class 7',
      stageName: 'CISCE Class 7',
      progressionStage: 'M' as ProgressionStage,
      outcome: 'Proximity concord with "either... or / neither... nor", compound plural exceptions.',
      depthNote: 'Classical grammar rules and transformation exercises.',
      curriculumRef: 'CISCE Middle School English Framework',
    },
    'Class 8': {
      stageKey: 'Class 8',
      stageName: 'CISCE Class 8',
      progressionStage: 'R' as ProgressionStage,
      outcome: 'Advanced concord in complex multi-clause sentences; preparatory ICSE syntax drills.',
      depthNote: 'Preparation for ICSE Question 5 grammar formats.',
      curriculumRef: 'CISCE Class 8 English Syllabus',
    },
    'Class 9': {
      stageKey: 'Class 9',
      stageName: 'ICSE Class 9',
      progressionStage: 'R' as ProgressionStage,
      outcome: 'ICSE Paper 1 format: tense inflection passages and sentence synthesis.',
      depthNote: 'Strict accuracy under exam conditions.',
      curriculumRef: 'ICSE Class 9 Regulations & Syllabuses',
    },
    'Class 10': {
      stageKey: 'Class 10',
      stageName: 'ICSE Class 10 (Board Exam)',
      progressionStage: 'M' as ProgressionStage,
      outcome: 'Flawless execution in Paper 1 Question 5(a) passage verb fills and Question 5(d) sentence transformation.',
      depthNote: 'Compulsory 20-mark functional grammar section.',
      curriculumRef: 'ICSE Class 10 Regulations Paper 1 (Q5)',
    },
    'Class 11': {
      stageKey: 'Class 11',
      stageName: 'ISC Class 11',
      progressionStage: 'E' as ProgressionStage,
      outcome: 'Notional concord, inverted clauses ("Seldom does the council..."), legal/formal register syntax.',
      depthNote: 'ISC pre-university rigorous language paper.',
      curriculumRef: 'ISC Class 11 English Paper 1',
    },
    'Class 12': {
      stageKey: 'Class 12',
      stageName: 'ISC Class 12 (Board Exam)',
      progressionStage: 'E' as ProgressionStage,
      outcome: 'Mastery in ISC Paper 1 transformation and precision editing of scholarly essays.',
      depthNote: 'Highest level of British-Indian grammatical rigor.',
      curriculumRef: 'ISC Class 12 English Paper 1',
    },
  },
  Cambridge: {
    'Stage 3': {
      stageKey: 'Stage 3',
      stageName: 'Cambridge Primary Stage 3',
      progressionStage: 'I' as ProgressionStage,
      outcome: 'Explore subject-verb agreement in simple sentences with common regular verbs.',
      depthNote: 'Contextual reading and guided talk.',
      curriculumRef: 'Cambridge Primary 0058 Stage 3',
    },
    'Stage 4': {
      stageKey: 'Stage 4',
      stageName: 'Cambridge Primary Stage 4',
      progressionStage: 'D' as ProgressionStage,
      outcome: 'Maintain agreement in compound sentences connected with co-ordinating conjunctions.',
      depthNote: 'Writing narratives and informational reports.',
      curriculumRef: 'Cambridge Primary 0058 Stage 4',
    },
    'Stage 5': {
      stageKey: 'Stage 5',
      stageName: 'Cambridge Primary Stage 5',
      progressionStage: 'D' as ProgressionStage,
      outcome: 'Recognize agreement with pronouns and collective singular nouns in text analysis.',
      depthNote: 'Editing own work for grammatical consistency.',
      curriculumRef: 'Cambridge Primary 0058 Stage 5',
    },
    'Stage 6': {
      stageKey: 'Stage 6',
      stageName: 'Cambridge Primary Stage 6 (Checkpoint)',
      progressionStage: 'R' as ProgressionStage,
      outcome: 'Sustain agreement throughout multi-paragraph non-fiction texts; agreement with relative clauses.',
      depthNote: 'Primary Checkpoint writing assessment.',
      curriculumRef: 'Cambridge Primary Checkpoint 0058 Stage 6',
    },
    'Stage 7': {
      stageKey: 'Stage 7',
      stageName: 'Cambridge Lower Secondary Stage 7',
      progressionStage: 'M' as ProgressionStage,
      outcome: 'Secure agreement across complex expanded noun phrases with prepositional post-modifiers.',
      depthNote: 'Explicit focus in curriculum framework 0861.',
      curriculumRef: 'Cambridge Lower Secondary 0861 Stage 7',
    },
    'Stage 8': {
      stageKey: 'Stage 8',
      stageName: 'Cambridge Lower Secondary Stage 8',
      progressionStage: 'R' as ProgressionStage,
      outcome: 'Control agreement in complex clauses with non-finite verbs and embedded parenthetical clauses.',
      depthNote: 'Rhetorical clarity in persuasive writing.',
      curriculumRef: 'Cambridge Lower Secondary 0861 Stage 8',
    },
    'Stage 9': {
      stageKey: 'Stage 9',
      stageName: 'Cambridge Lower Secondary Stage 9 (Checkpoint)',
      progressionStage: 'M' as ProgressionStage,
      outcome: 'Total grammatical control in Checkpoint examinations: nuanced noun phrases, indefinite quantifiers.',
      depthNote: 'Lower Secondary Checkpoint examination standard.',
      curriculumRef: 'Cambridge Checkpoint 0861 Stage 9',
    },
    'IGCSE Year 10': {
      stageKey: 'IGCSE Year 10',
      stageName: 'Cambridge IGCSE Year 10',
      progressionStage: 'R' as ProgressionStage,
      outcome: 'Stylistic sentence manipulation, avoiding unintended ambiguity or concord shifts in analysis.',
      depthNote: 'First Language English 0500 coursework/drills.',
      curriculumRef: 'Cambridge IGCSE Syllabus 0500',
    },
    'IGCSE Year 11': {
      stageKey: 'IGCSE Year 11',
      stageName: 'Cambridge IGCSE Year 11 (Exam)',
      progressionStage: 'M' as ProgressionStage,
      outcome: 'Consistent grammatical accuracy in formal non-fiction summary and argumentative discourse.',
      depthNote: 'Assessed under Criterion W3 (Range and Accuracy).',
      curriculumRef: 'Cambridge IGCSE Syllabus 0500 (W3)',
    },
    'AS & A Level': {
      stageKey: 'AS & A Level',
      stageName: 'Cambridge International AS & A Level',
      progressionStage: 'E' as ProgressionStage,
      outcome: 'Linguistic critique of concord variation, dialectal agreement patterns, and rhetorical foregrounding.',
      depthNote: 'Linguistics syllabus (9093).',
      curriculumRef: 'Cambridge AS/A Level 9093',
    },
  },
  VeritasRecommended: {
    'Class 3 / Stage 3': {
      stageKey: 'Class 3 / Stage 3',
      stageName: 'Learning Band 3',
      progressionStage: 'I' as ProgressionStage,
      outcome: 'Core singular vs plural subject identification with regular auxiliary verbs.',
      depthNote: 'Universal linguistic foundation.',
      curriculumRef: 'VERITAS K-12 Master Continuum',
    },
    'Class 4 / Stage 4': {
      stageKey: 'Class 4 / Stage 4',
      stageName: 'Learning Band 4',
      progressionStage: 'D' as ProgressionStage,
      outcome: 'Compound subjects joined by "and"; past tense auxiliary matching.',
      depthNote: 'Syntax building.',
      curriculumRef: 'VERITAS K-12 Master Continuum',
    },
    'Class 5 / Stage 5': {
      stageKey: 'Class 5 / Stage 5',
      stageName: 'Learning Band 5',
      progressionStage: 'R' as ProgressionStage,
      outcome: 'Filtering intervening phrases; introductory collective nouns.',
      depthNote: 'Preserving head noun focus.',
      curriculumRef: 'VERITAS K-12 Master Continuum',
    },
    'Class 6 / Stage 7': {
      stageKey: 'Class 6 / Stage 7',
      stageName: 'Learning Band 6',
      progressionStage: 'M' as ProgressionStage,
      outcome: 'Full formal suite: collective nouns, indefinite quantifiers, parenthetical modifiers.',
      depthNote: 'Major benchmark level across all editions.',
      curriculumRef: 'VERITAS K-12 Master Continuum',
    },
    'Class 7 / Stage 8': {
      stageKey: 'Class 7 / Stage 8',
      stageName: 'Learning Band 7',
      progressionStage: 'M' as ProgressionStage,
      outcome: 'Correlative conjunction proximity rules; agreement in relative clauses.',
      depthNote: 'Syntactic consolidation.',
      curriculumRef: 'VERITAS K-12 Master Continuum',
    },
    'Class 8 / Stage 9': {
      stageKey: 'Class 8 / Stage 9',
      stageName: 'Learning Band 8',
      progressionStage: 'R' as ProgressionStage,
      outcome: 'Advanced concord in multi-clause complex sentences and error editing.',
      depthNote: 'Secondary transition benchmark.',
      curriculumRef: 'VERITAS K-12 Master Continuum',
    },
    'Class 9 / IGCSE Y10': {
      stageKey: 'Class 9 / IGCSE Y10',
      stageName: 'Learning Band 9',
      progressionStage: 'R' as ProgressionStage,
      outcome: 'Board error editing with tricky concord traps in authentic prose excerpts.',
      depthNote: 'Exam simulation and timed exercises.',
      curriculumRef: 'VERITAS K-12 Master Continuum',
    },
    'Class 10 / IGCSE Y11': {
      stageKey: 'Class 10 / IGCSE Y11',
      stageName: 'Learning Band 10',
      progressionStage: 'M' as ProgressionStage,
      outcome: 'Total mastery under board and international exam constraints (zero tolerance for concord slip).',
      depthNote: 'Graduation benchmark for general secondary education.',
      curriculumRef: 'VERITAS K-12 Master Continuum',
    },
    'Class 11 / AS Level': {
      stageKey: 'Class 11 / AS Level',
      stageName: 'Learning Band 11',
      progressionStage: 'E' as ProgressionStage,
      outcome: 'Inversion concord, cleft sentence agreement, and register-specific stylistic choices.',
      depthNote: 'Pre-university extension.',
      curriculumRef: 'VERITAS K-12 Master Continuum',
    },
    'Class 12 / A Level': {
      stageKey: 'Class 12 / A Level',
      stageName: 'Learning Band 12',
      progressionStage: 'E' as ProgressionStage,
      outcome: 'Rhetorical parallelism, notional concord in scholarship prose, and linguistic variation critique.',
      depthNote: 'Advanced scholarly mastery.',
      curriculumRef: 'VERITAS K-12 Master Continuum',
    },
  },
};

// ============================================================================
// 5. CLASSIFIED CURRICULUM DIVERGENCE INSIGHTS
// ============================================================================
export const DEMO_DIVERGENCE_INSIGHTS: CurriculumDivergenceInsight[] = [
  {
    id: 'div-camb-syntax',
    title: 'Cambridge Early Syntax Acceleration',
    description:
      'Cambridge Primary Framework (0058 Stage 4) introduces fronted adverbials and expanded noun phrases with prepositional modifiers as early as ages 8–9, whereas Indian national curricula formalize these structures under clause analysis in Classes 6–8.',
    classification: 'SOURCE_BASED',
    sourceReference: 'CAIE Primary Framework 0058 Stage 4 Learning Objective 4Wg.02 vs. NCERT Learning Outcomes Class 4',
    isAcceptedByAuthor: true,
    acceptedAt: '2024-05-18',
    acceptedBy: 'Editorial Director',
  },
  {
    id: 'div-cisce-transformation',
    title: 'CISCE Transformation Rigor & Non-Communicative Precision',
    description:
      'ICSE Paper 1 Question 5(d) enforces strict sentence transformation without changing meaning, mandating specific structural beginnings ("No sooner...", "Had...", "Unless..."). In contrast, CBSE embeds grammar purely in communicative paragraphs (Section B) and does not test isolated classical transformation.',
    classification: 'SOURCE_BASED',
    sourceReference: 'ICSE Regulations & Syllabuses 2025 Paper 1 vs. CBSE Secondary Curriculum Code 184',
    isAcceptedByAuthor: true,
    acceptedAt: '2024-05-18',
    acceptedBy: 'Editorial Director',
  },
  {
    id: 'div-cbse-communicative',
    title: 'CBSE Applied Communicative Editing Paradigm',
    description:
      'CBSE Section B prioritizes authentic error-editing passages and dialogue completion reflecting everyday conversational registers over prescriptive rule memorization. This requires contextual pedagogical emphasis in VERITAS CBSE editions.',
    classification: 'EDITORIAL_ANALYSIS',
    sourceReference: 'VERITAS Editorial Board Analysis 2024 (Comparative Review Vol. 2)',
    isAcceptedByAuthor: true,
    acceptedAt: '2024-06-01',
    acceptedBy: 'Lead Grammar Architect',
  },
  {
    id: 'div-ai-modal-hedging',
    title: 'Modal Hedging Progression Discrepancy',
    description:
      'Potential divergence detected: Cambridge Stage 8 actively tests epistemic modal verbs ("might", "could", "would") for diplomatic hedging and argument qualification, whereas CISCE and CBSE treat modals primarily for deontic obligation ("must", "should", "ought to") until senior secondary classes.',
    classification: 'AI_SUGGESTED_UNVERIFIED',
    sourceReference: 'AI Studio Automated Syllabus Vector Comparison (Model v3.8)',
    isAcceptedByAuthor: false,
  },
];

// ============================================================================
// 6. FUTURE K, CLASS 1 AND CLASS 2 SUPPORT (EARLY YEARS PEDAGOGICAL MODELS)
// ============================================================================
export const EARLY_YEARS_PEDAGOGICAL_MODELS: EarlyYearsPedagogicalModel[] = [
  {
    level: 'Kindergarten',
    title: 'Foundation Stage: Wonder Words & Guided Discovery',
    ageRange: 'Ages 4–6 (Pre-Primary / Reception / KG)',
    pedagogicalFocus: 'Oral language immersion, phonological awareness, picture-led naming games, and visual story sequence discovery.',
    structureType: 'oral_and_picture_led',
    keyPillars: [
      {
        id: 'oral-lang',
        name: 'Oral Language & Listening',
        description: 'Interactive call-and-response, rhymes, and naming concrete classroom and natural objects.',
        activityStyle: 'Circle-time games, audio prompts, oral repetition.',
      },
      {
        id: 'pic-discovery',
        name: 'Picture-Led Scene Exploration',
        description: 'Large illustrated thematic spreads where children spot actions ("The duck swims", "The rabbit hops").',
        activityStyle: 'Point-and-say exercises, color-coded character sticker activities.',
      },
      {
        id: 'phonological',
        name: 'Sound & Syllable Play',
        description: 'Rhythm clapping and initial sound identification before formal written grammar.',
        activityStyle: 'Clapping games, alliteration songs.',
      },
      {
        id: 'sentence-awareness',
        name: 'Sentence Awareness & Gestures',
        description: 'Recognizing that a sentence tells a complete thought: "Who did what?" using physical gestures.',
        activityStyle: 'Action mimes, visual flashcard pairing.',
      },
    ],
    sampleActivities: [
      'Who Is Doing What? (Picture spread of animal sanctuary)',
      'Action Verb Charades (jump, sleep, laugh, fly)',
      'Naming Word Scavenger Hunt (5 things that are blue)',
    ],
    assessmentStyle: 'Formative teacher observation checklist, sticker milestones — NO written formal exams.',
  },
  {
    level: 'Class 1',
    title: 'Class 1: Language Stepping Stones',
    ageRange: 'Ages 6–7 (Grade 1 / Cambridge Stage 1)',
    pedagogicalFocus: 'Concrete naming words, doing words, singular/plural with picture support, capital letters, and full stops.',
    structureType: 'oral_and_picture_led',
    keyPillars: [
      {
        id: 'naming-words',
        name: 'Naming Words (Nouns in the Real World)',
        description: 'People, places, animals, and things discovered through brightly labeled vignettes.',
        activityStyle: 'Match picture to word, sort into person/place/animal baskets.',
      },
      {
        id: 'action-words',
        name: 'Action Words (Verbs with Animals & People)',
        description: 'Connecting actions to what we do every day: eat, play, read, run.',
        activityStyle: 'Sentence completion with illustrated verb choices.',
      },
      {
        id: 'mechanics-basics',
        name: 'Capital Letters & Full Stop Sentinels',
        description: 'Learning that every sentence starts tall (capital) and stops with a pebble (period).',
        activityStyle: 'Spot the missing sentinel, trace the capital letter.',
      },
      {
        id: 'guided-discovery',
        name: 'Guided Discovery of Number (One and Many)',
        description: 'Adding "-s" and "-es" visually using illustrated counting groups.',
        activityStyle: 'One cat -> Two cats, one box -> three boxes.',
      },
    ],
    sampleActivities: [
      'Build a Sentence Train: [Noun Card] + [Verb Card] + [Period Car]',
      'The Magic Capital Letter Hunt in short 3-line fairy tales',
      'Describing Colors & Sizes (The little green frog)',
    ],
    assessmentStyle: 'Continuous formative mini-tasks, pictorial matching quizzes, and teacher-guided oral checks.',
  },
  {
    level: 'Class 2',
    title: 'Class 2: Building Sentence Foundations',
    ageRange: 'Ages 7–8 (Grade 2 / Cambridge Stage 2)',
    pedagogicalFocus: 'Describing words, personal pronouns (he/she/they), joining words (and, but), questions with question marks, and simple past actions.',
    structureType: 'oral_and_picture_led',
    keyPillars: [
      {
        id: 'pronouns-stepping',
        name: 'Pronoun Replacements',
        description: 'Replacing repeated naming words with "he", "she", "it", and "they" to make sentences flow.',
        activityStyle: 'Sentence makeover game: rescue the tired noun.',
      },
      {
        id: 'describing-words',
        name: 'Describing Words (Sensory Adjectives)',
        description: 'Words that tell how things look, smell, sound, feel, and taste.',
        activityStyle: 'Sensory word webs, mystery touch-box description.',
      },
      {
        id: 'connecting-words',
        name: 'Joining Sentences with "And" & "But"',
        description: 'Combining short choppy thoughts into flowing stories.',
        activityStyle: 'Puzzle piece sentence connectors.',
      },
      {
        id: 'punctuation-expansion',
        name: 'Question Marks & Exclamation Points',
        description: 'Recognizing asking sentences vs telling sentences vs exciting surprise sentences.',
        activityStyle: 'Voice acting sentences according to the ending mark.',
      },
    ],
    sampleActivities: [
      'The Detective Story: What happened yesterday? (Introductory simple past verbs)',
      'Punctuation Traffic Lights: Red for full stop, Yellow for comma, Blue for question mark',
      'Describe Your Favorite Toy (Guided 4-line mini paragraph)',
    ],
    assessmentStyle: 'Integrated workbook exercises, visual self-assessment smiley faces, and classroom showcase presentations.',
  },
];

// ============================================================================
// 7. CURRICULUM COVERAGE MATRIX DATA (10 CONCEPTS x 10 LEARNING BANDS)
// ============================================================================
export interface CurriculumCoverageMatrixRow {
  conceptId: string;
  conceptName: string;
  strand: string;
  bands: Record<string, {
    CBSE: ProgressionStage;
    CISCE: ProgressionStage;
    Cambridge: ProgressionStage;
    VeritasSeries: ProgressionStage;
    flag?: 'CONCEPT_GAP' | 'UNNECESSARY_DUPLICATION' | 'DEPTH_MISMATCH' | 'ASSESSMENT_GAP' | 'MISSING_SOURCE' | 'UNVERIFIED_ALIGNMENT';
    flagNote?: string;
  }>;
}

export const CURRICULUM_COVERAGE_MATRIX_DATA: CurriculumCoverageMatrixRow[] = [
  {
    conceptId: 'concept-concord',
    conceptName: 'Subject–Verb Concord / Agreement',
    strand: 'Syntax & Inflection',
    bands: {
      'band-3': { CBSE: 'I', CISCE: 'I', Cambridge: 'I', VeritasSeries: 'I' },
      'band-4': { CBSE: 'D', CISCE: 'D', Cambridge: 'D', VeritasSeries: 'D' },
      'band-5': { CBSE: 'R', CISCE: 'R', Cambridge: 'D', VeritasSeries: 'R' },
      'band-6': { CBSE: 'M', CISCE: 'M', Cambridge: 'M', VeritasSeries: 'M' },
      'band-7': { CBSE: 'M', CISCE: 'M', Cambridge: 'R', VeritasSeries: 'M' },
      'band-8': { CBSE: 'R', CISCE: 'R', Cambridge: 'M', VeritasSeries: 'R' },
      'band-9': { CBSE: 'R', CISCE: 'R', Cambridge: 'R', VeritasSeries: 'R' },
      'band-10': { CBSE: 'M', CISCE: 'M', Cambridge: 'M', VeritasSeries: 'M' },
      'band-11': { CBSE: 'E', CISCE: 'E', Cambridge: 'E', VeritasSeries: 'E' },
      'band-12': { CBSE: 'E', CISCE: 'E', Cambridge: 'E', VeritasSeries: 'E' },
    },
  },
  {
    conceptId: 'concept-conditionals',
    conceptName: 'Conditional Sentences & Hypotheses',
    strand: 'Complex Syntax & Modality',
    bands: {
      'band-3': { CBSE: 'none', CISCE: 'none', Cambridge: 'none', VeritasSeries: 'none' },
      'band-4': { CBSE: 'none', CISCE: 'none', Cambridge: 'none', VeritasSeries: 'none' },
      'band-5': { CBSE: 'I', CISCE: 'I', Cambridge: 'I', VeritasSeries: 'I' },
      'band-6': { CBSE: 'D', CISCE: 'D', Cambridge: 'D', VeritasSeries: 'D' },
      'band-7': { CBSE: 'R', CISCE: 'R', Cambridge: 'D', VeritasSeries: 'R' },
      'band-8': { CBSE: 'M', CISCE: 'M', Cambridge: 'M', VeritasSeries: 'M' },
      'band-9': { CBSE: 'R', CISCE: 'R', Cambridge: 'R', VeritasSeries: 'R' },
      'band-10': { CBSE: 'M', CISCE: 'M', Cambridge: 'M', VeritasSeries: 'M' },
      'band-11': { CBSE: 'E', CISCE: 'E', Cambridge: 'E', VeritasSeries: 'E' },
      'band-12': { CBSE: 'E', CISCE: 'E', Cambridge: 'E', VeritasSeries: 'E' },
    },
  },
  {
    conceptId: 'concept-voice',
    conceptName: 'Active & Passive Voice Transformation',
    strand: 'Syntax & Pragmatics',
    bands: {
      'band-3': { CBSE: 'none', CISCE: 'none', Cambridge: 'none', VeritasSeries: 'none' },
      'band-4': { CBSE: 'none', CISCE: 'none', Cambridge: 'none', VeritasSeries: 'none' },
      'band-5': { CBSE: 'I', CISCE: 'I', Cambridge: 'I', VeritasSeries: 'I' },
      'band-6': { CBSE: 'D', CISCE: 'D', Cambridge: 'M', VeritasSeries: 'D', flag: 'DEPTH_MISMATCH', flagNote: 'Cambridge Lower Sec Stage 7 introduces passive for depersonalised non-fiction tone earlier than Indian boards.' },
      'band-7': { CBSE: 'R', CISCE: 'R', Cambridge: 'R', VeritasSeries: 'R' },
      'band-8': { CBSE: 'M', CISCE: 'M', Cambridge: 'M', VeritasSeries: 'M' },
      'band-9': { CBSE: 'R', CISCE: 'R', Cambridge: 'R', VeritasSeries: 'R' },
      'band-10': { CBSE: 'M', CISCE: 'M', Cambridge: 'M', VeritasSeries: 'M' },
      'band-11': { CBSE: 'E', CISCE: 'E', Cambridge: 'E', VeritasSeries: 'E' },
      'band-12': { CBSE: 'E', CISCE: 'E', Cambridge: 'E', VeritasSeries: 'E' },
    },
  },
  {
    conceptId: 'concept-reported-speech',
    conceptName: 'Direct & Indirect (Reported) Speech',
    strand: 'Syntax & Pragmatics',
    bands: {
      'band-3': { CBSE: 'none', CISCE: 'none', Cambridge: 'none', VeritasSeries: 'none' },
      'band-4': { CBSE: 'none', CISCE: 'none', Cambridge: 'none', VeritasSeries: 'none' },
      'band-5': { CBSE: 'I', CISCE: 'I', Cambridge: 'I', VeritasSeries: 'I' },
      'band-6': { CBSE: 'D', CISCE: 'D', Cambridge: 'D', VeritasSeries: 'D' },
      'band-7': { CBSE: 'R', CISCE: 'R', Cambridge: 'R', VeritasSeries: 'R' },
      'band-8': { CBSE: 'M', CISCE: 'M', Cambridge: 'M', VeritasSeries: 'M' },
      'band-9': { CBSE: 'R', CISCE: 'R', Cambridge: 'R', VeritasSeries: 'R' },
      'band-10': { CBSE: 'M', CISCE: 'M', Cambridge: 'M', VeritasSeries: 'M' },
      'band-11': { CBSE: 'E', CISCE: 'E', Cambridge: 'E', VeritasSeries: 'E' },
      'band-12': { CBSE: 'E', CISCE: 'E', Cambridge: 'E', VeritasSeries: 'E' },
    },
  },
  {
    conceptId: 'concept-prepositions',
    conceptName: 'Prepositions & Phrasal Verbs',
    strand: 'Lexical Syntax & Collocations',
    bands: {
      'band-3': { CBSE: 'I', CISCE: 'I', Cambridge: 'I', VeritasSeries: 'I' },
      'band-4': { CBSE: 'D', CISCE: 'D', Cambridge: 'D', VeritasSeries: 'D' },
      'band-5': { CBSE: 'R', CISCE: 'R', Cambridge: 'R', VeritasSeries: 'R' },
      'band-6': { CBSE: 'M', CISCE: 'M', Cambridge: 'M', VeritasSeries: 'M' },
      'band-7': { CBSE: 'M', CISCE: 'M', Cambridge: 'M', VeritasSeries: 'M' },
      'band-8': { CBSE: 'R', CISCE: 'R', Cambridge: 'R', VeritasSeries: 'R' },
      'band-9': { CBSE: 'R', CISCE: 'R', Cambridge: 'R', VeritasSeries: 'R' },
      'band-10': { CBSE: 'M', CISCE: 'M', Cambridge: 'M', VeritasSeries: 'M' },
      'band-11': { CBSE: 'E', CISCE: 'E', Cambridge: 'E', VeritasSeries: 'E' },
      'band-12': { CBSE: 'E', CISCE: 'E', Cambridge: 'E', VeritasSeries: 'E' },
    },
  },
  {
    conceptId: 'concept-tenses',
    conceptName: 'Tense, Aspect & Temporal Consistency',
    strand: 'Morphology & Syntax',
    bands: {
      'band-3': { CBSE: 'I', CISCE: 'I', Cambridge: 'I', VeritasSeries: 'I' },
      'band-4': { CBSE: 'D', CISCE: 'D', Cambridge: 'D', VeritasSeries: 'D' },
      'band-5': { CBSE: 'R', CISCE: 'R', Cambridge: 'R', VeritasSeries: 'R' },
      'band-6': { CBSE: 'M', CISCE: 'M', Cambridge: 'M', VeritasSeries: 'M' },
      'band-7': { CBSE: 'M', CISCE: 'M', Cambridge: 'M', VeritasSeries: 'M' },
      'band-8': { CBSE: 'R', CISCE: 'R', Cambridge: 'R', VeritasSeries: 'R' },
      'band-9': { CBSE: 'R', CISCE: 'R', Cambridge: 'R', VeritasSeries: 'R' },
      'band-10': { CBSE: 'M', CISCE: 'M', Cambridge: 'M', VeritasSeries: 'M' },
      'band-11': { CBSE: 'E', CISCE: 'E', Cambridge: 'E', VeritasSeries: 'E' },
      'band-12': { CBSE: 'E', CISCE: 'E', Cambridge: 'E', VeritasSeries: 'E' },
    },
  },
  {
    conceptId: 'concept-modals',
    conceptName: 'Modal Auxiliaries & Epistemic Stance',
    strand: 'Semantics & Pragmatics',
    bands: {
      'band-3': { CBSE: 'none', CISCE: 'none', Cambridge: 'I', VeritasSeries: 'I' },
      'band-4': { CBSE: 'I', CISCE: 'I', Cambridge: 'D', VeritasSeries: 'I' },
      'band-5': { CBSE: 'D', CISCE: 'D', Cambridge: 'R', VeritasSeries: 'D' },
      'band-6': { CBSE: 'R', CISCE: 'R', Cambridge: 'M', VeritasSeries: 'R' },
      'band-7': { CBSE: 'M', CISCE: 'M', Cambridge: 'M', VeritasSeries: 'M' },
      'band-8': { CBSE: 'R', CISCE: 'R', Cambridge: 'R', VeritasSeries: 'R' },
      'band-9': { CBSE: 'R', CISCE: 'R', Cambridge: 'R', VeritasSeries: 'R' },
      'band-10': { CBSE: 'M', CISCE: 'M', Cambridge: 'M', VeritasSeries: 'M' },
      'band-11': { CBSE: 'E', CISCE: 'E', Cambridge: 'E', VeritasSeries: 'E' },
      'band-12': { CBSE: 'E', CISCE: 'E', Cambridge: 'E', VeritasSeries: 'E' },
    },
  },
  {
    conceptId: 'concept-clauses',
    conceptName: 'Clauses, Synthesis & Subordination',
    strand: 'Complex Syntax',
    bands: {
      'band-3': { CBSE: 'none', CISCE: 'none', Cambridge: 'none', VeritasSeries: 'none' },
      'band-4': { CBSE: 'none', CISCE: 'none', Cambridge: 'I', VeritasSeries: 'none' },
      'band-5': { CBSE: 'I', CISCE: 'I', Cambridge: 'D', VeritasSeries: 'I' },
      'band-6': { CBSE: 'D', CISCE: 'D', Cambridge: 'R', VeritasSeries: 'D' },
      'band-7': { CBSE: 'R', CISCE: 'R', Cambridge: 'M', VeritasSeries: 'R' },
      'band-8': { CBSE: 'M', CISCE: 'M', Cambridge: 'M', VeritasSeries: 'M' },
      'band-9': { CBSE: 'R', CISCE: 'R', Cambridge: 'R', VeritasSeries: 'R' },
      'band-10': { CBSE: 'M', CISCE: 'M', Cambridge: 'M', VeritasSeries: 'M' },
      'band-11': { CBSE: 'E', CISCE: 'E', Cambridge: 'E', VeritasSeries: 'E' },
      'band-12': { CBSE: 'E', CISCE: 'E', Cambridge: 'E', VeritasSeries: 'E' },
    },
  },
  {
    conceptId: 'concept-punctuation',
    conceptName: 'Punctuation Nuance & Mechanics',
    strand: 'Orthography & Rhetorical Punctuation',
    bands: {
      'band-3': { CBSE: 'I', CISCE: 'I', Cambridge: 'I', VeritasSeries: 'I' },
      'band-4': { CBSE: 'D', CISCE: 'D', Cambridge: 'D', VeritasSeries: 'D' },
      'band-5': { CBSE: 'R', CISCE: 'R', Cambridge: 'R', VeritasSeries: 'R' },
      'band-6': { CBSE: 'M', CISCE: 'M', Cambridge: 'M', VeritasSeries: 'M' },
      'band-7': { CBSE: 'M', CISCE: 'M', Cambridge: 'M', VeritasSeries: 'M' },
      'band-8': { CBSE: 'M', CISCE: 'M', Cambridge: 'M', VeritasSeries: 'M' },
      'band-9': { CBSE: 'R', CISCE: 'R', Cambridge: 'R', VeritasSeries: 'R' },
      'band-10': { CBSE: 'M', CISCE: 'M', Cambridge: 'M', VeritasSeries: 'M' },
      'band-11': { CBSE: 'E', CISCE: 'E', Cambridge: 'E', VeritasSeries: 'E' },
      'band-12': { CBSE: 'E', CISCE: 'E', Cambridge: 'E', VeritasSeries: 'E' },
    },
  },
  {
    conceptId: 'concept-transformation',
    conceptName: 'Sentence Transformation & Synthesis',
    strand: 'Applied Syntactic Manipulation',
    bands: {
      'band-3': { CBSE: 'none', CISCE: 'none', Cambridge: 'none', VeritasSeries: 'none' },
      'band-4': { CBSE: 'none', CISCE: 'none', Cambridge: 'none', VeritasSeries: 'none' },
      'band-5': { CBSE: 'none', CISCE: 'I', Cambridge: 'none', VeritasSeries: 'none' },
      'band-6': { CBSE: 'I', CISCE: 'D', Cambridge: 'I', VeritasSeries: 'I' },
      'band-7': { CBSE: 'D', CISCE: 'R', Cambridge: 'D', VeritasSeries: 'D' },
      'band-8': { CBSE: 'R', CISCE: 'M', Cambridge: 'R', VeritasSeries: 'R' },
      'band-9': { CBSE: 'R', CISCE: 'R', Cambridge: 'R', VeritasSeries: 'R' },
      'band-10': { CBSE: 'M', CISCE: 'M', Cambridge: 'M', VeritasSeries: 'M' },
      'band-11': { CBSE: 'E', CISCE: 'E', Cambridge: 'E', VeritasSeries: 'E' },
      'band-12': { CBSE: 'E', CISCE: 'E', Cambridge: 'E', VeritasSeries: 'E' },
    },
  },
];

// ============================================================================
// 8. PROFESSIONAL CURRICULUM AUDIT SAFETY METRICS
// ============================================================================
export interface ProfessionalCurriculumAuditMetrics {
  totalRequirementsMapped: number;
  mappingCoveragePercentage: number;
  verifiedAlignmentPercentage: number;
  itemsAwaitingAcademicReview: number;
  itemsWithUnverifiedEditorialModel: number;
  criticalGapsDetected: number;
  complianceClaimNote: string;
}

export const PROFESSIONAL_AUDIT_METRICS: ProfessionalCurriculumAuditMetrics = {
  totalRequirementsMapped: 248,
  mappingCoveragePercentage: 94.8,
  verifiedAlignmentPercentage: 28.5,
  itemsAwaitingAcademicReview: 48,
  itemsWithUnverifiedEditorialModel: 64,
  criticalGapsDetected: 0,
  complianceClaimNote:
    'Academic verification integrity: Strictly 28.5% of mapped curriculum requirements carry verified primary source citations and reviewer sign-offs. 48 claims await academic review and 64 represent unverified editorial models. VERITAS never displays unverified claims as VERIFIED.',
};
