import { Flashcard } from '../types';

export const INITIAL_FLASHCARDS_BENCHMARK: Flashcard[] = [
  // ==========================================
  // DOMAIN 1: IRREGULAR VERBS
  // ==========================================
  {
    id: 'fc-verb-1',
    domain: 'irregular_verbs',
    classLevel: 'Class 7',
    title: 'Lie (Recline) vs. Lay (Place)',
    frontPrompt: 'What are the V1 (Base), V2 (Past Simple), and V3 (Past Participle) forms of "Lie" (to recline or rest)?',
    backAnswer: 'V1: Lie | V2: Lay | V3: Lain\n\n⚠️ Key Distinction: "Lie" is INTRANSITIVE (takes no direct object). "Lay" (to place something down) is TRANSITIVE (Lay / Laid / Laid).',
    clozeSentence: 'Yesterday, feeling exhausted after football practice, Arjun ___ (lie) down on the grass.',
    clozeAnswer: 'lay',
    exampleSentence: 'She had lain awake for two hours before hearing the morning birds.',
    tags: ['verbs', 'irregular', 'tricky-pairs', 'transitivity'],
    difficulty: 'hard',
    box: 1,
    intervalDays: 1,
    easeFactor: 2.3,
    repetitions: 0,
    nextReviewDate: new Date().toISOString(),
    masteryStatus: 'learning',
    history: [],
    irregularVerbDetails: {
      v1: 'lie',
      v2: 'lay',
      v3: 'lain',
      vIng: 'lying',
      v3rd: 'lies',
      phoneticV1: '/laɪ/',
      phoneticV2: '/leɪ/',
      phoneticV3: '/leɪn/',
      confusionWarning: 'Do not confuse with transitive verb: Lay -> Laid -> Laid (e.g., "Lay the book on the table").',
    },
  },
  {
    id: 'fc-verb-2',
    domain: 'irregular_verbs',
    classLevel: 'Class 6',
    title: 'Rise vs. Raise',
    frontPrompt: 'What are the V1, V2, and V3 forms of "Rise" (to move upward independently)?',
    backAnswer: 'V1: Rise | V2: Rose | V3: Risen\n\n⚠️ "Rise" is intransitive (the sun rises). "Raise" is regular and transitive: Raise / Raised / Raised (raise your hand).',
    clozeSentence: 'The sun ___ (rise) majestically behind the misty Himalayan peaks at dawn.',
    clozeAnswer: 'rose',
    exampleSentence: 'Water levels have risen dramatically following three days of relentless monsoon rain.',
    tags: ['verbs', 'irregular', 'transitivity'],
    difficulty: 'medium',
    box: 2,
    intervalDays: 2,
    easeFactor: 2.5,
    repetitions: 1,
    nextReviewDate: new Date().toISOString(),
    masteryStatus: 'learning',
    history: [],
    irregularVerbDetails: {
      v1: 'rise',
      v2: 'rose',
      v3: 'risen',
      vIng: 'rising',
      v3rd: 'rises',
      phoneticV1: '/raɪz/',
      phoneticV2: '/roʊz/',
      phoneticV3: '/ˈrɪz.ən/',
      confusionWarning: '"Rise" is intransitive; "Raise" takes a direct object (Raise your hand).',
    },
  },
  {
    id: 'fc-verb-3',
    domain: 'irregular_verbs',
    classLevel: 'Class 5',
    title: 'Choose / Chose / Chosen',
    frontPrompt: 'What are the past simple (V2) and past participle (V3) of "Choose"?',
    backAnswer: 'V1: Choose | V2: Chose | V3: Chosen\n\n💡 Spelling trap: Single "o" in the past tense (chose), double "o" in base form (choose).',
    clozeSentence: 'From all the candidates, the panel ___ (choose) Sarah as the head prefect yesterday.',
    clozeAnswer: 'chose',
    exampleSentence: 'He has chosen the most arduous path up the mountain.',
    tags: ['verbs', 'irregular', 'spelling-trap'],
    difficulty: 'easy',
    box: 3,
    intervalDays: 4,
    easeFactor: 2.6,
    repetitions: 2,
    nextReviewDate: new Date().toISOString(),
    masteryStatus: 'reviewing',
    history: [],
    irregularVerbDetails: {
      v1: 'choose',
      v2: 'chose',
      v3: 'chosen',
      vIng: 'choosing',
      v3rd: 'chooses',
      phoneticV1: '/tʃuːz/',
      phoneticV2: '/tʃoʊz/',
      phoneticV3: '/ˈtʃoʊ.zən/',
      confusionWarning: 'Notice spelling: choose (present) vs. chose (past).',
    },
  },
  {
    id: 'fc-verb-4',
    domain: 'irregular_verbs',
    classLevel: 'Class 8',
    title: 'Hang (Hung vs. Hanged)',
    frontPrompt: 'What is the past tense of "Hang" when referring to objects vs. execution?',
    backAnswer: 'Objects / Pictures / Clothes:\n👉 Hang -> Hung -> Hung\n\nExecution / Capital Punishment:\n👉 Hang -> Hanged -> Hanged',
    clozeSentence: 'The curator carefully ___ (hang) the antique portrait in the Grand Gallery.',
    clozeAnswer: 'hung',
    exampleSentence: 'Historically, the mutineers were hanged for treason at the naval fortress.',
    tags: ['verbs', 'irregular', 'semantic-split', 'legal-english'],
    difficulty: 'hard',
    box: 1,
    intervalDays: 1,
    easeFactor: 2.4,
    repetitions: 0,
    nextReviewDate: new Date().toISOString(),
    masteryStatus: 'learning',
    history: [],
    irregularVerbDetails: {
      v1: 'hang',
      v2: 'hung / hanged',
      v3: 'hung / hanged',
      confusionWarning: 'Hung is for suspension of objects; Hanged is strictly for execution of persons.',
    },
  },
  {
    id: 'fc-verb-5',
    domain: 'irregular_verbs',
    classLevel: 'Class 5',
    title: 'Bite / Bit / Bitten',
    frontPrompt: 'What are the V1, V2, and V3 forms of "Bite"?',
    backAnswer: 'V1: Bite | V2: Bit | V3: Bitten\n\nNote: The past participle doubles the "t" (bitten).',
    clozeSentence: 'The playful puppy accidentally ___ (bite) my leather sandal.',
    clozeAnswer: 'bit',
    exampleSentence: 'Once bitten, twice shy—she refused to invest in speculative ventures again.',
    tags: ['verbs', 'irregular', 'double-consonant'],
    difficulty: 'easy',
    box: 4,
    intervalDays: 7,
    easeFactor: 2.6,
    repetitions: 3,
    nextReviewDate: new Date().toISOString(),
    masteryStatus: 'reviewing',
    history: [],
    irregularVerbDetails: {
      v1: 'bite',
      v2: 'bit',
      v3: 'bitten',
      phoneticV1: '/baɪt/',
      phoneticV2: '/bɪt/',
      phoneticV3: '/ˈbɪt.ən/',
    },
  },
  {
    id: 'fc-verb-6',
    domain: 'irregular_verbs',
    classLevel: 'Class 6',
    title: 'Freeze / Froze / Frozen',
    frontPrompt: 'Provide the three principal parts of the verb "Freeze".',
    backAnswer: 'V1: Freeze | V2: Froze | V3: Frozen\n\n💡 Follows the weave/wove/woven and steal/stole/stolen ablaut vowel gradation pattern.',
    clozeSentence: 'During the record winter blizzard, the entire lake ___ (freeze) solid.',
    clozeAnswer: 'froze',
    exampleSentence: 'The pipes had frozen overnight due to sub-zero temperatures.',
    tags: ['verbs', 'irregular', 'weather'],
    difficulty: 'easy',
    box: 2,
    intervalDays: 2,
    easeFactor: 2.5,
    repetitions: 1,
    nextReviewDate: new Date().toISOString(),
    masteryStatus: 'learning',
    history: [],
    irregularVerbDetails: {
      v1: 'freeze',
      v2: 'froze',
      v3: 'frozen',
      phoneticV1: '/friːz/',
      phoneticV2: '/froʊz/',
      phoneticV3: '/ˈfroʊ.zən/',
    },
  },
  {
    id: 'fc-verb-7',
    domain: 'irregular_verbs',
    classLevel: 'Class 7',
    title: 'Sink / Sank / Sunk',
    frontPrompt: 'What are the V1, V2, and V3 forms of "Sink"?',
    backAnswer: 'V1: Sink | V2: Sank | V3: Sunk\n\n💡 Note: "Sunken" is an archaic participle retained today primarily as an adjective (e.g. "sunken treasure").',
    clozeSentence: 'The galleon ___ (sink) rapidly after striking the uncharted coral reef.',
    clozeAnswer: 'sank',
    exampleSentence: 'The heavy anchor has sunk deep into the seabed silt.',
    tags: ['verbs', 'irregular', 'i-a-u-pattern'],
    difficulty: 'medium',
    box: 3,
    intervalDays: 4,
    easeFactor: 2.5,
    repetitions: 2,
    nextReviewDate: new Date().toISOString(),
    masteryStatus: 'reviewing',
    history: [],
    irregularVerbDetails: {
      v1: 'sink',
      v2: 'sank',
      v3: 'sunk',
      confusionWarning: '"Sunken" is an adjective; use "sunk" for compound verb tenses (has sunk).',
    },
  },
  {
    id: 'fc-verb-8',
    domain: 'irregular_verbs',
    classLevel: 'Class 6',
    title: 'Shrink / Shrank / Shrunk',
    frontPrompt: 'What are the past simple and past participle of "Shrink"?',
    backAnswer: 'V1: Shrink | V2: Shrank | V3: Shrunk\n\n💡 Follows the i-a-u pattern: Drink/Drank/Drunk, Sing/Sang/Sung, Swim/Swam/Swum.',
    clozeSentence: 'The wool sweater ___ (shrink) two full sizes in the hot laundry dryer.',
    clozeAnswer: 'shrank',
    exampleSentence: 'Her personal savings have shrunk during the prolonged economic slump.',
    tags: ['verbs', 'irregular', 'i-a-u-pattern'],
    difficulty: 'medium',
    box: 2,
    intervalDays: 2,
    easeFactor: 2.4,
    repetitions: 1,
    nextReviewDate: new Date().toISOString(),
    masteryStatus: 'learning',
    history: [],
    irregularVerbDetails: {
      v1: 'shrink',
      v2: 'shrank',
      v3: 'shrunk',
      confusionWarning: '"Shrank" is the V2 past simple; "Shrunk" is the V3 participle.',
    },
  },
  {
    id: 'fc-verb-9',
    domain: 'irregular_verbs',
    classLevel: 'Class 8',
    title: 'Broadcast / Cast (Invariant Verbs)',
    frontPrompt: 'What is the past tense of "Broadcast"? Is "broadcasted" correct?',
    backAnswer: 'Standard English:\nV1: Broadcast | V2: Broadcast | V3: Broadcast\n\n💡 Like its root verb "cast" (cast/cast/cast), "broadcast" traditionally does not take "-ed". While "broadcasted" is colloquially heard, standard academic and textbook style prescribes "broadcast".',
    clozeSentence: 'The BBC ___ (broadcast) the monarch’s historic address across sixty commonwealth nations.',
    clozeAnswer: 'broadcast',
    exampleSentence: 'The emergency alert was broadcast simultaneously to all mobile devices.',
    tags: ['verbs', 'irregular', 'invariant-verbs', 'academic-style'],
    difficulty: 'hard',
    box: 1,
    intervalDays: 1,
    easeFactor: 2.2,
    repetitions: 0,
    nextReviewDate: new Date().toISOString(),
    masteryStatus: 'learning',
    history: [],
    irregularVerbDetails: {
      v1: 'broadcast',
      v2: 'broadcast',
      v3: 'broadcast',
      confusionWarning: 'Avoid "broadcasted" in formal grammar examinations.',
    },
  },
  {
    id: 'fc-verb-10',
    domain: 'irregular_verbs',
    classLevel: 'Class 7',
    title: 'Tear / Tore / Torn',
    frontPrompt: 'What are the three forms of "Tear" (to rip or pull apart)?',
    backAnswer: 'V1: Tear (/tɛər/) | V2: Tore (/tɔːr/) | V3: Torn (/tɔːrn/)\n\n💡 Do not confuse with noun "tear" (/tɪər/, a drop of clear liquid from the eye).',
    clozeSentence: 'During the high-speed chase, the jagged nail ___ (tear) his jacket sleeve.',
    clozeAnswer: 'tore',
    exampleSentence: 'The ancient manuscript was badly torn by centuries of damp storage.',
    tags: ['verbs', 'irregular', 'homographs'],
    difficulty: 'medium',
    box: 3,
    intervalDays: 5,
    easeFactor: 2.5,
    repetitions: 2,
    nextReviewDate: new Date().toISOString(),
    masteryStatus: 'reviewing',
    history: [],
    irregularVerbDetails: {
      v1: 'tear',
      v2: 'tore',
      v3: 'torn',
      phoneticV1: '/tɛər/',
      phoneticV2: '/tɔːr/',
      phoneticV3: '/tɔːrn/',
    },
  },
  {
    id: 'fc-verb-11',
    domain: 'irregular_verbs',
    classLevel: 'Class 9',
    title: 'Tread / Trod / Trodden',
    frontPrompt: 'What are the principal parts of "Tread" (to walk, step, or crush underfoot)?',
    backAnswer: 'V1: Tread | V2: Trod | V3: Trodden (or Trod)\n\nLiterary phrase: "Fools rush in where angels fear to tread."',
    clozeSentence: 'The lone hiker cautiously ___ (tread) upon the thin glacier ice.',
    clozeAnswer: 'trod',
    exampleSentence: 'The path less trodden often yields the greatest discoveries.',
    tags: ['verbs', 'irregular', 'literary'],
    difficulty: 'hard',
    box: 2,
    intervalDays: 2,
    easeFactor: 2.3,
    repetitions: 1,
    nextReviewDate: new Date().toISOString(),
    masteryStatus: 'learning',
    history: [],
    irregularVerbDetails: {
      v1: 'tread',
      v2: 'trod',
      v3: 'trodden',
      phoneticV1: '/trɛd/',
      phoneticV2: '/trɒd/',
      phoneticV3: '/ˈtrɒd.ən/',
    },
  },
  {
    id: 'fc-verb-12',
    domain: 'irregular_verbs',
    classLevel: 'Class 8',
    title: 'Lead / Led / Led',
    frontPrompt: 'What is the past tense of the verb "Lead" (to guide)? Notice spelling!',
    backAnswer: 'V1: Lead (/liːd/) | V2: Led (/lɛd/) | V3: Led (/lɛd/)\n\n⚠️ Common error: Writing "lead" for the past tense. "Lead" pronounced /lɛd/ is the toxic heavy metal (noun), NOT the past tense verb!',
    clozeSentence: 'Commander Evans ___ (lead) the expedition through the uncharted jungle.',
    clozeAnswer: 'led',
    exampleSentence: 'Consistent daily discipline has led to her remarkable academic breakthrough.',
    tags: ['verbs', 'irregular', 'homophones', 'spelling-trap'],
    difficulty: 'medium',
    box: 3,
    intervalDays: 4,
    easeFactor: 2.6,
    repetitions: 2,
    nextReviewDate: new Date().toISOString(),
    masteryStatus: 'reviewing',
    history: [],
    irregularVerbDetails: {
      v1: 'lead',
      v2: 'led',
      v3: 'led',
      phoneticV1: '/liːd/',
      phoneticV2: '/lɛd/',
      phoneticV3: '/lɛd/',
      confusionWarning: 'Never write "He lead the team". The past tense is strictly spelled L-E-D.',
    },
  },

  // ==========================================
  // DOMAIN 2: IDIOMS & FIGURATIVE LANGUAGE
  // ==========================================
  {
    id: 'fc-idiom-1',
    domain: 'idioms',
    classLevel: 'Class 8',
    title: 'Bite the Bullet',
    frontPrompt: 'What does the idiom "Bite the bullet" mean, and what is its historical origin?',
    backAnswer: 'Meaning: To force yourself to endure a painful, grim, or difficult situation with fortitude and resolve.\n\nOrigin: Before modern surgical anesthesia, wounded battlefield soldiers were instructed to bite down on a soft lead musket bullet to cope with excruciating pain during amputation or stitching.',
    clozeSentence: 'Knowing our budget had been slashed, the director decided to ___ and cancel the luxury banquet.',
    clozeAnswer: 'bite the bullet',
    exampleSentence: 'I despise visiting the dentist, but I simply had to bite the bullet and get the wisdom tooth extracted.',
    tags: ['idioms', 'figurative', 'courage', 'etymology'],
    difficulty: 'medium',
    box: 2,
    intervalDays: 3,
    easeFactor: 2.5,
    repetitions: 1,
    nextReviewDate: new Date().toISOString(),
    masteryStatus: 'learning',
    history: [],
    idiomDetails: {
      idiom: 'Bite the bullet',
      figurativeMeaning: 'To face a tough, unpleasant situation with resolute courage and no complaints.',
      literalMeaning: 'Clamping teeth onto a lead bullet during battlefield surgery.',
      originOrEtymology: '19th-century military medical practices prior to ether or chloroform anesthesia.',
      dialogueExample: '"We have to tell the client the launch is delayed by a month." — "Agreed. Let’s bite the bullet and call them right now."',
      register: 'conversational',
      synonymsOrAlternatives: ['Face the music', 'Grit one’s teeth', 'Take the plunge'],
    },
  },
  {
    id: 'fc-idiom-2',
    domain: 'idioms',
    classLevel: 'Class 7',
    title: 'Burn the Midnight Oil',
    frontPrompt: 'What does the idiom "Burn the midnight oil" signify?',
    backAnswer: 'Meaning: To work, study, or read late into the night.\n\nOrigin: Refers to the era prior to electricity, when scholars and workers had to illuminate their desks using oil lamps (burning whale or kerosene oil) after darkness fell.',
    clozeSentence: 'With board exams beginning next Monday, Priya was ___ every evening.',
    clozeAnswer: 'burning the midnight oil',
    exampleSentence: 'The engineering squad burned the midnight oil to patch the critical server vulnerability before dawn.',
    tags: ['idioms', 'study', 'work-ethic'],
    difficulty: 'easy',
    box: 4,
    intervalDays: 7,
    easeFactor: 2.7,
    repetitions: 3,
    nextReviewDate: new Date().toISOString(),
    masteryStatus: 'reviewing',
    history: [],
    idiomDetails: {
      idiom: 'Burn the midnight oil',
      figurativeMeaning: 'To stay awake working or studying late into the night.',
      originOrEtymology: '17th-century usage when oil lamps were the primary source of nocturnal lighting.',
      dialogueExample: '"You look exhausted, Liam." — "I’ve been burning the midnight oil finishing this quarterly report."',
      register: 'conversational',
      synonymsOrAlternatives: ['Pull an all-nighter', 'Work round the clock'],
    },
  },
  {
    id: 'fc-idiom-3',
    domain: 'idioms',
    classLevel: 'Class 9',
    title: 'Steal Someone’s Thunder',
    frontPrompt: 'What does "Steal someone’s thunder" mean, and who originally coined the phrase?',
    backAnswer: 'Meaning: To diminish someone’s achievement by preempting them, using their ideas first, or diverting attention away from them.\n\nOrigin: In 1709, English dramatist John Dennis invented a novel thunder machine (sheet of metal shaken backstage) for his play Appius and Virginia. His play was canceled, but the rival theater company used his thunder apparatus in Macbeth. Dennis angrily cried out: "They will not let my play run, but they steal my thunder!"',
    clozeSentence: 'Maya was about to announce her promotion when Dave abruptly proposed to his fiancée, completely ___ her thunder.',
    clozeAnswer: 'stealing',
    exampleSentence: 'Please do not announce the patent award before Dr. Rao; we must not steal her thunder.',
    tags: ['idioms', 'literary-origin', 'theatrical', 'preemption'],
    difficulty: 'hard',
    box: 1,
    intervalDays: 1,
    easeFactor: 2.3,
    repetitions: 0,
    nextReviewDate: new Date().toISOString(),
    masteryStatus: 'learning',
    history: [],
    idiomDetails: {
      idiom: 'Steal someone’s thunder',
      figurativeMeaning: 'To draw attention away from someone’s achievement or to preempt their news or idea.',
      originOrEtymology: 'Playwright John Dennis’s 1709 protest at London’s Drury Lane Theatre.',
      dialogueExample: '"Don’t post the project completion photo yet—let the interns share it first so we don’t steal their thunder."',
      register: 'conversational',
      synonymsOrAlternatives: ['Upstage someone', 'Take the wind out of their sails'],
    },
  },
  {
    id: 'fc-idiom-4',
    domain: 'idioms',
    classLevel: 'Class 6',
    title: 'A Blessing in Disguise',
    frontPrompt: 'Explain the meaning of "A blessing in disguise" with an example.',
    backAnswer: 'Meaning: An unfortunate or unwelcome event at first that eventually results in a surprisingly good outcome.',
    clozeSentence: 'Missing the delayed morning flight was a ___; it allowed me to avoid the massive traffic jam in Mumbai.',
    clozeAnswer: 'blessing in disguise',
    exampleSentence: 'Losing that corporate job was a blessing in disguise, as it forced him to establish his own successful studio.',
    tags: ['idioms', 'optimism', 'figurative'],
    difficulty: 'easy',
    box: 5,
    intervalDays: 14,
    easeFactor: 2.8,
    repetitions: 4,
    nextReviewDate: new Date().toISOString(),
    masteryStatus: 'mastered',
    history: [],
    idiomDetails: {
      idiom: 'A blessing in disguise',
      figurativeMeaning: 'A good thing that seemed bad or unfortunate initially.',
      dialogueExample: '"I was crushed when they rejected my manuscript." — "Maybe it’s a blessing in disguise; you can now polish the worldbuilding."',
      register: 'conversational',
    },
  },
  {
    id: 'fc-idiom-5',
    domain: 'idioms',
    classLevel: 'Class 8',
    title: 'Take with a Grain of Salt',
    frontPrompt: 'What does it mean to "Take something with a grain of salt" (or a pinch of salt)?',
    backAnswer: 'Meaning: To view a statement, rumor, or claim with healthy skepticism, without accepting it as literal or total truth.\n\nOrigin: From Latin scholar Pliny the Elder’s Naturalis Historia (AD 77), describing an antidote to poison that became effective only when swallowed with a single grain of salt (addito salis grano).',
    clozeSentence: 'Social media rumors about the company merger should be ___ with a grain of salt.',
    clozeAnswer: 'taken',
    exampleSentence: 'Since the tabloids are known for exaggeration, I take everything they write with a grain of salt.',
    tags: ['idioms', 'skepticism', 'classical-origin'],
    difficulty: 'medium',
    box: 3,
    intervalDays: 4,
    easeFactor: 2.5,
    repetitions: 2,
    nextReviewDate: new Date().toISOString(),
    masteryStatus: 'reviewing',
    history: [],
    idiomDetails: {
      idiom: 'Take with a grain of salt',
      figurativeMeaning: 'To regard something with reasonable skepticism and doubt.',
      originOrEtymology: 'Pliny the Elder’s recipe for Mithridates’ universal poison antidote.',
      dialogueExample: '"He claims he scored 100% without studying." — "I’d take that with a heavy grain of salt."',
      register: 'conversational',
    },
  },
  {
    id: 'fc-idiom-6',
    domain: 'idioms',
    classLevel: 'Class 7',
    title: 'Barking Up the Wrong Tree',
    frontPrompt: 'What does "Barking up the wrong tree" mean in everyday communication?',
    backAnswer: 'Meaning: Pursuing a mistaken course of action, following a false clue, or accusing the wrong person.\n\nOrigin: American raccoon hunting with trained hounds; the prey would leap across tree branches while the confused dog remained barking at the base of an empty tree.',
    clozeSentence: 'If you think Inspector Sharma leaked the classified file, you are ___ up the wrong tree.',
    clozeAnswer: 'barking',
    exampleSentence: 'The detectives wasted two precious weeks barking up the wrong tree before uncovering the real accomplice.',
    tags: ['idioms', 'investigation', 'hunting-origin'],
    difficulty: 'easy',
    box: 3,
    intervalDays: 5,
    easeFactor: 2.6,
    repetitions: 2,
    nextReviewDate: new Date().toISOString(),
    masteryStatus: 'reviewing',
    history: [],
    idiomDetails: {
      idiom: 'Barking up the wrong tree',
      figurativeMeaning: 'Pursuing a completely misguided strategy or blaming the wrong source.',
      originOrEtymology: '19th-century American hunting hounds tricked by arboreal raccoons.',
      dialogueExample: '"You’re looking for your misplaced keys in the refrigerator?" — "I guess I’m barking up the wrong tree."',
      register: 'informal',
    },
  },
  {
    id: 'fc-idiom-7',
    domain: 'idioms',
    classLevel: 'Class 10',
    title: 'Elephant in the Room',
    frontPrompt: 'Define the idiom "The elephant in the room" and give a context where it applies.',
    backAnswer: 'Meaning: An enormous, glaring problem or controversial truth that is obvious to everyone in a group, but which everyone deliberately avoids discussing out of embarrassment or discomfort.\n\nFirst recorded: Dostoevsky or Ivan Krylov’s fable "The Inquisitive Man" (1814) visiting a museum seeing all small insects but missing the elephant.',
    clozeSentence: 'No one wanted to address the company’s impending insolvency; it was the obvious ___ in the room.',
    clozeAnswer: 'elephant',
    exampleSentence: 'The unresolved dispute over royalties remained the elephant in the room during the author panel.',
    tags: ['idioms', 'psychology', 'group-dynamics'],
    difficulty: 'medium',
    box: 4,
    intervalDays: 8,
    easeFactor: 2.6,
    repetitions: 3,
    nextReviewDate: new Date().toISOString(),
    masteryStatus: 'reviewing',
    history: [],
    idiomDetails: {
      idiom: 'Elephant in the room',
      figurativeMeaning: 'A prominent controversial issue that everyone knows about but ignores.',
      dialogueExample: '"We talked for an hour about the budget, but nobody mentioned the massive debt." — "Classic elephant in the room."',
      register: 'formal',
    },
  },

  // ==========================================
  // DOMAIN 3: GRAMMAR RULES & TRAPS
  // ==========================================
  {
    id: 'fc-rule-1',
    domain: 'grammar_rules',
    classLevel: 'Class 9',
    title: 'The Dangling Modifier Trap',
    frontPrompt: 'What is a "Dangling Modifier", and how do you correct it?\n\n❌ Example: "Walking into the classroom, the whiteboard was completely clean."',
    backAnswer: 'Rule: An introductory participial phrase must be immediately followed by the grammatical subject that actually performs the action.\n\n❌ Wrong: "Walking into the classroom, the whiteboard was clean." (The whiteboard did not walk!)\n\n✅ Correct: "Walking into the classroom, the teacher noticed that the whiteboard was clean."\n(OR: "When the students entered the classroom, the whiteboard was clean.")',
    clozeSentence: 'Having finished his homework, the television was switched on by Rohan. [Is this correct? Type "yes" or "no"]',
    clozeAnswer: 'no',
    exampleSentence: 'Gazing through the telescope, Galileo observed four moons orbiting Jupiter.',
    tags: ['modifiers', 'participles', 'sentence-structure', 'syntax-traps'],
    difficulty: 'hard',
    box: 1,
    intervalDays: 1,
    easeFactor: 2.2,
    repetitions: 0,
    nextReviewDate: new Date().toISOString(),
    masteryStatus: 'learning',
    history: [],
    grammarRuleDetails: {
      ruleName: 'Dangling & Misplaced Modifiers',
      category: 'Modifiers & Syntax',
      incorrectExample: 'Walking through the botanical gardens, the roses smelled heavenly.',
      correctExample: 'Walking through the botanical gardens, we inhaled the heavenly scent of the roses.',
      explanation: 'A participial modifier at the beginning of a sentence logically modifies the noun immediately following the comma.',
      mnemonic: 'Ask: "WHO is doing the action in the intro phrase?" That doer MUST be the subject right after the comma!',
      examTrapNote: 'Frequent error in Class 9–12 board editing and error-detection sections.',
    },
  },
  {
    id: 'fc-rule-2',
    domain: 'grammar_rules',
    classLevel: 'Class 8',
    title: 'Subject-Verb Agreement: Neither... Nor & Either... Or',
    frontPrompt: 'When compound subjects are joined by "Neither... nor" or "Either... or", how do you determine if the verb is singular or plural?',
    backAnswer: 'Rule of Proximity (Nearer Subject Rule):\nThe verb agrees with the subject closest to it!\n\n1) Neither the teacher nor the STUDENTS [plural] ARE in the hall.\n2) Neither the students nor the TEACHER [singular] IS in the hall.\n\n⚠️ Compare with "as well as" / "along with" where the verb agrees strictly with the FIRST subject.',
    clozeSentence: 'Neither the captain nor the sailors ___ (was/were) able to navigate through the dense fog.',
    clozeAnswer: 'were',
    exampleSentence: 'Either the supervisor or her assistants are required to sign the inspection ledger.',
    tags: ['agreement', 'verbs', 'correlative-conjunctions'],
    difficulty: 'medium',
    box: 2,
    intervalDays: 3,
    easeFactor: 2.5,
    repetitions: 1,
    nextReviewDate: new Date().toISOString(),
    masteryStatus: 'learning',
    history: [],
    grammarRuleDetails: {
      ruleName: 'Correlative Subject-Verb Proximity Rule',
      category: 'Subject-Verb Agreement',
      incorrectExample: 'Neither the principal nor the teachers is attending the symposium.',
      correctExample: 'Neither the principal nor the teachers ARE attending the symposium.',
      explanation: 'With or/nor, look at the noun immediately preceding the verb slot. Match number with that noun.',
      mnemonic: 'Proximity Rule: The closer noun controls the verb!',
    },
  },
  {
    id: 'fc-rule-3',
    domain: 'grammar_rules',
    classLevel: 'Class 10',
    title: 'The Subjunctive Mood (Hypothetical & Counterfactual)',
    frontPrompt: 'When expressing a contrary-to-fact condition, wish, or hypothetical scenario in English, what form of the verb "to be" is required?',
    backAnswer: 'Rule: The Subjunctive uses "WERE" for all persons (I, he, she, it, they).\n\n❌ Colloquial: "If I was you, I would accept the scholarship."\n✅ Standard Subjunctive: "If I WERE you, I would accept the scholarship."\n\nAlso applies to mandative subjunctive: "The committee recommended that the bill BE approved immediately." (base infinitive form).',
    clozeSentence: 'If the old monarch ___ (was/were) still alive today, he would weep at the state of the kingdom.',
    clozeAnswer: 'were',
    exampleSentence: 'She wishes she were able to attend the international robotics championship.',
    tags: ['mood', 'subjunctive', 'conditionals', 'advanced'],
    difficulty: 'hard',
    box: 2,
    intervalDays: 2,
    easeFactor: 2.3,
    repetitions: 1,
    nextReviewDate: new Date().toISOString(),
    masteryStatus: 'learning',
    history: [],
    grammarRuleDetails: {
      ruleName: 'Counterfactual Subjunctive Mood',
      category: 'Verb Moods & Conditionals',
      incorrectExample: 'I wish it was summer again.',
      correctExample: 'I wish it WERE summer again.',
      explanation: 'In counterfactual wishes and impossible conditionals (Type 2 & 3), standard English retains the subjunctive "were".',
      mnemonic: 'In imaginary worlds: "I were, He were, She were, It were!"',
    },
  },
  {
    id: 'fc-rule-4',
    domain: 'grammar_rules',
    classLevel: 'Class 6',
    title: 'Fewer vs. Less (Countable vs. Uncountable)',
    frontPrompt: 'State the rule for choosing between "Fewer" and "Less".\n\nWhich is correct: "less students" or "fewer students"?',
    backAnswer: 'Rule:\n👉 FEWER is used with COUNTABLE plural nouns (things you can count: apples, students, books, errors).\n👉 LESS is used with UNCOUNTABLE / MASS nouns (things measured in degree, volume, or mass: water, sugar, patience, time).\n\n✅ Correct: "Fewer students attended" | "There was less water in the reservoir".',
    clozeSentence: 'Because of automated traffic lights, there are now ___ (fewer/less) accidents on the highway.',
    clozeAnswer: 'fewer',
    exampleSentence: 'With less pollution and fewer vehicles on the road, city air quality improved notably.',
    tags: ['determiners', 'countability', 'usage'],
    difficulty: 'easy',
    box: 4,
    intervalDays: 8,
    easeFactor: 2.7,
    repetitions: 3,
    nextReviewDate: new Date().toISOString(),
    masteryStatus: 'reviewing',
    history: [],
    grammarRuleDetails: {
      ruleName: 'Countable vs. Mass Determiner Distinction',
      category: 'Quantifiers & Determiners',
      incorrectExample: 'You have made less mistakes on this draft.',
      correctExample: 'You have made FEWER mistakes on this draft.',
      explanation: 'Mistakes can be individually counted (1 mistake, 2 mistakes), hence "fewer".',
      mnemonic: 'Can you count 1, 2, 3? Use FEWER! If it is a continuous mass, use LESS!',
    },
  },
  {
    id: 'fc-rule-5',
    domain: 'grammar_rules',
    classLevel: 'Class 8',
    title: 'Who vs. Whom (Subjective vs. Objective Pronoun)',
    frontPrompt: 'How can you quickly test whether to use "Who" or "Whom" in a sentence?',
    backAnswer: 'The He/Him (or She/Her) Substitution Trick:\n\n👉 If the pronoun can be replaced by HE (or They), use WHO (Subject case).\n👉 If the pronoun can be replaced by HIM (or Them), use WHOM (Object case).\n\nExample:\n"___ did you invite?" -> You invited HIM. -> "WHOM did you invite?"\n"___ scored the winning goal?" -> HE scored. -> "WHO scored the winning goal?"\n\nRule of thumb: Notice that "whoM" ends with "M", just like "hiM" and "theM"!',
    clozeSentence: 'The astronomer ___ (who/whom) discovered the comet was awarded the gold medal.',
    clozeAnswer: 'who',
    exampleSentence: 'To whom should this formal memorandum be addressed?',
    tags: ['pronouns', 'case', 'relative-clauses'],
    difficulty: 'medium',
    box: 3,
    intervalDays: 4,
    easeFactor: 2.5,
    repetitions: 2,
    nextReviewDate: new Date().toISOString(),
    masteryStatus: 'reviewing',
    history: [],
    grammarRuleDetails: {
      ruleName: 'Subject vs. Object Case Pronouns',
      category: 'Pronouns & Case',
      incorrectExample: 'Whom wrote the opening chapter of the epic?',
      correctExample: 'WHO wrote the opening chapter of the epic?',
      explanation: '"Who" functions as the grammatical subject performing the verb action; "Whom" functions as a direct object or prepositional object.',
      mnemonic: 'Who = He | WhoM = HiM (both end with M!)',
    },
  },
  {
    id: 'fc-rule-6',
    domain: 'grammar_rules',
    classLevel: 'Class 5',
    title: 'Its vs. It’s (Possessive Pronoun vs. Contraction)',
    frontPrompt: 'Explain the difference between "Its" and "It’s". Why does the possessive pronoun have NO apostrophe?',
    backAnswer: '👉 "It’s" (with apostrophe) = Contraction of "It is" or "It has".\n👉 "Its" (without apostrophe) = Possessive pronoun (belonging to it).\n\n💡 Pedagogical insight: Personal possessive pronouns NEVER take apostrophes (his, hers, ours, yours, theirs, ITS). We only use apostrophes on nouns (the cat\'s tail).',
    clozeSentence: 'The cheetah sprinted across the savanna at ___ (its/it’s) maximum velocity.',
    clozeAnswer: 'its',
    exampleSentence: 'It’s fascinating to watch how the chameleon changes its skin pigmentation.',
    tags: ['punctuation', 'apostrophes', 'pronouns', 'homophones'],
    difficulty: 'easy',
    box: 4,
    intervalDays: 7,
    easeFactor: 2.8,
    repetitions: 3,
    nextReviewDate: new Date().toISOString(),
    masteryStatus: 'reviewing',
    history: [],
    grammarRuleDetails: {
      ruleName: 'Possessive Determiners vs. Contractions',
      category: 'Punctuation & Pronouns',
      incorrectExample: 'The tree shed it’s leaves during November.',
      correctExample: 'The tree shed ITS leaves during November.',
      explanation: 'Replace the word with "it is". If "it is" makes sense, use "it’s". If it does not, use "its".',
      mnemonic: 'Try saying "it is". If it sounds absurd, remove the apostrophe!',
    },
  },
  {
    id: 'fc-rule-7',
    domain: 'grammar_rules',
    classLevel: 'Class 9',
    title: 'Parallel Structure (Parallelism in Series)',
    frontPrompt: 'What is "Parallel Structure", and why is the following sentence flawed?\n\n❌ "She enjoys hiking, to read historical novels, and baking sourdough bread."',
    backAnswer: 'Rule: Items in a coordinated list or series must share identical grammatical form (all gerunds, all infinitives, or all nouns).\n\n❌ Flawed: hiking (gerund), to read (infinitive), and baking (gerund).\n\n✅ Correct (all gerunds):\n"She enjoys hiking, reading historical novels, and baking sourdough bread."\n\n✅ Correct (all infinitives):\n"She likes to hike, to read historical novels, and to bake sourdough bread."',
    clozeSentence: 'The athlete promised to train rigorously, to eat nutritiously, and ___ (to rest / resting) sufficiently.',
    clozeAnswer: 'to rest',
    exampleSentence: 'Effective leaders communicate clearly, listen empathetically, and act decisively.',
    tags: ['parallelism', 'syntax', 'style', 'coordination'],
    difficulty: 'medium',
    box: 3,
    intervalDays: 4,
    easeFactor: 2.5,
    repetitions: 2,
    nextReviewDate: new Date().toISOString(),
    masteryStatus: 'reviewing',
    history: [],
    grammarRuleDetails: {
      ruleName: 'Syntactic Parallelism in Compound Structures',
      category: 'Sentence Architecture & Style',
      incorrectExample: 'The manager inspected the accounts, audited the registers, and reporting the discrepancies.',
      correctExample: 'The manager inspected the accounts, audited the registers, and REPORTED the discrepancies.',
      explanation: 'Coordinated verbs in the same predicate must maintain matching tense, voice, and grammatical mood.',
      mnemonic: 'Balance the scales: match -ing with -ing, past with past, to-infinitive with to-infinitive!',
    },
  },
  {
    id: 'fc-rule-8',
    domain: 'grammar_rules',
    classLevel: 'Class 7',
    title: 'Affect vs. Effect',
    frontPrompt: 'How do you distinguish between "Affect" and "Effect"?\n\nWhich is typically the VERB and which is typically the NOUN?',
    backAnswer: 'The RAVEN Mnemonic:\n\n👉 R-A-V-E-N\n• R = Remember\n• A = Affect is a\n• V = Verb (to influence / alter)\n• E = Effect is a\n• N = Noun (the result / outcome)\n\nExample:\n"The climate shift will AFFECT (verb) agricultural yields."\n"The EFFECT (noun) of the monsoon was devastating."',
    clozeSentence: 'The new regulations had an immediate positive ___ (affect/effect) on river cleanliness.',
    clozeAnswer: 'effect',
    exampleSentence: 'Excessive screen time before bed directly affects sleep quality.',
    tags: ['homophones', 'word-choice', 'verb-vs-noun'],
    difficulty: 'medium',
    box: 3,
    intervalDays: 5,
    easeFactor: 2.6,
    repetitions: 2,
    nextReviewDate: new Date().toISOString(),
    masteryStatus: 'reviewing',
    history: [],
    grammarRuleDetails: {
      ruleName: 'Action Verb vs. Result Noun Distinction',
      category: 'Commonly Confused Words',
      incorrectExample: 'Pollution has a direct affect on cardiovascular health.',
      correctExample: 'Pollution has a direct EFFECT on cardiovascular health.',
      explanation: 'Use Affect when describing the act of influencing. Use Effect when describing the end product or result.',
      mnemonic: 'RAVEN: Remember Affect = Verb, Effect = Noun!',
    },
  },
];
