import { GrammarQuestion, GrammarTestSeries, GrammarExercise } from '../types';

/**
 * Converts questions into standard Moodle GIFT format.
 * GIFT is the de facto text format supported by Moodle LMS, Canvas, and Blackboard
 * for bulk importing quizzes and question banks.
 */
export function exportToMoodleGIFT(title: string, questions: GrammarQuestion[]): string {
  let giftOutput = `// ==========================================\n// Moodle GIFT Quiz Export: ${title}\n// Generated by Grammar Book Series LMS Studio\n// ==========================================\n\n`;

  questions.forEach((q, idx) => {
    const qNum = idx + 1;
    giftOutput += `// Question ${qNum} (${q.type.toUpperCase()}) - ${q.difficulty} - ${q.marks} Mark(s)\n`;
    giftOutput += `::Q${qNum}_${q.type}:: `;

    if (q.type === 'mcq' && q.options && q.options.length > 0) {
      giftOutput += `${q.prompt} {\n`;
      q.options.forEach((opt) => {
        const isCorrect =
          opt.trim().toLowerCase().startsWith(q.correctAnswer.trim().toLowerCase().slice(0, 2)) ||
          opt.trim().toLowerCase() === q.correctAnswer.trim().toLowerCase();
        if (isCorrect) {
          giftOutput += `  =${opt} # Correct! ${q.explanation}\n`;
        } else {
          giftOutput += `  ~${opt} # Incorrect\n`;
        }
      });
      giftOutput += `}\n\n`;
    } else if (q.type === 'fill_in_blanks') {
      const answers = q.acceptableAnswers && q.acceptableAnswers.length > 0
        ? q.acceptableAnswers
        : [q.correctAnswer];
      const answerStr = answers.map((a) => `=${a}`).join(' ');
      const sentence = q.blanksSentence || q.prompt;
      giftOutput += `${sentence.replace(/___+/g, `{${answerStr}}`)}\n\n`;
    } else if (q.type === 'match_column' && q.columnA && q.columnB) {
      giftOutput += `${q.prompt} {\n`;
      q.columnA.forEach((aItem, i) => {
        const bItem = q.columnB?.[i];
        giftOutput += `  =${aItem.text} -> ${bItem ? bItem.text : ''}\n`;
      });
      giftOutput += `}\n\n`;
    } else {
      // Short answer or transformation
      giftOutput += `${q.prompt} {=${q.correctAnswer} # ${q.explanation}}\n\n`;
    }
  });

  return giftOutput;
}

/**
 * Formats a clean printable question paper / worksheet for students and teachers.
 */
export function generatePrintableExamText(
  test: GrammarTestSeries,
  includeAnswerKey: boolean = false
): string {
  let sheet = `${'='.repeat(70)}\n`;
  sheet += `${test.title.toUpperCase()}\n`;
  sheet += `Class: ${test.classLevel} | Time Allowed: ${test.durationMinutes} Minutes | Maximum Marks: ${test.totalMarks}\n`;
  sheet += `Student Name: _______________________   Roll No: _______   Date: __________\n`;
  sheet += `${'='.repeat(70)}\n\n`;

  if (test.instructions && test.instructions.length > 0) {
    sheet += `GENERAL INSTRUCTIONS:\n`;
    test.instructions.forEach((ins, idx) => {
      sheet += `  ${idx + 1}. ${ins}\n`;
    });
    sheet += `\n${'-'.repeat(70)}\n\n`;
  }

  let totalQCount = 1;
  test.sections.forEach((sec) => {
    sheet += `[ ${sec.title.toUpperCase()} ]\n`;
    if (sec.description) sheet += `(${sec.description})\n`;
    sheet += `\n`;

    sec.questions.forEach((q) => {
      sheet += `Q${totalQCount++}. ${q.prompt}  [${q.marks} Mark${q.marks > 1 ? 's' : ''}]\n`;

      if (q.instruction) {
        sheet += `    Instruction: ${q.instruction}\n`;
      }

      if (q.type === 'mcq' && q.options) {
        q.options.forEach((opt) => {
          sheet += `    ${opt}\n`;
        });
      } else if (q.type === 'fill_in_blanks' && q.blanksSentence) {
        sheet += `    ${q.blanksSentence}  ${q.hints ? `(Hint: ${q.hints})` : ''}\n`;
      } else if (q.type === 'match_column' && q.columnA && q.columnB) {
        sheet += `    Column A                               Column B\n`;
        const maxLen = Math.max(q.columnA.length, q.columnB.length);
        for (let i = 0; i < maxLen; i++) {
          const colA = q.columnA[i]?.text || '';
          const colB = q.columnB[i]?.text || '';
          sheet += `    ${colA.padEnd(38)} ${colB}\n`;
        }
      } else if (q.originalSentence) {
        sheet += `    Sentence: "${q.originalSentence}"\n`;
      }

      sheet += `\n`;
    });

    sheet += `${'-'.repeat(70)}\n\n`;
  });

  if (includeAnswerKey) {
    sheet += `\n\n${'#'.repeat(70)}\n`;
    sheet += `TEACHER'S ASSESSMENT KEY & PEDAGOGICAL EXPLANATIONS\n`;
    sheet += `${'#'.repeat(70)}\n\n`;

    let aNum = 1;
    test.sections.forEach((sec) => {
      sheet += `--- ${sec.title} ---\n`;
      sec.questions.forEach((q) => {
        sheet += `Ans ${aNum++}: ${q.correctAnswer}\n`;
        if (q.explanation) {
          sheet += `    Explanation: ${q.explanation}\n`;
        }
        sheet += `\n`;
      });
    });
  }

  return sheet;
}
