import { NovelProject } from '../types';

export const INITIAL_NOVEL: NovelProject = {
  id: 'proj-architect-of-echoes',
  title: 'The Architect of Echoes',
  subtitle: 'A Novel of Memory, Glass, and Vanishing Walls',
  authorName: 'Evelyn Vance',
  genre: 'Literary Speculative Thriller',
  logline: 'When an architectural conservator is commissioned to restore a coastal sanctuary that rebuilds its own floorplan each dusk, he discovers his dead sister’s handwriting etched beneath centuries of lime mortar.',
  synopsis: 'Set on the storm-battered cliffs of Blackwater Cape, The Architect of Echoes explores grief, structural obsession, and the thin boundary between memory and architecture. Julian Mercer believes every building carries an echo of its occupants. But the Highclere Conservatory does not simply remember its past—it rearranges it.',
  targetTotalWords: 80000,
  dailyGoalWords: 1000,
  wordsWrittenToday: 420,
  lastDailyResetDate: new Date().toISOString().split('T')[0],
  createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  updatedAt: new Date().toISOString(),
  isEncrypted: false,
  stylePersona: {
    id: 'persona-1',
    name: 'Grounded Atmospheric Realism',
    description: 'Rhythmic, high-burstiness literary prose with visceral sensory grounding, abrupt clause variations, and zero corporate or AI filler words.',
    tone: 'Haunting, tactile, precise, psychologically alert',
    burstinessLevel: 'High',
    sensoryLevel: 'Dense & Visceral',
    dialogueStyle: 'Crisp & Punchy',
    bannedWords: [
      'rich tapestry',
      'testament to',
      'delve',
      'intertwined',
      'palpable tension',
      'moreover',
      'furthermore',
      'a symphony of',
      'navigating the',
      'little did they know',
    ],
  },
  coverDesign: {
    title: 'The Architect of Echoes',
    subtitle: 'A Novel by Evelyn Vance',
    authorName: 'EVELYN VANCE',
    fontFamily: 'Cinzel',
    titleColor: '#f8fafc',
    accentColor: '#d97706',
    themeLayout: 'Cinematic Drama',
    spineWidth: 28,
  },
  chapters: [
    {
      id: 'chap-1',
      number: 1,
      title: 'Salt and Mortar',
      summary: 'Julian Mercer arrives at the remote Blackwater Cape to inspect the Highclere Conservatory, noticing the impossible geometry of the atrium.',
      targetWordCount: 4500,
      status: 'In Revision',
      scenes: [
        {
          id: 'scene-1-1',
          title: 'Arrival at Blackwater Head',
          povCharacterId: 'char-julian',
          sceneGoal: 'Establish Julian’s sensory obsession with materials and reveal the uncanny behavior of the conservatory.',
          conflict: 'Julian’s calipers and laser-level contradict the physical blueprints by nearly three meters.',
          outcome: 'He finds his sister’s drafting mark on an interior lintel.',
          wordCount: 420,
          status: 'In Revision',
          lastModified: new Date().toISOString(),
          content: `The wind smelled of cold brine and iron rust.

Julian Mercer did not trust buildings that smelled like damp earth before the rain fell. He killed the diesel engine of the Land Cruiser, listening as the manifold clicked in the sea fog, cooling unevenly against the salt mist. 

Ahead of him stood the conservatory. It looked less like an estate than a ribcage left to calcify above the Atlantic breakers.

He grabbed his canvas field-bag from the passenger seat. Heavy. Inside, six brass plumb-bobs, two steel tapes, a mechanical pencil with 0.5-millimeter HB lead, and the frayed linen folder containing Lord Highclere’s telegram: *The north gallery has moved again. Bring your sister’s notes.*

His sister, Clara, had been drowned for seventeen months.

Julian walked up the gravel path, his workboots grinding through shell fragments and crushed shale. A gull wheeled overhead, its throat raw against the gray chop of the tide. At the entrance, the portico arched inward—Doric columns, but carved with strange diagonal fluting that made his balance tilt. He pressed his palm against the cornerstone.

Cold. Limestone should carry the residual warmth of the afternoon sun, even under sea-stratus. This stone drank heat.

"You're thirty minutes early, Mr. Mercer," a voice cut through the fog.

Julian turned. A woman in a waxed Barbour coat stood near the hydrangeas, shears in hand. Dirt streaked her temple. Her gaze was neither welcoming nor apologetic—merely measuring.

"The ferry was empty," Julian said. "The water was flat."

"The water is never flat out here," she said, clipping a withered flowerhead. The snap was louder than it should have been. "It just pretends until you're past the shoals. I'm Martha Highclere. Come inside before the tide locks the causeway gate."`,
        },
        {
          id: 'scene-1-2',
          title: 'The Shifting Gallery',
          povCharacterId: 'char-julian',
          sceneGoal: 'Take baseline measurements inside the northern wing.',
          conflict: 'The walls resonate at a subsonic pitch that induces mild vertigo.',
          outcome: 'A hidden niche is uncovered behind the plaster.',
          wordCount: 285,
          status: 'Draft',
          lastModified: new Date().toISOString(),
          content: `The gallery stretched eighty paces under ribbed glass. Dust danced in the gray beams of light, suspended like flecks of gold leaf in oil.

Julian unlatched the tripod and leveled his laser. 

The red beam stabbed through the gloom, striking the far lintel. The digital readout pulsed, settled, then flickered: *42.84m*. 

He blinked. He tapped the optical casing with his knuckle. He looked back at Clara's yellowed blueprints spread across the cedar sawhorses. Her handwriting was firm, slanted, confident: *North Gallery: 39.50m from threshold to hearth.*

Three meters. A wall of load-bearing Portland stone doesn't drift three meters in ninety years without tearing the floor joists to splinters. Yet the parquetry beneath his boots was flush. No buckling. No cracked varnish. Just the smell of beeswax and the faint, sweet decay of old paper.

He knelt. With his thumb, he brushed away a cobweb clinging to the wainscoting. 

There, stamped into the mortar with a notched architect's scribe, was a cipher he knew better than his own signature: a pair of linked compasses with an open eye.

Clara's maker's mark. 

Dated October 1912.

Julian pulled his hand back as if the plaster had burned him. Clara was born in 1988.`,
        },
      ],
    },
    {
      id: 'chap-2',
      number: 2,
      title: 'The Geometry of Loss',
      summary: 'Julian confronts Martha Highclere about the impossible dates in the archive and begins nocturnal acoustic mapping.',
      targetWordCount: 5000,
      status: 'Draft',
      scenes: [
        {
          id: 'scene-2-1',
          title: 'Tea and False Blueprints',
          povCharacterId: 'char-julian',
          sceneGoal: 'Interrogate Martha Highclere over dinner without revealing his panic.',
          conflict: 'Martha avoids discussing Clara’s final week at the cape.',
          outcome: 'Julian steals the brass skeleton key to the cellar archives.',
          wordCount: 190,
          status: 'Draft',
          lastModified: new Date().toISOString(),
          content: `Dinner was boiled haddock and bitter chicory. 

Martha poured black tea from a silver pot whose spout was shaped like a crane's beak. Across the mahogany table, shadows huddled in the corners of the dining room like stray dogs waiting for scraps.

"Your father built the seawall in thirty-four," Julian said, his voice flat. "Who supervised the mortar mix?"

"My grandfather," Martha replied, spooning sugar that clinked against bone china. "He didn't trust engineers from London. Said they calculated for wind, but neglected the appetite of the Atlantic."

"And Clara?"

The teaspoon froze midway to the saucer. Martha didn't flinch, but her eyelids dropped a fraction of a millimeter. 

"Your sister was gifted, Julian. But she was greedy for things walls were never meant to hold."`,
        },
      ],
    },
  ],
  characters: [
    {
      id: 'char-julian',
      name: 'Dr. Julian Mercer',
      alias: 'The Conservator',
      role: 'Protagonist',
      archetype: 'Obsessive Seeker / Wounded Craftsman',
      age: '37',
      appearance: 'Tall, lean frame with salt-and-pepper stubble, permanent charcoal smudges on his cuffs, calloused fingertips from stone chisels.',
      personality: 'Methodical, deeply observant, guarded, emotionally repressed since his sister’s death, speaks in succinct sentences.',
      internalGoal: 'To uncover what Clara found at Highclere and prove her death was not accidental madness.',
      externalConflict: 'The Highclere estate is scheduled for demolition by an offshore syndicate in twenty-one days.',
      flaw: 'Relies so rigidly on physical measurements that he dismisses instinct until danger is immediate.',
      voiceNotes: 'Speaks with cadence of a field engineer. Short clauses, technical terminology (lintel, plumb-bob, shear stress), pauses to assess before speaking.',
      relationships: ['Clara Mercer (Deceased sister - unresolved guilt)', 'Martha Highclere (Hostile ally)'],
    },
    {
      id: 'char-martha',
      name: 'Martha Highclere',
      alias: 'The Caretaker',
      role: 'Antagonist',
      archetype: 'Guardian of Secrets',
      age: '54',
      appearance: 'Weathered hands, silver hair cut bluntly at the jaw, dark wool coats that smell of peat smoke and dried lavender.',
      personality: 'Sharp, unsentimental, fatalistic, fiercely protective of the conservatory’s hidden mechanism.',
      internalGoal: 'To prevent the conservatory’s inner chamber from collapsing into the sea before the winter solstice.',
      externalConflict: 'Needs Julian’s architectural mastery, but cannot let him decipher the 1912 records.',
      flaw: 'Believes sacrifice of truth is necessary to preserve legacy.',
      voiceNotes: 'Clipped, rhythmic Northern coastal dialect. Never uses two words when half of one suffices. Uses horticultural metaphors.',
      relationships: ['Julian Mercer (Distrusted specialist)', 'Clara Mercer (Former confidante)'],
    },
    {
      id: 'char-clara',
      name: 'Clara Mercer (Posthumous)',
      alias: 'The Architect of Shadows',
      role: 'Deuteragonist',
      archetype: 'Visionary Pioneer',
      age: '32 at disappearance',
      appearance: 'Fiery auburn hair, luminous hazel eyes, ink-stained thumbs, quick nervous laughter in memories.',
      personality: 'Daring, intuitive, mathematically brilliant, impatient with academic orthodoxy.',
      internalGoal: 'To discover the fourth architectural dimension engineered into the estate.',
      externalConflict: 'The house began mapping her own mind into its floorplans.',
      flaw: 'Hubris—believed she could master a structure designed to swallow its observers.',
      voiceNotes: 'Passionate, lyrical, quick-fire deductions, uses musical and geometric terms interchangeably.',
      relationships: ['Julian Mercer (Devoted brother)', 'Lord Highclere (Patron)'],
    },
  ],
  plotBeats: [
    {
      id: 'beat-1',
      act: 'Act I (Beginning)',
      beatType: 'Hook',
      title: 'The Impossible Survey',
      description: 'Julian arrives at Blackwater Cape and discovers Highclere Conservatory expands by three meters every dusk.',
      tensionLevel: 4,
      status: 'Drafted',
      linkedChapterId: 'chap-1',
      notes: 'Focus on visceral salt fog and acoustic resonance.',
    },
    {
      id: 'beat-2',
      act: 'Act I (Beginning)',
      beatType: 'Inciting Incident',
      title: 'Clara’s 1912 Cipher',
      description: 'Julian finds his modern sister’s mason mark stamped in mortar dating from eighty years before her birth.',
      tensionLevel: 6,
      status: 'Drafted',
      linkedChapterId: 'chap-1',
    },
    {
      id: 'beat-3',
      act: 'Act II (Middle)',
      beatType: 'First Plot Point',
      title: 'The Subterranean Cloister',
      description: 'Julian discovers the lower cellar contains mirrors that do not reflect candles, only ocean depth.',
      tensionLevel: 7,
      status: 'Planned',
      linkedChapterId: 'chap-2',
    },
    {
      id: 'beat-4',
      act: 'Act II (Middle)',
      beatType: 'Midpoint',
      title: 'The Midnight Shift',
      description: 'Trapped inside during a nor’easter, Julian watches a solid stone wall dissolve into a corridor of fog.',
      tensionLevel: 9,
      status: 'Planned',
    },
    {
      id: 'beat-5',
      act: 'Act III (Climax & Resolution)',
      beatType: 'Climax',
      title: 'The Master Keystones',
      description: 'Julian must decide whether to dismantle the core keystone to save the cape or let the house reconstruct Clara.',
      tensionLevel: 10,
      status: 'Planned',
    },
  ],
  team: [
    {
      id: 'member-1',
      name: 'Evelyn Vance (You)',
      email: 'clarencedrosario@gmail.com',
      role: 'owner',
      avatar: 'EV',
      online: true,
      lastActive: 'Just now',
    },
    {
      id: 'member-2',
      name: 'David K. Thorne',
      email: 'thorne.editor@literarypress.org',
      role: 'editor',
      avatar: 'DT',
      online: true,
      lastActive: '2m ago',
    },
    {
      id: 'member-3',
      name: 'Dr. Sarah Lin',
      email: 'slin.beta@readcircle.com',
      role: 'beta-reader',
      avatar: 'SL',
      online: false,
      lastActive: '1h ago',
    },
  ],
  comments: [
    {
      id: 'comm-1',
      chapterId: 'chap-1',
      sceneId: 'scene-1-1',
      author: 'David K. Thorne (Editor)',
      authorRole: 'editor',
      timestamp: 'Yesterday at 4:15 PM',
      quoteText: 'Julian Mercer did not trust buildings that smelled like damp earth before the rain fell.',
      comment: 'Superb opening sentence. Immediate sensory anchor and establishes Julian’s sensory instincts.',
      resolved: false,
    },
    {
      id: 'comm-2',
      chapterId: 'chap-1',
      sceneId: 'scene-1-1',
      author: 'Dr. Sarah Lin (Beta Reader)',
      authorRole: 'beta-reader',
      timestamp: 'Today at 9:30 AM',
      quoteText: 'Doric columns, but carved with strange diagonal fluting that made his balance tilt.',
      comment: 'Great touch with diagonal fluting—creates physical vertigo in the reader without over-explaining.',
      resolved: true,
    },
  ],
  auditLogs: [
    {
      id: 'log-1',
      timestamp: new Date(Date.now() - 3600000).toISOString(),
      user: 'Evelyn Vance',
      action: 'SCENE_EDIT',
      details: 'Revised Scene 1.1 "Arrival at Blackwater Head" (+140 words, tightened sensory pacing)',
    },
    {
      id: 'log-2',
      timestamp: new Date(Date.now() - 7200000).toISOString(),
      user: 'David K. Thorne',
      action: 'COMMENT_ADDED',
      details: 'Added editorial comment on Scene 1.1 opening hook',
    },
    {
      id: 'log-3',
      timestamp: new Date(Date.now() - 14400000).toISOString(),
      user: 'System',
      action: 'AUTO_BACKUP',
      details: 'Automated snapshot v4 created (420 words, encrypted AES-256 state verified)',
    },
  ],
  versions: [
    {
      id: 'ver-1',
      versionNumber: 1,
      timestamp: new Date(Date.now() - 3 * 24 * 3600000).toISOString(),
      title: 'Initial Outline & Prologue Concept',
      author: 'Evelyn Vance',
      wordCount: 210,
      summaryNote: 'First rough draft of Blackwater Cape arrival.',
      dataJson: '',
    },
    {
      id: 'ver-2',
      versionNumber: 2,
      timestamp: new Date(Date.now() - 24 * 3600000).toISOString(),
      title: 'Pacing & Cadence Overhaul',
      author: 'Evelyn Vance',
      wordCount: 540,
      summaryNote: 'Broke up long expository paragraphs; added high burstiness dialogue with Martha.',
      dataJson: '',
    },
  ],
  codexEntries: [
    {
      id: 'codex-highclere',
      title: 'Highclere Conservatory',
      category: 'location',
      shortDescription: 'A 19th-century coastal conservatory built on basalt cliffs that mechanically and acoustically shifts dimensions each dusk.',
      detailedLore: 'Erected between 1892 and 1898 by eccentric industrialist Alistair Highclere. Constructed using hydraulic bronze counterweights, sea-salt tempered glass panes, and lime mortar seeded with crushed beryl. At twilight, the changing tide forces air through sub-basement acoustic flutes, triggering stone keystones to expand along non-Euclidean bearing lines.',
      sensoryDetails: 'Scent of brine, wet lime, oxidized brass, and damp geraniums. Echoes carry a 1.2-second acoustic lag that makes human voices double.',
      secrets: 'The conservatory floorplan mirrors a 4-dimensional hypercube designed to capture and replay psychological trauma stored in human sweat and vocal cords.',
      tags: ['Sanctuary', 'Acoustic Architecture', 'Blackwater Cape', 'Living Building'],
      linkedCharacterIds: ['char-julian', 'char-martha', 'char-clara'],
      linkedChapterIds: ['chap-1'],
      significance: 'Core Narrative',
    },
    {
      id: 'codex-blackwater-cape',
      title: 'Blackwater Cape',
      category: 'location',
      shortDescription: 'A knife-edge promontory of black basalt jutting into the North Atlantic, notorious for dense sea fogs and shipwrecks.',
      detailedLore: 'The cape is known locally as The Needle. The water temperature rarely exceeds 48°F, and the sea bottom drops off into an abyss only fifty yards from the cliffs. Local fishermen refuse to navigate within three cables of the headland after sunset.',
      sensoryDetails: 'Roar of heavy swell crashing against submerged sea-caves; thick salt vapor that leaves an oily crystalline crust on skin and spectacles.',
      secrets: 'Beneath the cape lies an ancient network of submerged caverns that act as the acoustic resonator for the Conservatory keystones.',
      tags: ['Geography', 'Coastal', 'Atmosphere'],
      linkedCharacterIds: ['char-martha'],
      significance: 'Core Narrative',
    },
    {
      id: 'codex-resonance-masonry',
      title: 'Resonance Masonry',
      category: 'magic_tech',
      shortDescription: 'A lost architectural discipline combining acoustic physics, mineral crystalline alignment, and pneumatic structural stress.',
      detailedLore: 'Developed by fringe Victorian architects who believed sound and consciousness could be trapped in lime mortar if struck at specific resonant frequencies during the curing process. Buildings constructed this way act as passive phonographs.',
      sensoryDetails: 'A high, hair-thin ringing sound that vibrates the molars when leaning one’s ear against load-bearing masonry.',
      secrets: 'Clara Mercer discovered that speaking certain frequencies directly into the mortar joints could unlock internal hidden corridors without chiseling a single brick.',
      tags: ['Discipline', 'Science', 'Memory', 'Keystones'],
      linkedCharacterIds: ['char-julian', 'char-clara'],
      significance: 'Core Narrative',
    },
    {
      id: 'codex-keystones-1912',
      title: 'The Seven Keystones of 1912',
      category: 'relic',
      shortDescription: 'Carved granite wedges inscribed with wave harmonics and mathematical equations, installed secretly during the 1912 renovation.',
      detailedLore: 'Julian discovered Clara’s signature stamped beside the mason mark on Keystone IV, despite the mortar being over a century old. Each keystone controls the expansion of one quadrant of the house.',
      sensoryDetails: 'Cold to the touch even when heated by direct hearth flames. Faint phosphorescent green sheen under ultraviolet moonlight.',
      secrets: 'Removing Keystone VII will cause the entire conservatory to fold inward and slide down the cliff into the sea abyss.',
      tags: ['Relic', 'Artifact', 'Keystone', 'Mystery'],
      linkedCharacterIds: ['char-julian', 'char-clara'],
      significance: 'Core Narrative',
    },
    {
      id: 'codex-offshore-syndicate',
      title: 'The Vane-Caldwell Offshore Syndicate',
      category: 'faction',
      shortDescription: 'A ruthless multinational private development consortium seeking to raze Highclere to build a deepwater mineral terminal.',
      detailedLore: 'Operated by front companies in Zurich and London. They purchased the deed to Blackwater Cape through a foreclosure loop and have given Martha Highclere twenty-one days to vacate before demolition explosives are planted.',
      sensoryDetails: 'Smell of expensive tobacco, diesel tugboat fumes, sharp legal paper, crisp sealed eviction writs.',
      secrets: 'The syndicate is aware of the resonance properties and wants to recover the keystones for military acoustic stealth research.',
      tags: ['Antagonist', 'Corporation', 'Deadline'],
      linkedCharacterIds: ['char-martha'],
      significance: 'Subplot Lore',
    },
  ],
  timelineEvents: [
    {
      id: 'time-1892',
      title: 'Highclere Conservatory Foundation Laid',
      storyDate: 'October 14, 1892',
      storyOrder: 1,
      isFlashback: true,
      track: 'Historical Lore',
      location: 'Blackwater Cape',
      summary: 'Alistair Highclere commissions the subterranean basalt vaults, embedding maritime bronze flutes along the cliff foundation.',
      impactLevel: 'Medium',
    },
    {
      id: 'time-1912',
      title: 'The Great Solstice Vanishing',
      storyDate: 'December 21, 1912',
      storyOrder: 2,
      isFlashback: true,
      track: 'Historical Lore',
      location: 'Highclere North Gallery',
      summary: 'Alistair Highclere and three stonemasons seal themselves inside the central rotunda during a hurricane; when opened, only empty clothes remain.',
      impactLevel: 'Catastrophic Climax',
    },
    {
      id: 'time-3yr-ago',
      title: 'Clara Mercer Disappears at Highclere',
      storyDate: 'November 4, 3 Years Ago',
      storyOrder: 3,
      isFlashback: true,
      track: 'Character Arc / Romance',
      povCharacterId: 'char-clara',
      location: 'Mirror Cloister',
      summary: 'Clara documents her final acoustic equation in her leather journal and steps through the dissolving mortar wall in the basement.',
      impactLevel: 'High',
    },
    {
      id: 'time-day-1-am',
      title: 'Julian Mercer Arrives at Blackwater Cape',
      storyDate: 'Present Day, October 3 (08:00)',
      storyOrder: 4,
      narrativeChapterId: 'chap-1',
      isFlashback: false,
      track: 'Main Quest',
      povCharacterId: 'char-julian',
      location: 'Highclere Drive & Gatehouse',
      summary: 'Julian drives through dense salt fog, meets Martha, and notes that the exterior conservatory dimensions do not match the blueprint.',
      impactLevel: 'Low',
    },
    {
      id: 'time-day-1-dusk',
      title: 'The Dusk Expansion & 1912 Cipher Discovery',
      storyDate: 'Present Day, October 3 (18:15)',
      storyOrder: 5,
      narrativeChapterId: 'chap-1',
      isFlashback: false,
      track: 'Main Quest',
      povCharacterId: 'char-julian',
      location: 'North Gallery Atrium',
      summary: 'At sundown, the walls creak and expand three meters outward. Julian scrapes back mortar and discovers Clara’s fresh handwriting dated 1912.',
      impactLevel: 'High',
    },
    {
      id: 'time-day-2',
      title: 'Discovery of the Subterranean Mirror Cloister',
      storyDate: 'Present Day, October 4 (14:30)',
      storyOrder: 6,
      narrativeChapterId: 'chap-2',
      isFlashback: false,
      track: 'Main Quest',
      povCharacterId: 'char-julian',
      location: 'Basement Cloister',
      summary: 'Julian breaks Martha’s padlocks and enters the cellar, finding mirrors that show ocean depth instead of light.',
      impactLevel: 'High',
    },
    {
      id: 'time-day-21',
      title: 'Winter Solstice / Syndicate Demolition Deadline',
      storyDate: 'Present Day, October 24 (Solstice Equinox)',
      storyOrder: 7,
      isFlashback: false,
      track: 'Antagonist Conspiracy',
      location: 'Blackwater Cape',
      summary: 'The 21-day eviction order expires; syndicate demolition crews arrive as the annual maximum tide converges on the house.',
      impactLevel: 'Catastrophic Climax',
    },
  ],
  characterRelationships: [
    {
      id: 'rel-julian-clara',
      sourceCharacterId: 'char-julian',
      targetCharacterId: 'char-clara',
      relationshipType: 'Family',
      description: 'Devoted brother consumed by survivor guilt; believes Clara found a scientific breakthrough that unhinged her reality.',
      tensionScore: 9,
      status: 'Active',
    },
    {
      id: 'rel-julian-martha',
      sourceCharacterId: 'char-julian',
      targetCharacterId: 'char-martha',
      relationshipType: 'Unresolved Tension',
      description: 'Mutual dependence masked by sharp distrust. Julian needs her records; Martha needs his calculations to keep the cliffs standing.',
      tensionScore: 7,
      evolutionChapter: 2,
      status: 'Active',
    },
    {
      id: 'rel-martha-clara',
      sourceCharacterId: 'char-martha',
      targetCharacterId: 'char-clara',
      relationshipType: 'Mentor',
      description: 'Martha was Clara’s guide and confidante before Clara grew obsessed with opening the cloister doors.',
      tensionScore: 8,
      status: 'Fractured',
    },
  ],
  queryPitch: {
    targetAgentName: 'Victoria Marlo',
    agencyName: 'Marlo & Finch Literary Agency',
    hook: 'What if the ghost in the haunted house isn’t a phantom, but an impossible floorplan mapping your own grief in stone?',
    genre: 'Literary Speculative Thriller / Gothic Mystery',
    wordCount: 82000,
    compTitles: 'PIRANESI meets THE HAUNTING OF HILL HOUSE with the architectural obsession of MEXICAN GOTHIC',
    protagonistIntro: 'Dr. Julian Mercer is an architectural conservator who believes buildings retain physical memory in their lime mortar. Still reeling from the unresolved disappearance of his brilliant architect sister Clara, Julian takes a final restoration contract on the stormy cliffs of Blackwater Cape.',
    incitingIncident: 'At Highclere Conservatory, a Victorian glass-and-basalt estate perched over a freezing Atlantic abyss, Julian discovers the building expands by three meters every dusk. When he scrapes lime from a newly formed corridor, he finds Clara’s unmistakable handwriting and mason cipher stamped beneath mortar that cured eighty years before she was born.',
    stakesAndChoice: 'With an offshore corporate syndicate preparing to blow the estate into the sea in twenty-one days, Julian must unravel the harmonic physics of the living house. But as the rooms reconfigure around his deepest memories, he faces an agonizing choice: dismantle the master keystone to survive, or allow the walls to consume him in exchange for seeing his sister one last time.',
    authorBio: 'Evelyn Vance holds a degree in architectural history from University College London. Her non-fiction essays on maritime ruin ecology have appeared in The Atlantic and Lapham’s Quarterly. The Architect of Echoes is her debut novel.',
    synopsisOnePage: 'THE ARCHITECT OF ECHOES (82,000 words) opens on Blackwater Cape, where conservator Dr. Julian Mercer arrives at the dilapidated Highclere Conservatory...\n\nACT I: Julian meets the hostile caretaker Martha Highclere and assesses the structure, scheduled for demolition in three weeks. At sunset, hydraulic tides trigger acoustic resonance in the basalt foundations, physically expanding the house. Julian finds his missing sister Clara’s handwriting etched in 1912 lime.\n\nACT II-A: Julian discovers the Subterranean Mirror Cloister, where mirrors reflect deep-sea currents rather than human faces. He learns Clara had been testing "Resonance Masonry"—using acoustic pitch to shift solid matter.\n\nACT II-B: Martha admits she withheld Clara’s final journal to prevent Julian from awakening the central rotunda. During a severe nor’easter, the syndicate serves final notice, cutting power. The house responds by sealing its exterior doors and transforming into an endless geometric labyrinth.\n\nACT III: Julian and Martha reach the core keystone chamber deep beneath the cliff line. There, an acoustic phantom of Clara speaks through the mortar, offering to rebuild her physical form if Julian surrenders the conservatory’s seal. Recognizing that the house reproduces grief rather than truth, Julian uses his stone chisel to shatter Keystone IV. The false corridors collapse safely, freeing Julian and Martha as the ocean floods the lower vaults, bringing peace to Clara’s memory.',
    synopsisFivePage: 'FULL CHAPTER-BY-CHAPTER DETAILED SYNOPSIS AVAILABLE FOR SUBMISSION\n\nChapter 1–3: Arrival at Blackwater Cape and the phenomenon of dusk expansion...\nChapter 4–8: Deciphering the 1912 ledger and the subterranean exploration...\nChapter 9–14: The storm convergence, syndicate siege, and Martha’s confession...\nChapter 15–20: Navigating the hypercube labyrinth and the final keystone sacrifice...',
  },
  researchNotes: [
    {
      id: 'res-hydraulic-keystones',
      title: 'Victorian Pneumatic Counterweights & Basalt Bedrock Resonance',
      category: 'Scientific & Technical',
      content: 'Late Victorian engineers (notably Brunel and William Armstrong) developed hydraulic accumulators that stored gravitational potential energy via weighted water rams. In porous basalt sea-cliffs, rhythmic swell pressure can force subterranean pneumatic chambers to produce infrasound standing waves (3–7 Hz), producing disorientation, auditory hallucinations, and resonant expansion in stone joints.',
      sourceUrl: 'Transactions of the Royal Architectural Society (1894, Vol. XII)',
      tags: ['Acoustics', 'Hydraulics', 'Victorian Engineering', 'Basalt'],
      linkedCharacterIds: ['char-julian', 'char-clara'],
      linkedCodexIds: ['codex-highclere', 'codex-resonance-masonry'],
      linkedChapterIds: ['chap-1'],
      linkedSceneIds: ['scene-1-2'],
      linkedPlotBeatIds: ['beat-1'],
      createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'res-lime-mortar-calcification',
      title: 'Historical Portland Stone Carbonation & Acoustic Retention',
      category: 'Material & Sensory',
      content: 'Lime mortars cure by absorbing atmospheric CO2 over decades, creating crystalline calcite bridges. High-salinity Atlantic sea fog accelerates superficial spalling while case-hardening interior core mortar. When struck, carbonated lime rings with a distinctive ceramic timbre (approx. 1420 Hz) compared to modern Portland cement’s dull thud.',
      sourceUrl: 'Building Research Establishment Special Report No. 44 (1962)',
      tags: ['Mortar', 'Petrology', 'Sensory Details', 'Conservation'],
      linkedCharacterIds: ['char-julian'],
      linkedCodexIds: ['codex-resonance-masonry'],
      linkedChapterIds: ['chap-1'],
      linkedSceneIds: ['scene-1-1'],
      linkedPlotBeatIds: ['beat-2'],
      createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'res-solstice-tide-tables',
      title: 'North Atlantic Autumnal Equinox & Perigean Spring Tides',
      category: 'Geographical',
      content: 'During the October perigean spring tide, astronomical tidal range at Blackwater Cape increases from 4.2m to 7.8m. Tidal rip currents exceed 9 knots through the offshore gullies, cutting off the causeway 4 hours before high water and flooding subterranean caverns under the foundation.',
      sourceUrl: 'Admiralty Tide Tables: North Coast of Ireland & Atlantic Approaches',
      tags: ['Tides', 'Blackwater Cape', 'Navigation', 'Deadline'],
      linkedCharacterIds: ['char-martha'],
      linkedCodexIds: ['codex-blackwater-cape'],
      linkedChapterIds: ['chap-2'],
      linkedPlotBeatIds: ['beat-4', 'beat-5'],
      createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
};

export const getInitialNovelProject = (): NovelProject => {
  return JSON.parse(JSON.stringify(INITIAL_NOVEL));
};
