import { SentenceDiagramData } from '../types';

export const BENCHMARK_SENTENCE_PRESETS: SentenceDiagramData[] = [
  // Class 3-4: Simple Subject + Verb + Modifiers
  {
    id: 'preset-simple-1',
    sentence: 'The curious black cat slept peacefully on the soft velvet cushion.',
    classification: 'simple',
    classLevelRecommendation: 'Class 4',
    strand: 'Simple Sentence Architecture & Modifiers',
    pedagogicalNotes:
      'A foundational simple sentence featuring a complete subject with two coordinate adjectives ("curious", "black") and an article, an intransitive verb ("slept"), an adverb of manner ("peacefully"), and an adverbial prepositional phrase of place ("on the soft velvet cushion").',
    clauses: [
      {
        id: 'c-1',
        type: 'principal',
        typeName: 'Principal (Independent) Clause',
        color: 'indigo',
        text: 'The curious black cat slept peacefully on the soft velvet cushion.',
        functionInSentence: 'Expresses the complete, standalone thought.',
        subject: {
          text: 'The curious black cat',
          headNoun: 'cat',
          modifiers: ['The', 'curious', 'black'],
        },
        predicate: {
          verbPhrase: 'slept',
          tense: 'Simple Past Active',
          transitivity: 'intransitive',
          adverbials: ['peacefully', 'on the soft velvet cushion'],
        },
      },
    ],
    tokens: [
      { id: 't-1', word: 'The', pos: 'determiner', role: 'determiner', roleLabel: 'Definite Article', clauseId: 'c-1', clauseName: 'Principal Clause', modifiesTarget: 'cat' },
      { id: 't-2', word: 'curious', pos: 'adjective', role: 'adjective_modifier', roleLabel: 'Descriptive Adjective', clauseId: 'c-1', clauseName: 'Principal Clause', modifiesTarget: 'cat' },
      { id: 't-3', word: 'black', pos: 'adjective', role: 'adjective_modifier', roleLabel: 'Descriptive Adjective', clauseId: 'c-1', clauseName: 'Principal Clause', modifiesTarget: 'cat' },
      { id: 't-4', word: 'cat', pos: 'noun', role: 'subject', roleLabel: 'Subject (Head Noun)', clauseId: 'c-1', clauseName: 'Principal Clause' },
      { id: 't-5', word: 'slept', pos: 'verb', role: 'predicate_verb', roleLabel: 'Finite Intransitive Verb', clauseId: 'c-1', clauseName: 'Principal Clause' },
      { id: 't-6', word: 'peacefully', pos: 'adverb', role: 'adverb_modifier', roleLabel: 'Adverb of Manner', clauseId: 'c-1', clauseName: 'Principal Clause', modifiesTarget: 'slept' },
      { id: 't-7', word: 'on', pos: 'preposition', role: 'preposition', roleLabel: 'Preposition of Place', clauseId: 'c-1', clauseName: 'Principal Clause', modifiesTarget: 'slept' },
      { id: 't-8', word: 'the', pos: 'determiner', role: 'determiner', roleLabel: 'Definite Article', clauseId: 'c-1', clauseName: 'Principal Clause', modifiesTarget: 'cushion' },
      { id: 't-9', word: 'soft', pos: 'adjective', role: 'adjective_modifier', roleLabel: 'Descriptive Adjective', clauseId: 'c-1', clauseName: 'Principal Clause', modifiesTarget: 'cushion' },
      { id: 't-10', word: 'velvet', pos: 'noun', role: 'adjective_modifier', roleLabel: 'Noun Adjunct (Modifier)', clauseId: 'c-1', clauseName: 'Principal Clause', modifiesTarget: 'cushion' },
      { id: 't-11', word: 'cushion', pos: 'noun', role: 'object_of_preposition', roleLabel: 'Object of Preposition "on"', clauseId: 'c-1', clauseName: 'Principal Clause' },
    ],
    reedKellogg: [
      {
        clauseId: 'c-1',
        clauseType: 'principal',
        subject: 'cat',
        subjectModifiers: [
          { word: 'The', type: 'determiner' },
          { word: 'curious', type: 'adjective' },
          { word: 'black', type: 'adjective' },
        ],
        verb: 'slept',
        verbModifiers: [{ word: 'peacefully', type: 'adverb' }],
        prepPhrases: [
          {
            preposition: 'on',
            object: 'cushion',
            attachesTo: 'verb',
            modifiers: ['the', 'soft', 'velvet'],
          },
        ],
      },
    ],
    syntaxTree: {
      id: 'node-root',
      label: 'S',
      fullLabel: 'Simple Sentence',
      category: 'clause',
      text: 'The curious black cat slept peacefully on the soft velvet cushion.',
      children: [
        {
          id: 'np-1',
          label: 'NP',
          fullLabel: 'Noun Phrase (Subject)',
          category: 'phrase',
          children: [
            { id: 'det-1', label: 'Det', fullLabel: 'Determiner', category: 'word', text: 'The' },
            { id: 'adj-1', label: 'Adj', fullLabel: 'Adjective', category: 'word', text: 'curious' },
            { id: 'adj-2', label: 'Adj', fullLabel: 'Adjective', category: 'word', text: 'black' },
            { id: 'n-1', label: 'N', fullLabel: 'Head Noun', category: 'word', text: 'cat' },
          ],
        },
        {
          id: 'vp-1',
          label: 'VP',
          fullLabel: 'Verb Phrase (Predicate)',
          category: 'phrase',
          children: [
            { id: 'v-1', label: 'V', fullLabel: 'Intransitive Verb', category: 'word', text: 'slept' },
            { id: 'adv-1', label: 'Adv', fullLabel: 'Adverb of Manner', category: 'word', text: 'peacefully' },
            {
              id: 'pp-1',
              label: 'PP',
              fullLabel: 'Prepositional Phrase (Adverbial of Place)',
              category: 'phrase',
              children: [
                { id: 'p-1', label: 'P', fullLabel: 'Preposition', category: 'word', text: 'on' },
                {
                  id: 'np-2',
                  label: 'NP',
                  fullLabel: 'Noun Phrase (Object of Preposition)',
                  category: 'phrase',
                  children: [
                    { id: 'det-2', label: 'Det', fullLabel: 'Determiner', category: 'word', text: 'the' },
                    { id: 'adj-3', label: 'Adj', fullLabel: 'Adjective', category: 'word', text: 'soft' },
                    { id: 'n-mod', label: 'Adj', fullLabel: 'Noun Adjunct', category: 'word', text: 'velvet' },
                    { id: 'n-2', label: 'N', fullLabel: 'Noun', category: 'word', text: 'cushion' },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  },

  // Class 5: Transitive Verb + Direct Object & Indirect Object
  {
    id: 'preset-simple-transitive-2',
    sentence: 'The enthusiastic young botanist showed the eager visitors a rare Himalayan orchid.',
    classification: 'simple',
    classLevelRecommendation: 'Class 5',
    strand: 'Ditransitive Verb Architecture (Direct & Indirect Objects)',
    pedagogicalNotes:
      'Demonstrates ditransitive syntax where the verb "showed" takes an indirect object ("visitors") followed by a direct object ("orchid"). In Reed-Kellogg diagramming, the direct object is placed on the baseline separated by a vertical line, while the indirect object rests on a preposition-style branch underneath the verb.',
    clauses: [
      {
        id: 'c-1',
        type: 'principal',
        typeName: 'Principal Clause (Ditransitive)',
        color: 'indigo',
        text: 'The enthusiastic young botanist showed the eager visitors a rare Himalayan orchid.',
        functionInSentence: 'Independent clause with subject, verb, indirect object, and direct object.',
        subject: {
          text: 'The enthusiastic young botanist',
          headNoun: 'botanist',
          modifiers: ['The', 'enthusiastic', 'young'],
        },
        predicate: {
          verbPhrase: 'showed',
          tense: 'Simple Past',
          transitivity: 'transitive',
          indirectObject: 'the eager visitors',
          directObject: 'a rare Himalayan orchid',
          adverbials: [],
        },
      },
    ],
    tokens: [
      { id: 't-1', word: 'The', pos: 'determiner', role: 'determiner', roleLabel: 'Definite Article', clauseId: 'c-1', clauseName: 'Principal Clause', modifiesTarget: 'botanist' },
      { id: 't-2', word: 'enthusiastic', pos: 'adjective', role: 'adjective_modifier', roleLabel: 'Adjective', clauseId: 'c-1', clauseName: 'Principal Clause', modifiesTarget: 'botanist' },
      { id: 't-3', word: 'young', pos: 'adjective', role: 'adjective_modifier', roleLabel: 'Adjective', clauseId: 'c-1', clauseName: 'Principal Clause', modifiesTarget: 'botanist' },
      { id: 't-4', word: 'botanist', pos: 'noun', role: 'subject', roleLabel: 'Subject Head', clauseId: 'c-1', clauseName: 'Principal Clause' },
      { id: 't-5', word: 'showed', pos: 'verb', role: 'predicate_verb', roleLabel: 'Ditransitive Verb', clauseId: 'c-1', clauseName: 'Principal Clause' },
      { id: 't-6', word: 'the', pos: 'determiner', role: 'determiner', roleLabel: 'Definite Article', clauseId: 'c-1', clauseName: 'Principal Clause', modifiesTarget: 'visitors' },
      { id: 't-7', word: 'eager', pos: 'adjective', role: 'adjective_modifier', roleLabel: 'Adjective', clauseId: 'c-1', clauseName: 'Principal Clause', modifiesTarget: 'visitors' },
      { id: 't-8', word: 'visitors', pos: 'noun', role: 'indirect_object', roleLabel: 'Indirect Object', clauseId: 'c-1', clauseName: 'Principal Clause' },
      { id: 't-9', word: 'a', pos: 'determiner', role: 'determiner', roleLabel: 'Indefinite Article', clauseId: 'c-1', clauseName: 'Principal Clause', modifiesTarget: 'orchid' },
      { id: 't-10', word: 'rare', pos: 'adjective', role: 'adjective_modifier', roleLabel: 'Adjective', clauseId: 'c-1', clauseName: 'Principal Clause', modifiesTarget: 'orchid' },
      { id: 't-11', word: 'Himalayan', pos: 'adjective', role: 'adjective_modifier', roleLabel: 'Proper Adjective', clauseId: 'c-1', clauseName: 'Principal Clause', modifiesTarget: 'orchid' },
      { id: 't-12', word: 'orchid', pos: 'noun', role: 'direct_object', roleLabel: 'Direct Object', clauseId: 'c-1', clauseName: 'Principal Clause' },
    ],
    reedKellogg: [
      {
        clauseId: 'c-1',
        clauseType: 'principal',
        subject: 'botanist',
        subjectModifiers: [
          { word: 'The', type: 'determiner' },
          { word: 'enthusiastic', type: 'adjective' },
          { word: 'young', type: 'adjective' },
        ],
        verb: 'showed',
        verbModifiers: [],
        objectOrComplement: 'orchid',
        complementType: 'direct_object',
        objectModifiers: [
          { word: 'a', type: 'determiner' },
          { word: 'rare', type: 'adjective' },
          { word: 'Himalayan', type: 'adjective' },
        ],
        prepPhrases: [
          {
            preposition: '[to]',
            object: 'visitors',
            attachesTo: 'verb',
            modifiers: ['the', 'eager'],
          },
        ],
      },
    ],
    syntaxTree: {
      id: 'node-root',
      label: 'S',
      fullLabel: 'Simple Sentence (Ditransitive)',
      category: 'clause',
      text: 'The enthusiastic young botanist showed the eager visitors a rare Himalayan orchid.',
      children: [
        {
          id: 'np-sub',
          label: 'NP',
          fullLabel: 'Subject Noun Phrase',
          category: 'phrase',
          children: [
            { id: 'd-1', label: 'Det', fullLabel: 'Determiner', category: 'word', text: 'The' },
            { id: 'adj-1', label: 'Adj', fullLabel: 'Adjective', category: 'word', text: 'enthusiastic' },
            { id: 'adj-2', label: 'Adj', fullLabel: 'Adjective', category: 'word', text: 'young' },
            { id: 'n-1', label: 'N', fullLabel: 'Noun', category: 'word', text: 'botanist' },
          ],
        },
        {
          id: 'vp-main',
          label: 'VP',
          fullLabel: 'Verb Phrase',
          category: 'phrase',
          children: [
            { id: 'v-1', label: 'V', fullLabel: 'Ditransitive Verb', category: 'word', text: 'showed' },
            {
              id: 'np-io',
              label: 'NP (IO)',
              fullLabel: 'Indirect Object Noun Phrase',
              category: 'phrase',
              children: [
                { id: 'd-2', label: 'Det', fullLabel: 'Determiner', category: 'word', text: 'the' },
                { id: 'adj-3', label: 'Adj', fullLabel: 'Adjective', category: 'word', text: 'eager' },
                { id: 'n-2', label: 'N', fullLabel: 'Noun', category: 'word', text: 'visitors' },
              ],
            },
            {
              id: 'np-do',
              label: 'NP (DO)',
              fullLabel: 'Direct Object Noun Phrase',
              category: 'phrase',
              children: [
                { id: 'd-3', label: 'Det', fullLabel: 'Determiner', category: 'word', text: 'a' },
                { id: 'adj-4', label: 'Adj', fullLabel: 'Adjective', category: 'word', text: 'rare' },
                { id: 'adj-5', label: 'Adj', fullLabel: 'Proper Adjective', category: 'word', text: 'Himalayan' },
                { id: 'n-3', label: 'N', fullLabel: 'Noun', category: 'word', text: 'orchid' },
              ],
            },
          ],
        },
      ],
    },
  },

  // Class 6: Compound Sentence with FANBOYS Conjunction ("but")
  {
    id: 'preset-compound-1',
    sentence: 'Rohan practiced his violin diligently every morning, but his elder sister preferred mathematics.',
    classification: 'compound',
    classLevelRecommendation: 'Class 6',
    strand: 'Compound Sentences & Coordinating Conjunctions',
    pedagogicalNotes:
      'A canonical compound sentence consisting of two syntactically equal independent clauses joined by the coordinating conjunction "but". In Reed-Kellogg diagramming, the two clauses occupy parallel baselines, bridged by a dashed step line carrying the conjunction.',
    clauses: [
      {
        id: 'c-1',
        type: 'principal',
        typeName: 'Independent Clause 1',
        color: 'indigo',
        text: 'Rohan practiced his violin diligently every morning',
        functionInSentence: 'First independent proposition.',
        subject: {
          text: 'Rohan',
          headNoun: 'Rohan',
          modifiers: [],
        },
        predicate: {
          verbPhrase: 'practiced',
          tense: 'Simple Past',
          transitivity: 'transitive',
          directObject: 'his violin',
          adverbials: ['diligently', 'every morning'],
        },
      },
      {
        id: 'c-2',
        type: 'coordinate',
        typeName: 'Independent Clause 2',
        color: 'cyan',
        text: 'his elder sister preferred mathematics',
        conjunction: 'but',
        functionInSentence: 'Second independent proposition expressing contrast.',
        subject: {
          text: 'his elder sister',
          headNoun: 'sister',
          modifiers: ['his', 'elder'],
        },
        predicate: {
          verbPhrase: 'preferred',
          tense: 'Simple Past',
          transitivity: 'transitive',
          directObject: 'mathematics',
          adverbials: [],
        },
      },
    ],
    tokens: [
      { id: 't-1', word: 'Rohan', pos: 'noun', role: 'subject', roleLabel: 'Proper Noun (Subject)', clauseId: 'c-1', clauseName: 'Independent Clause 1' },
      { id: 't-2', word: 'practiced', pos: 'verb', role: 'predicate_verb', roleLabel: 'Transitive Verb', clauseId: 'c-1', clauseName: 'Independent Clause 1' },
      { id: 't-3', word: 'his', pos: 'pronoun', role: 'determiner', roleLabel: 'Possessive Determiner', clauseId: 'c-1', clauseName: 'Independent Clause 1', modifiesTarget: 'violin' },
      { id: 't-4', word: 'violin', pos: 'noun', role: 'direct_object', roleLabel: 'Direct Object', clauseId: 'c-1', clauseName: 'Independent Clause 1' },
      { id: 't-5', word: 'diligently', pos: 'adverb', role: 'adverb_modifier', roleLabel: 'Adverb of Manner', clauseId: 'c-1', clauseName: 'Independent Clause 1', modifiesTarget: 'practiced' },
      { id: 't-6', word: 'every', pos: 'determiner', role: 'determiner', roleLabel: 'Distributive Determiner', clauseId: 'c-1', clauseName: 'Independent Clause 1', modifiesTarget: 'morning' },
      { id: 't-7', word: 'morning', pos: 'noun', role: 'adverb_modifier', roleLabel: 'Adverbial Objective (Time)', clauseId: 'c-1', clauseName: 'Independent Clause 1', modifiesTarget: 'practiced' },
      { id: 't-8', word: 'but', pos: 'conjunction', role: 'coordinating_conjunction', roleLabel: 'Coordinating Conjunction', clauseId: 'c-2', clauseName: 'Independent Clause 2' },
      { id: 't-9', word: 'his', pos: 'pronoun', role: 'determiner', roleLabel: 'Possessive Determiner', clauseId: 'c-2', clauseName: 'Independent Clause 2', modifiesTarget: 'sister' },
      { id: 't-10', word: 'elder', pos: 'adjective', role: 'adjective_modifier', roleLabel: 'Adjective', clauseId: 'c-2', clauseName: 'Independent Clause 2', modifiesTarget: 'sister' },
      { id: 't-11', word: 'sister', pos: 'noun', role: 'subject', roleLabel: 'Subject Head', clauseId: 'c-2', clauseName: 'Independent Clause 2' },
      { id: 't-12', word: 'preferred', pos: 'verb', role: 'predicate_verb', roleLabel: 'Transitive Verb', clauseId: 'c-2', clauseName: 'Independent Clause 2' },
      { id: 't-13', word: 'mathematics', pos: 'noun', role: 'direct_object', roleLabel: 'Direct Object', clauseId: 'c-2', clauseName: 'Independent Clause 2' },
    ],
    reedKellogg: [
      {
        clauseId: 'c-1',
        clauseType: 'principal',
        subject: 'Rohan',
        subjectModifiers: [],
        verb: 'practiced',
        verbModifiers: [
          { word: 'diligently', type: 'adverb' },
          { word: 'every morning', type: 'adverb' },
        ],
        objectOrComplement: 'violin',
        complementType: 'direct_object',
        objectModifiers: [{ word: 'his', type: 'determiner' }],
        prepPhrases: [],
      },
      {
        clauseId: 'c-2',
        clauseType: 'coordinate',
        conjunctionToParent: {
          word: 'but',
          dashedConnectorText: 'Coordinating Conjunction',
        },
        subject: 'sister',
        subjectModifiers: [
          { word: 'his', type: 'determiner' },
          { word: 'elder', type: 'adjective' },
        ],
        verb: 'preferred',
        verbModifiers: [],
        objectOrComplement: 'mathematics',
        complementType: 'direct_object',
        objectModifiers: [],
        prepPhrases: [],
      },
    ],
    syntaxTree: {
      id: 'node-root',
      label: 'S (Compound)',
      fullLabel: 'Compound Sentence',
      category: 'clause',
      text: 'Rohan practiced his violin diligently every morning, but his elder sister preferred mathematics.',
      children: [
        {
          id: 's-1',
          label: 'S1',
          fullLabel: 'Independent Clause 1',
          category: 'clause',
          children: [
            {
              id: 'np-1',
              label: 'NP',
              fullLabel: 'Subject',
              category: 'phrase',
              children: [{ id: 'n-1', label: 'N', fullLabel: 'Proper Noun', category: 'word', text: 'Rohan' }],
            },
            {
              id: 'vp-1',
              label: 'VP',
              fullLabel: 'Verb Phrase',
              category: 'phrase',
              children: [
                { id: 'v-1', label: 'V', fullLabel: 'Verb', category: 'word', text: 'practiced' },
                {
                  id: 'np-do-1',
                  label: 'NP',
                  fullLabel: 'Direct Object',
                  category: 'phrase',
                  children: [
                    { id: 'det-1', label: 'Det', fullLabel: 'Possessive', category: 'word', text: 'his' },
                    { id: 'n-v', label: 'N', fullLabel: 'Noun', category: 'word', text: 'violin' },
                  ],
                },
                { id: 'adv-1', label: 'Adv', fullLabel: 'Adverb', category: 'word', text: 'diligently' },
                { id: 'np-time', label: 'NP (Adv)', fullLabel: 'Adverbial NP', category: 'phrase', text: 'every morning' },
              ],
            },
          ],
        },
        {
          id: 'cc-1',
          label: 'CC',
          fullLabel: 'Coordinating Conjunction',
          category: 'word',
          text: 'but',
        },
        {
          id: 's-2',
          label: 'S2',
          fullLabel: 'Independent Clause 2',
          category: 'clause',
          children: [
            {
              id: 'np-2',
              label: 'NP',
              fullLabel: 'Subject',
              category: 'phrase',
              children: [
                { id: 'det-2', label: 'Det', fullLabel: 'Possessive', category: 'word', text: 'his' },
                { id: 'adj-2', label: 'Adj', fullLabel: 'Adjective', category: 'word', text: 'elder' },
                { id: 'n-2', label: 'N', fullLabel: 'Noun', category: 'word', text: 'sister' },
              ],
            },
            {
              id: 'vp-2',
              label: 'VP',
              fullLabel: 'Verb Phrase',
              category: 'phrase',
              children: [
                { id: 'v-2', label: 'V', fullLabel: 'Verb', category: 'word', text: 'preferred' },
                { id: 'n-3', label: 'NP', fullLabel: 'Direct Object', category: 'phrase', text: 'mathematics' },
              ],
            },
          ],
        },
      ],
    },
  },

  // Class 7-8: Complex Sentence with Subordinate Adverbial Clause of Concession
  {
    id: 'preset-complex-adverb-1',
    sentence: 'Although the stormy weather delayed the flights, all passengers reached their destinations safely.',
    classification: 'complex',
    classLevelRecommendation: 'Class 7',
    strand: 'Complex Sentences & Subordinate Adverbial Clauses',
    pedagogicalNotes:
      'A complex sentence with an initial subordinate adverbial clause of concession introduced by "Although". The subordinate clause modifies the main verb "reached" by stating an opposing circumstance. Notice how the subordinate baseline is suspended from the main verb by a dashed line carrying "Although".',
    clauses: [
      {
        id: 'c-sub',
        type: 'subordinate_adverb',
        typeName: 'Subordinate Adverbial Clause of Concession',
        color: 'emerald',
        text: 'Although the stormy weather delayed the flights',
        conjunction: 'Although',
        functionInSentence: 'Modifies the main verb "reached" by conceding an adverse condition.',
        subject: {
          text: 'the stormy weather',
          headNoun: 'weather',
          modifiers: ['the', 'stormy'],
        },
        predicate: {
          verbPhrase: 'delayed',
          tense: 'Simple Past Active',
          transitivity: 'transitive',
          directObject: 'the flights',
          adverbials: [],
        },
      },
      {
        id: 'c-main',
        type: 'principal',
        typeName: 'Principal (Independent) Clause',
        color: 'indigo',
        text: 'all passengers reached their destinations safely',
        functionInSentence: 'The main proposition of the sentence.',
        subject: {
          text: 'all passengers',
          headNoun: 'passengers',
          modifiers: ['all'],
        },
        predicate: {
          verbPhrase: 'reached',
          tense: 'Simple Past',
          transitivity: 'transitive',
          directObject: 'their destinations',
          adverbials: ['safely'],
        },
      },
    ],
    tokens: [
      { id: 't-1', word: 'Although', pos: 'conjunction', role: 'subordinating_conjunction', roleLabel: 'Subordinating Conjunction (Concession)', clauseId: 'c-sub', clauseName: 'Subordinate Adverbial Clause' },
      { id: 't-2', word: 'the', pos: 'determiner', role: 'determiner', roleLabel: 'Definite Article', clauseId: 'c-sub', clauseName: 'Subordinate Adverbial Clause', modifiesTarget: 'weather' },
      { id: 't-3', word: 'stormy', pos: 'adjective', role: 'adjective_modifier', roleLabel: 'Adjective', clauseId: 'c-sub', clauseName: 'Subordinate Adverbial Clause', modifiesTarget: 'weather' },
      { id: 't-4', word: 'weather', pos: 'noun', role: 'subject', roleLabel: 'Subject Head (Subordinate)', clauseId: 'c-sub', clauseName: 'Subordinate Adverbial Clause' },
      { id: 't-5', word: 'delayed', pos: 'verb', role: 'predicate_verb', roleLabel: 'Transitive Verb', clauseId: 'c-sub', clauseName: 'Subordinate Adverbial Clause' },
      { id: 't-6', word: 'the', pos: 'determiner', role: 'determiner', roleLabel: 'Definite Article', clauseId: 'c-sub', clauseName: 'Subordinate Adverbial Clause', modifiesTarget: 'flights' },
      { id: 't-7', word: 'flights', pos: 'noun', role: 'direct_object', roleLabel: 'Direct Object', clauseId: 'c-sub', clauseName: 'Subordinate Adverbial Clause' },
      { id: 't-8', word: 'all', pos: 'determiner', role: 'determiner', roleLabel: 'Quantifier Determiner', clauseId: 'c-main', clauseName: 'Principal Clause', modifiesTarget: 'passengers' },
      { id: 't-9', word: 'passengers', pos: 'noun', role: 'subject', roleLabel: 'Principal Subject Head', clauseId: 'c-main', clauseName: 'Principal Clause' },
      { id: 't-10', word: 'reached', pos: 'verb', role: 'predicate_verb', roleLabel: 'Principal Transitive Verb', clauseId: 'c-main', clauseName: 'Principal Clause' },
      { id: 't-11', word: 'their', pos: 'pronoun', role: 'determiner', roleLabel: 'Possessive Determiner', clauseId: 'c-main', clauseName: 'Principal Clause', modifiesTarget: 'destinations' },
      { id: 't-12', word: 'destinations', pos: 'noun', role: 'direct_object', roleLabel: 'Direct Object', clauseId: 'c-main', clauseName: 'Principal Clause' },
      { id: 't-13', word: 'safely', pos: 'adverb', role: 'adverb_modifier', roleLabel: 'Adverb of Manner', clauseId: 'c-main', clauseName: 'Principal Clause', modifiesTarget: 'reached' },
    ],
    reedKellogg: [
      {
        clauseId: 'c-main',
        clauseType: 'principal',
        subject: 'passengers',
        subjectModifiers: [{ word: 'all', type: 'determiner' }],
        verb: 'reached',
        verbModifiers: [{ word: 'safely', type: 'adverb' }],
        objectOrComplement: 'destinations',
        complementType: 'direct_object',
        objectModifiers: [{ word: 'their', type: 'determiner' }],
        prepPhrases: [],
      },
      {
        clauseId: 'c-sub',
        clauseType: 'subordinate_adverb',
        conjunctionToParent: {
          word: 'Although',
          dashedConnectorText: 'Adverb Clause of Concession (modifies "reached")',
        },
        subject: 'weather',
        subjectModifiers: [
          { word: 'the', type: 'determiner' },
          { word: 'stormy', type: 'adjective' },
        ],
        verb: 'delayed',
        verbModifiers: [],
        objectOrComplement: 'flights',
        complementType: 'direct_object',
        objectModifiers: [{ word: 'the', type: 'determiner' }],
        prepPhrases: [],
      },
    ],
    syntaxTree: {
      id: 'node-root',
      label: 'S (Complex)',
      fullLabel: 'Complex Sentence',
      category: 'clause',
      text: 'Although the stormy weather delayed the flights, all passengers reached their destinations safely.',
      children: [
        {
          id: 'sbar-1',
          label: 'SBAR',
          fullLabel: 'Subordinate Clause (Adverbial)',
          category: 'clause',
          children: [
            { id: 'c-comp', label: 'Comp', fullLabel: 'Subordinator', category: 'word', text: 'Although' },
            {
              id: 's-sub-tree',
              label: 'S',
              fullLabel: 'Embedded Clause',
              category: 'clause',
              children: [
                {
                  id: 'np-sub-w',
                  label: 'NP',
                  fullLabel: 'Subject',
                  category: 'phrase',
                  children: [
                    { id: 'd-w1', label: 'Det', fullLabel: 'Determiner', category: 'word', text: 'the' },
                    { id: 'adj-w1', label: 'Adj', fullLabel: 'Adjective', category: 'word', text: 'stormy' },
                    { id: 'n-w1', label: 'N', fullLabel: 'Noun', category: 'word', text: 'weather' },
                  ],
                },
                {
                  id: 'vp-sub-d',
                  label: 'VP',
                  fullLabel: 'Verb Phrase',
                  category: 'phrase',
                  children: [
                    { id: 'v-sub1', label: 'V', fullLabel: 'Verb', category: 'word', text: 'delayed' },
                    {
                      id: 'np-fl',
                      label: 'NP',
                      fullLabel: 'Direct Object',
                      category: 'phrase',
                      children: [
                        { id: 'd-fl', label: 'Det', fullLabel: 'Determiner', category: 'word', text: 'the' },
                        { id: 'n-fl', label: 'N', fullLabel: 'Noun', category: 'word', text: 'flights' },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          id: 's-main-tree',
          label: 'S',
          fullLabel: 'Principal Clause',
          category: 'clause',
          children: [
            {
              id: 'np-pass',
              label: 'NP',
              fullLabel: 'Subject Noun Phrase',
              category: 'phrase',
              children: [
                { id: 'd-all', label: 'Det', fullLabel: 'Quantifier', category: 'word', text: 'all' },
                { id: 'n-pass', label: 'N', fullLabel: 'Noun', category: 'word', text: 'passengers' },
              ],
            },
            {
              id: 'vp-reached',
              label: 'VP',
              fullLabel: 'Verb Phrase',
              category: 'phrase',
              children: [
                { id: 'v-r', label: 'V', fullLabel: 'Verb', category: 'word', text: 'reached' },
                {
                  id: 'np-dest',
                  label: 'NP',
                  fullLabel: 'Direct Object',
                  category: 'phrase',
                  children: [
                    { id: 'd-their', label: 'Det', fullLabel: 'Possessive', category: 'word', text: 'their' },
                    { id: 'n-dest', label: 'N', fullLabel: 'Noun', category: 'word', text: 'destinations' },
                  ],
                },
                { id: 'adv-safely', label: 'Adv', fullLabel: 'Adverb of Manner', category: 'word', text: 'safely' },
              ],
            },
          ],
        },
      ],
    },
  },

  // Class 9: Relative (Adjective) Clause
  {
    id: 'preset-relative-clause-1',
    sentence: 'The ancient manuscript which the archaeologist discovered in the cave revealed a lost civilization.',
    classification: 'complex',
    classLevelRecommendation: 'Class 9',
    strand: 'Relative (Adjective) Clauses & Antecedent Binding',
    pedagogicalNotes:
      'A complex sentence containing a defining relative clause ("which the archaeologist discovered in the cave") that post-modifies the subject noun "manuscript". In Reed-Kellogg diagramming, the relative pronoun "which" serves as the direct object within the subordinate clause while simultaneously connecting via a dotted line to its antecedent "manuscript".',
    clauses: [
      {
        id: 'c-main',
        type: 'principal',
        typeName: 'Principal Clause',
        color: 'indigo',
        text: 'The ancient manuscript revealed a lost civilization',
        functionInSentence: 'Main independent clause holding the overarching predicate.',
        subject: {
          text: 'The ancient manuscript',
          headNoun: 'manuscript',
          modifiers: ['The', 'ancient'],
        },
        predicate: {
          verbPhrase: 'revealed',
          tense: 'Simple Past Active',
          transitivity: 'transitive',
          directObject: 'a lost civilization',
          adverbials: [],
        },
      },
      {
        id: 'c-rel',
        type: 'subordinate_relative',
        typeName: 'Subordinate Relative (Adjective) Clause',
        color: 'amber',
        text: 'which the archaeologist discovered in the cave',
        conjunction: 'which',
        functionInSentence: 'Modifies the antecedent noun "manuscript".',
        subject: {
          text: 'the archaeologist',
          headNoun: 'archaeologist',
          modifiers: ['the'],
        },
        predicate: {
          verbPhrase: 'discovered',
          tense: 'Simple Past',
          transitivity: 'transitive',
          directObject: 'which (referring to manuscript)',
          adverbials: ['in the cave'],
        },
      },
    ],
    tokens: [
      { id: 't-1', word: 'The', pos: 'determiner', role: 'determiner', roleLabel: 'Definite Article', clauseId: 'c-main', clauseName: 'Principal Clause', modifiesTarget: 'manuscript' },
      { id: 't-2', word: 'ancient', pos: 'adjective', role: 'adjective_modifier', roleLabel: 'Descriptive Adjective', clauseId: 'c-main', clauseName: 'Principal Clause', modifiesTarget: 'manuscript' },
      { id: 't-3', word: 'manuscript', pos: 'noun', role: 'subject', roleLabel: 'Subject Head (Antecedent)', clauseId: 'c-main', clauseName: 'Principal Clause' },
      { id: 't-4', word: 'which', pos: 'pronoun', role: 'direct_object', roleLabel: 'Relative Pronoun (DO of "discovered")', clauseId: 'c-rel', clauseName: 'Relative Clause', modifiesTarget: 'manuscript' },
      { id: 't-5', word: 'the', pos: 'determiner', role: 'determiner', roleLabel: 'Definite Article', clauseId: 'c-rel', clauseName: 'Relative Clause', modifiesTarget: 'archaeologist' },
      { id: 't-6', word: 'archaeologist', pos: 'noun', role: 'subject', roleLabel: 'Subject of Relative Clause', clauseId: 'c-rel', clauseName: 'Relative Clause' },
      { id: 't-7', word: 'discovered', pos: 'verb', role: 'predicate_verb', roleLabel: 'Transitive Verb', clauseId: 'c-rel', clauseName: 'Relative Clause' },
      { id: 't-8', word: 'in', pos: 'preposition', role: 'preposition', roleLabel: 'Preposition of Place', clauseId: 'c-rel', clauseName: 'Relative Clause', modifiesTarget: 'discovered' },
      { id: 't-9', word: 'the', pos: 'determiner', role: 'determiner', roleLabel: 'Definite Article', clauseId: 'c-rel', clauseName: 'Relative Clause', modifiesTarget: 'cave' },
      { id: 't-10', word: 'cave', pos: 'noun', role: 'object_of_preposition', roleLabel: 'Object of Preposition', clauseId: 'c-rel', clauseName: 'Relative Clause' },
      { id: 't-11', word: 'revealed', pos: 'verb', role: 'predicate_verb', roleLabel: 'Principal Transitive Verb', clauseId: 'c-main', clauseName: 'Principal Clause' },
      { id: 't-12', word: 'a', pos: 'determiner', role: 'determiner', roleLabel: 'Indefinite Article', clauseId: 'c-main', clauseName: 'Principal Clause', modifiesTarget: 'civilization' },
      { id: 't-13', word: 'lost', pos: 'adjective', role: 'adjective_modifier', roleLabel: 'Participial Adjective', clauseId: 'c-main', clauseName: 'Principal Clause', modifiesTarget: 'civilization' },
      { id: 't-14', word: 'civilization', pos: 'noun', role: 'direct_object', roleLabel: 'Direct Object Head', clauseId: 'c-main', clauseName: 'Principal Clause' },
    ],
    reedKellogg: [
      {
        clauseId: 'c-main',
        clauseType: 'principal',
        subject: 'manuscript',
        subjectModifiers: [
          { word: 'The', type: 'determiner' },
          { word: 'ancient', type: 'adjective' },
        ],
        verb: 'revealed',
        verbModifiers: [],
        objectOrComplement: 'civilization',
        complementType: 'direct_object',
        objectModifiers: [
          { word: 'a', type: 'determiner' },
          { word: 'lost', type: 'adjective' },
        ],
        prepPhrases: [],
      },
      {
        clauseId: 'c-rel',
        clauseType: 'subordinate_relative',
        conjunctionToParent: {
          word: 'which',
          dashedConnectorText: 'Relative Pronoun connects to antecedent "manuscript"',
        },
        subject: 'archaeologist',
        subjectModifiers: [{ word: 'the', type: 'determiner' }],
        verb: 'discovered',
        verbModifiers: [],
        objectOrComplement: 'which',
        complementType: 'direct_object',
        objectModifiers: [],
        prepPhrases: [
          {
            preposition: 'in',
            object: 'cave',
            attachesTo: 'verb',
            modifiers: ['the'],
          },
        ],
      },
    ],
    syntaxTree: {
      id: 'node-root',
      label: 'S (Complex)',
      fullLabel: 'Complex Sentence with Relative Clause',
      category: 'clause',
      text: 'The ancient manuscript which the archaeologist discovered in the cave revealed a lost civilization.',
      children: [
        {
          id: 'np-sub-rel',
          label: 'NP',
          fullLabel: 'Subject Noun Phrase with Embedded Relative Clause',
          category: 'phrase',
          children: [
            { id: 'd-m', label: 'Det', fullLabel: 'Determiner', category: 'word', text: 'The' },
            { id: 'adj-m', label: 'Adj', fullLabel: 'Adjective', category: 'word', text: 'ancient' },
            { id: 'n-m', label: 'N', fullLabel: 'Head Noun', category: 'word', text: 'manuscript' },
            {
              id: 'rc-1',
              label: 'RC (SBAR)',
              fullLabel: 'Relative Clause',
              category: 'clause',
              children: [
                { id: 'rel-pro', label: 'RelPro', fullLabel: 'Relative Pronoun', category: 'word', text: 'which' },
                {
                  id: 's-rc',
                  label: 'S',
                  fullLabel: 'Clause',
                  category: 'clause',
                  children: [
                    { id: 'np-arch', label: 'NP', fullLabel: 'Subject', category: 'phrase', text: 'the archaeologist' },
                    { id: 'vp-disc', label: 'VP', fullLabel: 'Verb Phrase', category: 'phrase', text: 'discovered in the cave' },
                  ],
                },
              ],
            },
          ],
        },
        {
          id: 'vp-main-rev',
          label: 'VP',
          fullLabel: 'Main Verb Phrase',
          category: 'phrase',
          children: [
            { id: 'v-rev', label: 'V', fullLabel: 'Verb', category: 'word', text: 'revealed' },
            { id: 'np-civ', label: 'NP', fullLabel: 'Direct Object', category: 'phrase', text: 'a lost civilization' },
          ],
        },
      ],
    },
  },

  // Class 10: Noun Clause as Direct Object
  {
    id: 'preset-noun-clause-1',
    sentence: 'The research scientist proved that greenhouse emissions accelerate global warming.',
    classification: 'complex',
    classLevelRecommendation: 'Class 10',
    strand: 'Subordinate Noun Clauses & Complementizer "that"',
    pedagogicalNotes:
      'Features a subordinate noun clause ("that greenhouse emissions accelerate global warming") functioning as the direct object of the main transitive verb "proved". In Reed-Kellogg diagramming, the noun clause is elevated on a stilt/pedestal in place of a simple direct object noun.',
    clauses: [
      {
        id: 'c-main',
        type: 'principal',
        typeName: 'Principal Clause',
        color: 'indigo',
        text: 'The research scientist proved',
        functionInSentence: 'Main matrix clause.',
        subject: {
          text: 'The research scientist',
          headNoun: 'scientist',
          modifiers: ['The', 'research'],
        },
        predicate: {
          verbPhrase: 'proved',
          tense: 'Simple Past Active',
          transitivity: 'transitive',
          directObject: '[that greenhouse emissions accelerate global warming]',
          adverbials: [],
        },
      },
      {
        id: 'c-noun',
        type: 'subordinate_noun',
        typeName: 'Subordinate Noun Clause (Object of "proved")',
        color: 'rose',
        text: 'that greenhouse emissions accelerate global warming',
        conjunction: 'that',
        functionInSentence: 'Functions as the Direct Object of the verb "proved".',
        subject: {
          text: 'greenhouse emissions',
          headNoun: 'emissions',
          modifiers: ['greenhouse'],
        },
        predicate: {
          verbPhrase: 'accelerate',
          tense: 'Simple Present',
          transitivity: 'transitive',
          directObject: 'global warming',
          adverbials: [],
        },
      },
    ],
    tokens: [
      { id: 't-1', word: 'The', pos: 'determiner', role: 'determiner', roleLabel: 'Definite Article', clauseId: 'c-main', clauseName: 'Principal Clause', modifiesTarget: 'scientist' },
      { id: 't-2', word: 'research', pos: 'noun', role: 'adjective_modifier', roleLabel: 'Noun Adjunct', clauseId: 'c-main', clauseName: 'Principal Clause', modifiesTarget: 'scientist' },
      { id: 't-3', word: 'scientist', pos: 'noun', role: 'subject', roleLabel: 'Subject Head', clauseId: 'c-main', clauseName: 'Principal Clause' },
      { id: 't-4', word: 'proved', pos: 'verb', role: 'predicate_verb', roleLabel: 'Transitive Verb', clauseId: 'c-main', clauseName: 'Principal Clause' },
      { id: 't-5', word: 'that', pos: 'conjunction', role: 'subordinating_conjunction', roleLabel: 'Complementizer (Introductory Conjunction)', clauseId: 'c-noun', clauseName: 'Noun Clause' },
      { id: 't-6', word: 'greenhouse', pos: 'noun', role: 'adjective_modifier', roleLabel: 'Noun Adjunct', clauseId: 'c-noun', clauseName: 'Noun Clause', modifiesTarget: 'emissions' },
      { id: 't-7', word: 'emissions', pos: 'noun', role: 'subject', roleLabel: 'Subject of Noun Clause', clauseId: 'c-noun', clauseName: 'Noun Clause' },
      { id: 't-8', word: 'accelerate', pos: 'verb', role: 'predicate_verb', roleLabel: 'Transitive Verb', clauseId: 'c-noun', clauseName: 'Noun Clause' },
      { id: 't-9', word: 'global', pos: 'adjective', role: 'adjective_modifier', roleLabel: 'Adjective', clauseId: 'c-noun', clauseName: 'Noun Clause', modifiesTarget: 'warming' },
      { id: 't-10', word: 'warming', pos: 'noun', role: 'direct_object', roleLabel: 'Direct Object of Noun Clause', clauseId: 'c-noun', clauseName: 'Noun Clause' },
    ],
    reedKellogg: [
      {
        clauseId: 'c-main',
        clauseType: 'principal',
        subject: 'scientist',
        subjectModifiers: [
          { word: 'The', type: 'determiner' },
          { word: 'research', type: 'adjective' },
        ],
        verb: 'proved',
        verbModifiers: [],
        objectOrComplement: '[that emissions accelerate warming]',
        complementType: 'direct_object',
        objectModifiers: [],
        prepPhrases: [],
      },
      {
        clauseId: 'c-noun',
        clauseType: 'subordinate_noun',
        conjunctionToParent: {
          word: 'that',
          dashedConnectorText: 'Elevated Noun Clause pedestal functioning as Direct Object',
        },
        subject: 'emissions',
        subjectModifiers: [{ word: 'greenhouse', type: 'adjective' }],
        verb: 'accelerate',
        verbModifiers: [],
        objectOrComplement: 'warming',
        complementType: 'direct_object',
        objectModifiers: [{ word: 'global', type: 'adjective' }],
        prepPhrases: [],
      },
    ],
    syntaxTree: {
      id: 'node-root',
      label: 'S (Complex)',
      fullLabel: 'Complex Sentence with Noun Clause Object',
      category: 'clause',
      text: 'The research scientist proved that greenhouse emissions accelerate global warming.',
      children: [
        {
          id: 'np-sci',
          label: 'NP',
          fullLabel: 'Subject',
          category: 'phrase',
          children: [
            { id: 'd-sci', label: 'Det', fullLabel: 'Determiner', category: 'word', text: 'The' },
            { id: 'adj-sci', label: 'Adj', fullLabel: 'Noun Adjunct', category: 'word', text: 'research' },
            { id: 'n-sci', label: 'N', fullLabel: 'Noun', category: 'word', text: 'scientist' },
          ],
        },
        {
          id: 'vp-pr',
          label: 'VP',
          fullLabel: 'Verb Phrase',
          category: 'phrase',
          children: [
            { id: 'v-pr', label: 'V', fullLabel: 'Verb', category: 'word', text: 'proved' },
            {
              id: 'sbar-noun',
              label: 'SBAR (Noun Clause)',
              fullLabel: 'Noun Clause as Direct Object',
              category: 'clause',
              children: [
                { id: 'c-that', label: 'Comp', fullLabel: 'Complementizer', category: 'word', text: 'that' },
                {
                  id: 's-embedded',
                  label: 'S',
                  fullLabel: 'Embedded Clause',
                  category: 'clause',
                  children: [
                    { id: 'np-em', label: 'NP', fullLabel: 'Subject', category: 'phrase', text: 'greenhouse emissions' },
                    { id: 'vp-acc', label: 'VP', fullLabel: 'Verb Phrase', category: 'phrase', text: 'accelerate global warming' },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  },

  // Class 11-12: Compound-Complex Sentence
  {
    id: 'preset-compound-complex-1',
    sentence: 'Although the torrential monsoon flooded the lowlands, the resilient villagers fortified the stone embankment, and the rescue boats evacuated the stranded families safely.',
    classification: 'compound-complex',
    classLevelRecommendation: 'Class 11',
    strand: 'Compound-Complex Architecture & Multi-Clause Orchestration',
    pedagogicalNotes:
      'A masterpiece of multi-clause coordination and subordination: two independent clauses joined by "and", with the first independent clause governed by an initial adverbial clause of concession introduced by "Although".',
    clauses: [
      {
        id: 'c-sub',
        type: 'subordinate_adverb',
        typeName: 'Subordinate Adverbial Clause (Concession)',
        color: 'emerald',
        text: 'Although the torrential monsoon flooded the lowlands',
        conjunction: 'Although',
        functionInSentence: 'Modifies the first independent clause.',
        subject: {
          text: 'the torrential monsoon',
          headNoun: 'monsoon',
          modifiers: ['the', 'torrential'],
        },
        predicate: {
          verbPhrase: 'flooded',
          tense: 'Simple Past Active',
          transitivity: 'transitive',
          directObject: 'the lowlands',
          adverbials: [],
        },
      },
      {
        id: 'c-main-1',
        type: 'principal',
        typeName: 'Independent Clause 1',
        color: 'indigo',
        text: 'the resilient villagers fortified the stone embankment',
        functionInSentence: 'First independent proposition.',
        subject: {
          text: 'the resilient villagers',
          headNoun: 'villagers',
          modifiers: ['the', 'resilient'],
        },
        predicate: {
          verbPhrase: 'fortified',
          tense: 'Simple Past',
          transitivity: 'transitive',
          directObject: 'the stone embankment',
          adverbials: [],
        },
      },
      {
        id: 'c-main-2',
        type: 'coordinate',
        typeName: 'Independent Clause 2',
        color: 'cyan',
        text: 'the rescue boats evacuated the stranded families safely',
        conjunction: 'and',
        functionInSentence: 'Second independent proposition coordinated by "and".',
        subject: {
          text: 'the rescue boats',
          headNoun: 'boats',
          modifiers: ['the', 'rescue'],
        },
        predicate: {
          verbPhrase: 'evacuated',
          tense: 'Simple Past',
          transitivity: 'transitive',
          directObject: 'the stranded families',
          adverbials: ['safely'],
        },
      },
    ],
    tokens: [
      { id: 't-1', word: 'Although', pos: 'conjunction', role: 'subordinating_conjunction', roleLabel: 'Subordinating Conjunction', clauseId: 'c-sub', clauseName: 'Subordinate Clause' },
      { id: 't-2', word: 'the', pos: 'determiner', role: 'determiner', roleLabel: 'Definite Article', clauseId: 'c-sub', clauseName: 'Subordinate Clause', modifiesTarget: 'monsoon' },
      { id: 't-3', word: 'torrential', pos: 'adjective', role: 'adjective_modifier', roleLabel: 'Adjective', clauseId: 'c-sub', clauseName: 'Subordinate Clause', modifiesTarget: 'monsoon' },
      { id: 't-4', word: 'monsoon', pos: 'noun', role: 'subject', roleLabel: 'Subject Head', clauseId: 'c-sub', clauseName: 'Subordinate Clause' },
      { id: 't-5', word: 'flooded', pos: 'verb', role: 'predicate_verb', roleLabel: 'Transitive Verb', clauseId: 'c-sub', clauseName: 'Subordinate Clause' },
      { id: 't-6', word: 'the', pos: 'determiner', role: 'determiner', roleLabel: 'Definite Article', clauseId: 'c-sub', clauseName: 'Subordinate Clause', modifiesTarget: 'lowlands' },
      { id: 't-7', word: 'lowlands', pos: 'noun', role: 'direct_object', roleLabel: 'Direct Object', clauseId: 'c-sub', clauseName: 'Subordinate Clause' },
      { id: 't-8', word: 'the', pos: 'determiner', role: 'determiner', roleLabel: 'Definite Article', clauseId: 'c-main-1', clauseName: 'Independent Clause 1', modifiesTarget: 'villagers' },
      { id: 't-9', word: 'resilient', pos: 'adjective', role: 'adjective_modifier', roleLabel: 'Adjective', clauseId: 'c-main-1', clauseName: 'Independent Clause 1', modifiesTarget: 'villagers' },
      { id: 't-10', word: 'villagers', pos: 'noun', role: 'subject', roleLabel: 'Subject Head', clauseId: 'c-main-1', clauseName: 'Independent Clause 1' },
      { id: 't-11', word: 'fortified', pos: 'verb', role: 'predicate_verb', roleLabel: 'Transitive Verb', clauseId: 'c-main-1', clauseName: 'Independent Clause 1' },
      { id: 't-12', word: 'the', pos: 'determiner', role: 'determiner', roleLabel: 'Definite Article', clauseId: 'c-main-1', clauseName: 'Independent Clause 1', modifiesTarget: 'embankment' },
      { id: 't-13', word: 'stone', pos: 'noun', role: 'adjective_modifier', roleLabel: 'Noun Adjunct', clauseId: 'c-main-1', clauseName: 'Independent Clause 1', modifiesTarget: 'embankment' },
      { id: 't-14', word: 'embankment', pos: 'noun', role: 'direct_object', roleLabel: 'Direct Object', clauseId: 'c-main-1', clauseName: 'Independent Clause 1' },
      { id: 't-15', word: 'and', pos: 'conjunction', role: 'coordinating_conjunction', roleLabel: 'Coordinating Conjunction', clauseId: 'c-main-2', clauseName: 'Independent Clause 2' },
      { id: 't-16', word: 'the', pos: 'determiner', role: 'determiner', roleLabel: 'Definite Article', clauseId: 'c-main-2', clauseName: 'Independent Clause 2', modifiesTarget: 'boats' },
      { id: 't-17', word: 'rescue', pos: 'noun', role: 'adjective_modifier', roleLabel: 'Noun Adjunct', clauseId: 'c-main-2', clauseName: 'Independent Clause 2', modifiesTarget: 'boats' },
      { id: 't-18', word: 'boats', pos: 'noun', role: 'subject', roleLabel: 'Subject Head', clauseId: 'c-main-2', clauseName: 'Independent Clause 2' },
      { id: 't-19', word: 'evacuated', pos: 'verb', role: 'predicate_verb', roleLabel: 'Transitive Verb', clauseId: 'c-main-2', clauseName: 'Independent Clause 2' },
      { id: 't-20', word: 'the', pos: 'determiner', role: 'determiner', roleLabel: 'Definite Article', clauseId: 'c-main-2', clauseName: 'Independent Clause 2', modifiesTarget: 'families' },
      { id: 't-21', word: 'stranded', pos: 'adjective', role: 'adjective_modifier', roleLabel: 'Participial Adjective', clauseId: 'c-main-2', clauseName: 'Independent Clause 2', modifiesTarget: 'families' },
      { id: 't-22', word: 'families', pos: 'noun', role: 'direct_object', roleLabel: 'Direct Object', clauseId: 'c-main-2', clauseName: 'Independent Clause 2' },
      { id: 't-23', word: 'safely', pos: 'adverb', role: 'adverb_modifier', roleLabel: 'Adverb of Manner', clauseId: 'c-main-2', clauseName: 'Independent Clause 2', modifiesTarget: 'evacuated' },
    ],
    reedKellogg: [
      {
        clauseId: 'c-main-1',
        clauseType: 'principal',
        subject: 'villagers',
        subjectModifiers: [
          { word: 'the', type: 'determiner' },
          { word: 'resilient', type: 'adjective' },
        ],
        verb: 'fortified',
        verbModifiers: [],
        objectOrComplement: 'embankment',
        complementType: 'direct_object',
        objectModifiers: [
          { word: 'the', type: 'determiner' },
          { word: 'stone', type: 'adjective' },
        ],
        prepPhrases: [],
      },
      {
        clauseId: 'c-sub',
        clauseType: 'subordinate_adverb',
        conjunctionToParent: {
          word: 'Although',
          dashedConnectorText: 'Adverb Clause of Concession',
        },
        subject: 'monsoon',
        subjectModifiers: [
          { word: 'the', type: 'determiner' },
          { word: 'torrential', type: 'adjective' },
        ],
        verb: 'flooded',
        verbModifiers: [],
        objectOrComplement: 'lowlands',
        complementType: 'direct_object',
        objectModifiers: [{ word: 'the', type: 'determiner' }],
        prepPhrases: [],
      },
      {
        clauseId: 'c-main-2',
        clauseType: 'coordinate',
        conjunctionToParent: {
          word: 'and',
          dashedConnectorText: 'Coordinating Conjunction',
        },
        subject: 'boats',
        subjectModifiers: [
          { word: 'the', type: 'determiner' },
          { word: 'rescue', type: 'adjective' },
        ],
        verb: 'evacuated',
        verbModifiers: [{ word: 'safely', type: 'adverb' }],
        objectOrComplement: 'families',
        complementType: 'direct_object',
        objectModifiers: [
          { word: 'the', type: 'determiner' },
          { word: 'stranded', type: 'adjective' },
        ],
        prepPhrases: [],
      },
    ],
    syntaxTree: {
      id: 'node-root',
      label: 'S (Compound-Complex)',
      fullLabel: 'Compound-Complex Sentence',
      category: 'clause',
      text: 'Although the torrential monsoon flooded the lowlands, the resilient villagers fortified the stone embankment, and the rescue boats evacuated the stranded families safely.',
      children: [
        {
          id: 's-complex-1',
          label: 'S1 (Complex)',
          fullLabel: 'First Independent Clause with Subordinate Clause',
          category: 'clause',
          children: [
            { id: 'sbar-adv', label: 'SBAR (Adv)', fullLabel: 'Adverbial Clause', category: 'clause', text: 'Although the torrential monsoon flooded the lowlands' },
            { id: 's-prop-1', label: 'S', fullLabel: 'Main Clause 1', category: 'clause', text: 'the resilient villagers fortified the stone embankment' },
          ],
        },
        { id: 'cc-and', label: 'CC', fullLabel: 'Coordinating Conjunction', category: 'word', text: 'and' },
        { id: 's-prop-2', label: 'S2', fullLabel: 'Second Independent Clause', category: 'clause', text: 'the rescue boats evacuated the stranded families safely' },
      ],
    },
  },
];
